### ISSUE TITLE
pub.dev example pack has issues

### ISSUE THREAD

**Issue by Protofall** [Baseflow/flutter-geolocator#574] opened 2020-11-03 03:01 UTC
## 🏗 Enhancement Proposal

The example on https://pub.dev/packages/geolocator/example has some issues. Firstly its only showing the main function which doesn't itself contain any geolocator example code, secondly the link to the source file is broken

### Pitch

This is useful because although the readme does a good job at explaining many features, it is a bit uncertain how they work in practice (Eg Asking the user to update their settings)

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] pub.dev

**Comment by mvanbeusekom** [comment] 2020-11-03 07:30
Duplicate of #547. I will close this issue and track progress in #547, thanks for reporting.

**Closed by mvanbeusekom** 2020-11-03 07:30 UTC
Labels: type: duplicate
