### ISSUE TITLE
getCurrentPosition method trigger didChangeAppLifecycleState of flutter

### ISSUE THREAD

**Issue by nirav4273** [Baseflow/flutter-geolocator#396] opened 2020-02-23 12:27 UTC
When `getCurrentPosition()` it's also change `AppLifeCycleState`. 
Basically i am trying to get location when app `resume` so i used `didChangeAppLifecycleState` of flutter. In code it's trigger infinite when getCurrentPosition() called.

Sample Code 

```
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class CreateBug extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return CreateBugState();
  }
}

class CreateBugState extends State<CreateBug> with WidgetsBindingObserver{

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    Geolocator().getCurrentPosition().then((res){
      print(res);
    });
    WidgetsBinding.instance.addPostFrameCallback((res){
      print(res);
    });
  }
  // This section call each time on  `getCurrentPosition()` 
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print(state);
    // Fetch location again on `resumed` state.
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      key: _scaffoldKey,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Container(
          ),
        ),
      ),
    );
  }
}

```

Logs:

```
 AppLifecycleState.inactive
E/location_permissions(22373): Flutter result object is null.
I/flutter (22373): AppLifecycleState.resumed
D/DecorView(22373): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@da22870[MainActivity]
I/flutter (22373): AppLifecycleState.inactive
I/flutter (22373): AppLifecycleState.resumed
.
.
.
.
.
```

**Comment by nirav4273** [comment] 2020-03-07 10:36
Is there any update about this issue ?

**Comment by habilgur** [comment] 2020-03-16 19:28
Hello nirav4273,
I also check location change when app resume here what i used..
It calls only one time. I hope itwill help..

class _ScheduleScreenState extends State<ScheduleScreen> {
  void _onAfterBuild(BuildContext context) {
    Provider.of<CoreProvider>(context, listen: false).fetchDataFromAppOpeningOrOnResume();
  }

  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _onAfterBuild(context));
  }

  @override
  Widget build(BuildContext context) {
  .....

**Comment by nirav4273** [comment] 2020-05-16 05:36
@habilgur https://github.com/Baseflow/flutter-geolocator/issues/396#issuecomment-599719911.
Need to use provider to manage this issue ?
Why we need provider in this flow ?

**Comment by mvanbeusekom** [comment] 2020-09-03 15:38
I can confirm that the geolocator doesn't call or handle any life-cycle event by it self. I have tested it with the following application (and geolocator 6.0.0):

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Geolocator #396'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState 
  extends State<MyHomePage>
  with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
    getCurrentPosition().then((position) => print('Start: $position'));
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print(state);
    getCurrentPosition().then((position) => print('Resume: $position'));
  }

  @override
  Widget build(BuildContext context) {
   return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),// This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```

Note that I also added the following permission to my AndroidManifest.xml file:

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

The output of the application is as follows (everything is called exactly once):

```
I/flutter ( 4623): Start: Latitude: 52.1577067, Longitude: 5.387015
I/flutter ( 4623): AppLifecycleState.inactive
I/flutter ( 4623): Resume: Latitude: 52.1577083, Longitude: 5.3870147
D/EGL_emulation( 4623): eglMakeCurrent: 0xe201a120: ver 3 0 (tinfo 0xc7b6ee00)
I/flutter ( 4623): AppLifecycleState.paused
I/flutter ( 4623): Resume: Latitude: 52.1577077, Longitude: 5.3870148
I/flutter ( 4623): AppLifecycleState.resumed
E/Surface ( 4623): getSlotFromBufferLocked: unknown buffer: 0x200
W/libEGL  ( 4623): EGLNativeWindowType 0xcaf51808 disconnect failed
D/EGL_emulation( 4623): eglMakeCurrent: 0xea1bc720: ver 3 0 (tinfo 0xea254ea0)
D/EGL_emulation( 4623): eglMakeCurrent: 0xe201a120: ver 3 0 (tinfo 0xc7b6ee00)
D/EGL_emulation( 4623): eglMakeCurrent: 0xea1bc720: ver 3 0 (tinfo 0xea254ea0)
I/flutter ( 4623): Resume: Latitude: 52.1578421, Longitude: 5.3869821
```

I will close this ticket since I don't think it is related to the geolocator.

**Closed by mvanbeusekom** 2020-09-03 15:38 UTC
Labels: status: triage

**Comment by michael-chiu** [comment] 2022-03-08 15:16
I have the same issue, I found that it will not trigger "AppLifecycleState.resumed" if you have granted the location permission. But if you have rejected the permission, then it will throw PlatformException, and triggered the "AppLifecycleState.resumed", and if you have put the getCurrentPosition() logic in the resume callback, it will trigger an infinite loop, as it will throw PlatformException and trigger "AppLifecycleState.resumed" again. Please have a look. Thanks a lot.

**Comment by tree1891** [comment] 2022-04-09 06:41
After grant the location permission, getCurrentPosition() is called, but same issue.

**Comment by jaimin1531** [comment] 2022-07-05 13:14
I am also facing this issue

**Comment by mvanbeusekom** [comment] 2022-07-05 13:40
The most likely reason this happens is that permissions are requested. On Android the permission system will put the current app to the background and bring it back in the foreground after requesting the permissions. This is causing the `didChangeAppLifecycleState` method to be triggered. 

When using geolocator version below 8.0.0 this can be caused be the `getCurrentPosition` method itself as it will try to handle permissions internally. If you are using pre-8.0.0 version the suggestion would be to update to the latest version.

Since version 8.0.0 and later the `getCurrentPosition` no longer tries to handle permissions and this issue can be caused by manually requesting permissions (using the `requestPermission` method). To avoid getting stuck in a loop make sure you are not requesting permissions in the `didChangeAppLifecycleState` method.

A more detailed explanation and possible solutions are discussed in this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1056#issuecomment-1122167349) on issue #1056.

**Comment by jaimin1531** [comment] 2022-07-05 14:16
Thanks for the quick reply
i am using the latest version of the plugin only and `getCurrentPosition` is not calling that method. i will stop using `requestPermission` method in `didChangeAppLIfeCycleState`.

**Comment by jaimin1531** [comment] 2022-08-05 08:09
Hello @mvanbeusekom 
i get this issue again in samsung device. when i call `getCurrentPosition` method in samsung device it triggers the `didChangeAppLifeCycleState` method.

**Comment by mvanbeusekom** [comment] 2022-08-05 08:58
@jaimin1531 can you collect a stacktrace on the Android side? 

Are you sure this is triggered by the `getCurrentPosition` method?

Maybe you can supply a small example app reproducing the issue?

**Comment by jaimin1531** [comment] 2022-08-05 10:37
I don't have any code example. but will build one and share with you. I am facing this issue in only one device.
My code flow is something like
i call this function on google maps `onCameraIdle` function trigger
