### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by inceptusp** [Baseflow/flutter-geolocator#503] opened 2020-09-02 01:34 UTC
## 🔙 Regression

After upgrading to 6.0.0+1 I started to receive an exception as a warning on console multiple times

### Old (and correct) behavior

Not having an exception

### Reproduction steps

Just ask the position and the error appears after a while

### Configuration

**Version:** 6.0.0+1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

### Console output

```
W/ConnectionTracker( 1662): Exception thrown while unbinding
W/ConnectionTracker( 1662): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjf@5516abb
W/ConnectionTracker( 1662):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)
W/ConnectionTracker( 1662):     at android.app.ContextImpl.unbindService(ContextImpl.java:1847)
W/ConnectionTracker( 1662):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)
W/ConnectionTracker( 1662):     at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker( 1662):     at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zzin.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.1:246)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zzin.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.1:263)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zzin.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.1:330)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zziq.zza(com.google.android.gms:play-services-measurement-impl@@17.4.1:2)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zzah.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:7)
W/ConnectionTracker( 1662):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 1662):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 1662):     at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:21)
```

**Comment by mvanbeusekom** [comment] 2020-09-02 08:49
@inceptusp this seems like an issue with the Google Play Services. Do you have Google Play Services installed on your device?

Did you use the `forceAndroidLocationManager` property with the previous versions of the Geolocator plugin? If so you can now pass this as a parameter to the `getCurrentPosition` and `getPositionStream` methods. This will force Android to use the legacy `LocationManager` instead of the `FusedLocationProviderClient` (which requires Google Play Services).

**Comment by inceptusp** [comment] 2020-09-02 08:53
@mvanbeusekom Yes, I have Google Play Services... It is a Samsung Galaxy J6, the same device I was using before the update... I never used the ```forceAndroidLocationManager``` property...

**Comment by GrahamDi** [comment] 2020-09-02 10:06
@mvanbeusekom @inceptusp 

FYI. I have also been seeing this error after I upgraded to 6.0.0+1. When I revert to 5.3.2+2 it goes away again. I have moved my  geocoding calls to geocoding 1.0.3  and that is working fine. The issue is definitely with geolocator 6.0.0+1. I also don't use forceAndroidLocationManager and I use Play Services.

**Comment by loooookiezxc** [comment] 2020-09-02 12:13
I also saw this recently, correct me if I'm wrong but ```com.google.android.gms.measurement.internal``` came from Firebase Analytics API. Maybe the firebase plugin and geolocator are communicating in some ways. Also saw this issue on the Firebase Core plugin.

**Comment by mvanbeusekom** [comment] 2020-09-02 14:43
@GrahamDi @inceptusp it looks like it is related to this [issue](https://github.com/firebase/firebase-android-sdk/issues/1662) and I noticed that we indeed bring in the `com.google.android.gms:play-services-base:17.3.0` as part of the geolocator build.gradle file. 

This should be fixed by removing the line, but I need to test this out. I will do so today / tomorrow and then make a new release.

**Comment by mvanbeusekom** [comment] 2020-09-03 13:57
Hi @inceptusp and @GrahamDi, I have just release version 6.0.0+2 of the geolocator plugin where I removed the `com.google.android.gms:play-services-base:17.3.0` line from the geolocator's `build.gradle` file. Is it possible for one of you to test if this solved the problem? I would really appreciate that.

**Comment by mvanbeusekom** [comment] 2020-09-03 21:37
Glad to hear! Thanks for the feedback and posting the bug report!

Will close the issue, if the error pops up again let me know and I’ll reopen it again

**Closed by mvanbeusekom** 2020-09-03 21:37 UTC
Labels: platform: android, status: in progress, type: bug

**Comment by GrahamDi** [comment] 2020-09-04 14:57
Finally got around to testing it. Working fine for me also. Thanks a lot for fixing so quickly.

**Comment by LewisGartonFSSI** [comment] 2020-11-17 22:23
TODO 
1. Remove  Service not registered: com.google.android.gms.measurement.internal
2. Get Unit Test Running 
3. Get jacoco test running

**Comment by KingAlawaka** [comment] 2020-11-21 01:23
Add the following to your android\app\build.gradle

```
implementation 'com.google.android.gms:play-services-basement:17.5.0'
implementation 'com.google.firebase:firebase-analytics:18.0.0'
```

**Comment by kbrmimbyl** [comment] 2020-12-02 11:31
I'm seeing the problem in Version 6.0.0+4 and this line solves it:
`implementation 'com.google.android.gms:play-services-basement:17.5.0'`
h/t @KingAlawaka

**Comment by amroomi** [comment] 2020-12-10 11:15
> Glad to hear! Thanks for the feedback and posting the bug report!
> 
> Will close the issue, if the error pops up again let me know and I’ll reopen it again

I still have the same issue.

pubspec.yaml file
`cupertino_icons: ^1.0.1
firebase_core: ^0.5.3
firebase_auth: ^0.18.4+1
firebase_database: ^4.4.0`

Project level build.gradle
`dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.4'
}`

App level build.gradle
`apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

dependencies {
    implementation platform('com.google.firebase:firebase-bom:26.1.1')
}`

The error occurs after adding this line to App level build.gradle file
`apply plugin: 'com.google.gms.google-services'`

**Comment by mvanbeusekom** [comment] 2020-12-10 13:31
@amroomi not sure I can help here, your listing of the `pubspec.yaml` doesn't mention you are using the "geolocator" plugin. 

Looks like this has to do something with the other "firebase" plugins, this issue is still open for those plugins: https://github.com/firebase/firebase-android-sdk/issues/1662

**Comment by amroomi** [comment] 2020-12-10 14:04
@mvanbeusekom I am not using geolocator plugin I am only using firebase core, auth and database plugins.

**Comment by mvanbeusekom** [comment] 2020-12-10 14:13
Yes but you are raising this issue in the geolocator repository. We maintain the geolocator and have no relation to the firebase plugins.

**Comment by sontn15** [comment] 2020-12-11 16:22
Same me

W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lu@c38f59c
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1671)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):1)
        at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):2)
        at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):9)
        at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
        at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):5)

**Comment by sebastien-michel** [comment] 2020-12-11 18:19
> 
> 
> Same me
> 
> W/ConnectionTracker: Exception thrown while unbinding
> java.lang.IllegalArgumentException: Service not registered: lu@c38f59c
> at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1671)
> at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
> at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
> at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):1)
> at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):2)
> at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):9)
> at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
> at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):5)

I have now the same error, didn't touch my code and it was working 2 days ago...

**Comment by mvanbeusekom** [comment] 2020-12-11 18:25
@sontn15, @sebastien-michel, just to make sure are you both using the geolocator plugin?

Do you depend on any other packages (i.e. firebase)?

Could you provide some additional information? Mostly the contents of the `pubspec.yaml`, `build.gradle` and the output of the `flutter doctor -v` command.

**Comment by inceptusp** [comment] 2020-12-11 18:30
@sontn15 @sebastien-michel this error is a bug on firebase_core tracked by this issue: https://github.com/FirebaseExtended/flutterfire/issues/4090

It was a bug on Geolocator but @mvanbeusekom has fixed it... You should complain with flutterfire team... I am too receiving this same messages using firebase_admob since it requires firebase_core witch is the cause of the issue...

**Comment by Nasar-uddin** [comment] 2020-12-12 17:56
The same problem while login in firebase with Facebook 

W/ConnectionTracker(26498): Exception thrown while unbinding
W/ConnectionTracker(26498): java.lang.IllegalArgumentException: Service not registered: ls@76dcf29
W/ConnectionTracker(26498): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker(26498): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1786)

**Comment by dulkith** [comment] 2020-12-14 01:45
W/ConnectionTracker( 4736): Exception thrown while unbinding
W/ConnectionTracker( 4736): java.lang.IllegalArgumentException: Service not registered: ls@c33423gd
W/ConnectionTracker( 4736): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
W/ConnectionTracker( 4736): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
W/ConnectionTracker( 4736): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
W/ConnectionTracker( 4736): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):1)
W/ConnectionTracker( 4736): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):2)
W/ConnectionTracker( 4736): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):9)
W/ConnectionTracker( 4736): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):3)
W/ConnectionTracker( 4736): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):3)
W/ConnectionTracker( 4736): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 4736): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 4736): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713100@20.47.13 (150700-0):5)

**Comment by inceptusp** [comment] 2020-12-14 01:48
@Nasar-uddin @dulkith https://github.com/Baseflow/flutter-geolocator/issues/503#issuecomment-743354564

**Comment by vsalamov** [comment] 2020-12-14 13:06
Same problem with atttempt show admob test ad

**Comment by mvanbeusekom** [comment] 2020-12-14 13:13
@Nasar-uddin, @dulkith, @vsalamov, really curious why you are posting these problems here? How does this related to the geolocator plugin?

Please provide information on why you think this problem has to do with the geolocator plugin (since we solved this issue months ago). If you are having this issue and do not make use of the  geolocotor plugin, the answer is: you are in the wrong place, please post this issue in the correct location (if you are experiencing this problem in combination with Firebase, read through issue FirebaseExtended/flutterfire#4090, they document workarounds (for example [here](https://github.com/FirebaseExtended/flutterfire/issues/4090#issuecomment-725420953)).

**Comment by inceptusp** [comment] 2020-12-14 20:36
@mvanbeusekom I think you should lock this thread for now... They are posting these things here because when you search the error on Google it leave them here...
