### ISSUE TITLE
Location doesn't work on IOS emulator

### ISSUE THREAD

**Issue by LarryJing** [Baseflow/flutter-geolocator#453] opened 2020-06-04 00:54 UTC
### Expected behavior
Expect to print the position, this is the code:
    Geolocator geo = Geolocator();
    Position pos =
        await geo.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
    print(pos);

### Reproduction steps
It works on the Android emulator-position gets printed to console.
Doesn't work on iOS emulator, nothing gets printed and if I add another print statement after print(pos), it doesn't print either. I'm guessing it never got the position so its "await"ing forever?

### Configuration
iPhone 11 emulator on Android studio

**Version:** 1.x

**Platform:** 
:iphone: iOS

**Comment by mvanbeusekom** [comment] 2020-06-04 11:22
@LarryJing I cannot reproduce this problem, did you actually simulate location updates? On the iOS simulator you need to actively set a location using the following menu option: "Features" -> "Location":
  
<img width="756" alt="Screenshot 2020-06-04 at 13 21 49" src="https://user-images.githubusercontent.com/13098888/83750955-5ddf1f00-a666-11ea-8b75-4165074df01f.png">

**Comment by mitLinkwok** [comment] 2020-06-04 13:14
yes, I have also got an error on this plugin in ios simulator. i am getting this log on console.
<img width="1077" alt="Screenshot 2020-06-04 at 6 42 49 PM" src="https://user-images.githubusercontent.com/44049045/83760919-3d798980-a693-11ea-9410-5d5a161990e5.png">

**Comment by aya-eiya** [comment] 2020-06-04 13:37
> yes, I have also got an error on this plugin in ios simulator. i am getting this log on console.
> <img alt="Screenshot 2020-06-04 at 6 42 49 PM" width="1077" src="https://user-images.githubusercontent.com/44049045/83760919-3d798980-a693-11ea-9410-5d5a161990e5.png">

I have got same error too.

**Comment by aya-eiya** [comment] 2020-06-04 13:58
the error does not occur when the module version change to `5.3.1`.

**Comment by kundanlal555** [comment] 2020-06-04 14:46
![Screenshot 2020-06-04 at 8 15 06 PM](https://user-images.githubusercontent.com/32810208/83771646-1ffeec80-a6a0-11ea-8316-d376469d41eb.png)
By adding location update permission ,this issue solve

**Comment by MisterJimson** [comment] 2020-06-04 15:06
I am also running into this. I do not want to request location in the background, only foreground. I would hope that means I shouldn’t need to enable a background mode.

**Comment by mvanbeusekom** [comment] 2020-06-04 15:36
This is indeed an error that went live by mistake. I will correct it later today/ tomorrow. Until then either enable location updates in the background or stick with 5.3.1

**Comment by mvanbeusekom** [comment] 2020-06-04 20:19
I have just released a hotfix which should fix this issue. The option to enable Backgroup location updates is now configurable using the `EnableBackgroundLocationUpdates` key in your `Info.plist` (see also the [README.md](https://github.com/Baseflow/flutter-geolocator/blob/develop/README.md) in the iOS section).

Thanks everybody for helping debug this. Please let me know if it works correctly again.

**Comment by mvanbeusekom** [comment] 2020-06-09 06:55
Confirmed fix, closing the issue.

**Closed by mvanbeusekom** 2020-06-09 06:55 UTC
Labels: platform: ios, status: in progress, type: bug

**Comment by normancarcamo** [comment] 2020-06-30 14:17
Hi there, I'm new here using geolocation services with flutter and I've found this project, looks good, but I have a problem when I try to get the current location, the application stops and it gets closed after pressing a simple button to get the location... 

This is the current code I use in the onPress event handler in a dummy class:

```dart
GeolocationStatus geolocationStatus  = await Geolocator().checkGeolocationPermissionStatus();

if (geolocationStatus == GeolocationStatus.granted) {
  Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
  print('position $position');
}
```

and this is the version of the package I'm using in `pubspec.yaml`:
```yaml
geolocator: ^5.3.2+2
```

And these are the keys I have added to the `info.plist` file:
```xml
  <!-- ...skipped by brevity -->
  <key>EnableBackgroundLocationUpdates</key>
  <true/>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>This app needs access to location when open.</string>
  <key>NSLocationAlwaysUsageDescription</key>
  <string>This app needs access to location when in the background.</string>
  <key>NSLocationAlwaysAndWhenInUsageDescription</key>
  <string>Always And In Use Permission</string>
  <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  <string>This app needs access to location when open and in the background.</string>
  <!-- skipped by brevity... -->
```

@mvanbeusekom any idea of what do you think I'm doing wrong?

**Comment by markbeij** [comment] 2020-11-11 13:17
@mvanbeusekom, the link doesn't seem to work and other then this issue, I can't find any reference regarding `EnableBackgroundLocationUpdates`. Love this package btw..

**Comment by mvanbeusekom** [comment] 2020-11-11 16:16
@markbeij, correct the link mentioned was part of the 5.3.1 release. Currently we are on a much improved version 6.1.6 which has an updated folder structure to support the federated plugin architecture (which makes things easier to support multiple platforms).

The current link to the README.md is: https://github.com/Baseflow/flutter-geolocator/blob/master/README.md

The section regarding the background mode is:

>If you would like to receive updates when your App is in the background, you'll also need to add the Background Modes capability to your XCode project (Project > Signing and Capabilities > "+ Capability" button) and select Location Updates. Be careful with this, you will need to explain in detail to Apple why your App needs this when submitting your App to the AppStore. If Apple isn't satisfied with the explanation your App will be rejected.

This will basically add the `EnableBackgroundLocationUpdates` parameter to your `Info.plist`. Note that the geolocator doesn't support running in the background and it doesn't provide any way to receive updates while running in the background. At the moment the only thing `EnableBackgroundLocationUpdates` will do is tell the platform to keep on listening to location updates on the platform while the app is in the background (nothing gets called or executed otherwise).

**Comment by Abdullah104** [comment] 2022-05-01 03:15
> ![Screenshot 2020-06-04 at 8 15 06 PM](https://user-images.githubusercontent.com/32810208/83771646-1ffeec80-a6a0-11ea-8316-d376469d41eb.png) By adding location update permission ,this issue solve

Solved my problem. Thanks
