### ISSUE TITLE
Let Geolocator.getCurrentPosition finish less than one second on iOS

### ISSUE THREAD

**Issue by reedom** [Baseflow/flutter-geolocator#851] opened 2021-10-02 06:49 UTC
## 🏗 Enhancement Proposal

On iOS, use `CLLocationManager:startUpdatingLocation` over `CLLocationManager:requestLocation` 
on any iOS versions.

### Pitch

https://github.com/Baseflow/flutter-geolocator/blob/master/geolocator_apple/apple/Classes/Handlers/GeolocationHandler.m#L31-L34
```objectivec
- (void)requestPosition:(GeolocatorResult _Nonnull)resultHandler
           errorHandler:(GeolocatorError _Nonnull)errorHandler {
  self.errorHandler = errorHandler;
  self.resultHandler = resultHandler;
  
  if (@available(iOS 9.0, macOS 10.14, *)) {
    [self.locationManager requestLocation];
    return;
  }
  
  [self startUpdatingLocationWithDesiredAccuracy:kCLLocationAccuracyBest
                                  distanceFilter:kCLDistanceFilterNone];
}
```

Currently it calls `CLLocationManager:requestLocation` on iOS 9 or later devices but it's considerably slow.
One of my device, iPhone7(iOS13), takes about 10 seconds to get a result.
But calling `CLLocationManager:startUpdatingLocation` took less than a second.
(I don't have any clear idea why the speed is so different but [folks say so, too](https://stackoverflow.com/questions/42245571/cllocationmanager-is-slow-getting-location-swift))

Does the use of `CLLocationManager:requestLocation` has any strong purpose?
If not, skipping it would be preferable.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-10-02 11:12
The problem is that the `startUpdatingLocation` method starts a stream that first returns the cached last known location which is often not the device's current location.

The `requestLocation` method internally acts the same as the `startUpdatingLocation` method but skips the first two results before returning and thus being sure this is the device's real location. 

If you don't care about the precision of the location you could use the `getLastKnowPosition` method or listen to the `getPositionStream` and use the first result. If you want an accurate location fix however you should use the `getCurrentPosition` or listen to the `getPositionStream` and skip the first two results. Unfortunately the last takes several seconds (indeed this can take up to 10 seconds or more for the first location fix). This is also mentioned in Apple's [documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation).

Of course I am open for alternatives or other ways that might improve the performance if it doesn't impact the quality of the result. So please if I am missing something let me know.

In meantime I will close this issue as I believe switching back to `startLocationUpdates` is not a good solution (we have done this earlier and received several complaints from users they only get the inaccurate last known position).

**Closed by mvanbeusekom** 2021-10-02 11:12 UTC

**Comment by reedom** [comment] 2021-10-03 01:35
@mvanbeusekom 
Thanks for letting me know the in detail background.

I think it'd be nice to be documented while it's great knowledge.
Without it I hesitate to call `getLastKnowPosition` but now I love to call both APIs for last and current.
In other words, the information bring me a design choice. Possibly for other developers, too.
