### ISSUE TITLE
Response time exactly 10 seconds Lib iOS 1.2.2

### ISSUE THREAD

**Issue by erickbrittes** [Baseflow/flutter-geolocator#909] opened 2021-12-02 02:14 UTC
Problems with lib version: "1.2.2", location request return exactly in 10 seconds, while a lib 1.0.0 response in between 2 seconds

**Comment by mvanbeusekom** [comment] 2021-12-02 07:52
Hi @erickbrittes,

It is expected behaviour and explained in more detail in issue #887. Older versions (pre-7.6.0) of the geolocator actually contained a bug when fetching the current position (see issue #629) which was fixed in [version 7.6.0](https://pub.dev/packages/geolocator/changelog#760). 

However I am curious what you mean with `Lib iOS 1.0.0` and `Lib iOS 1.2.2`, which libraries are you talking about?

**Comment by SergeShkurko** [comment] 2021-12-03 14:04
@erickbrittes 

You can use cached location for better performance
```dart
Position? position = await Geolocator.getLastKnownPosition();
if (position == null) {
  position = await Geolocator.getCurrentPosition();
}
```

**Comment by janhecker** [comment] 2021-12-16 02:45
@mvanbeusekom Hey, I read your comment #887 and I understood some things (not all because I'm a beginner). But we use geolocator plugin in our app and I justed wanted to ask you wether the bug will be fixed with the long iOS load and if so, when approx.?

**Closed** 2021-12-16 08:22 UTC
Labels: status: needs more info, platform: ios

**Comment by mvanbeusekom** [comment] 2021-12-16 08:25
Hi @janhecker,

This is not a bug and intended behaviour from Apple, meaning there is nothing for me to "fix". This is also explained in my comment on issue #887.
