### ISSUE TITLE
Getting current location on iOS takes 10+ seconds

### ISSUE THREAD

**Issue by leonidlist** [Baseflow/flutter-geolocator#887] opened 2021-11-02 17:32 UTC
## 🐛 Bug Report

Call of `getCurrentPosition` takes about 10000ms. Tested on example app.

![image](https://user-images.githubusercontent.com/18485070/139915372-c13fa602-710e-4daf-883d-62877bca5576.png)

### Expected behavior

Getting current location takes less time.

### Reproduction steps

Launching on real device

https://user-images.githubusercontent.com/18485070/139915799-29e4155f-f36c-440e-b2d8-a76891e11d4f.MP4

### Configuration

iPhone 13 Pro, iOS 15.0.2

**Version:** 7.7.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-11-02 20:01
Hi @leonidlist,

This is expected behaviour and even [documented by Apple](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation?language=objc) (al though they try to soften it):

>Calling it causes the location manager to obtain a location fix (which may take several seconds)

The problem is that the `startUpdatingLocation` method starts a stream that first returns the cached last known location which is often not the device's current location.

The `requestLocation` method internally acts the same as the `startUpdatingLocation` method but skips the first two results before returning and thus being sure this is the device's real location. 

If you don't care about the precision of the location you could use the `getLastKnowPosition` method or listen to the `getPositionStream` and use the first result. If you want an accurate location fix however you should use the `getCurrentPosition` or listen to the `getPositionStream` and skip the first two results. Unfortunately the last takes several seconds (indeed this can take up to 10 seconds or more for the first location fix). This is also mentioned in Apple's [documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation).

Of course I am open for alternatives or other ways that might improve the performance if it doesn't impact the quality of the result. So please if I am missing something let me know.

In meantime I will close this issue as I believe switching back to `startLocationUpdates` is not a good solution (we have done this earlier and received several complaints from users they only get the inaccurate last known position).

**Closed by mvanbeusekom** 2021-11-02 20:01 UTC

**Comment by janhecker** [comment] 2021-12-18 10:16
> Hi @leonidlist,
> 
> This is expected behaviour and even [documented by Apple](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation?language=objc) (al though they try to soften it):
> 
> > Calling it causes the location manager to obtain a location fix (which may take several seconds)
> 
> The problem is that the `startUpdatingLocation` method starts a stream that first returns the cached last known location which is often not the device's current location.
> 
> The `requestLocation` method internally acts the same as the `startUpdatingLocation` method but skips the first two results before returning and thus being sure this is the device's real location.
> 
> If you don't care about the precision of the location you could use the `getLastKnowPosition` method or listen to the `getPositionStream` and use the first result. If you want an accurate location fix however you should use the `getCurrentPosition` or listen to the `getPositionStream` and skip the first two results. Unfortunately the last takes several seconds (indeed this can take up to 10 seconds or more for the first location fix). This is also mentioned in Apple's [documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation).
> 
> Of course I am open for alternatives or other ways that might improve the performance if it doesn't impact the quality of the result. So please if I am missing something let me know.
> 
> In meantime I will close this issue as I believe switching back to `startLocationUpdates` is not a good solution (we have done this earlier and received several complaints from users they only get the inaccurate last known position).

@mvanbeusekom Hey Maurits, regarding that known issue. I asked our developer and he said that the biggest problem with geolocator is: we get the stream from geolocator but the first result / location we receive from geolocator takes also 10 (or so) seconds. It would be very good if we can get every location even if the first three locations aren't that accurate...

**Comment by mvanbeusekom** [comment] 2021-12-18 11:05
Hello @janhecker, 

It is possible that when the phone doesn't have any cached location stored also the stream will need time determining the position, especially when the accuracy is set to high or best. 

The code used to setup the stream is a one-to-one connection to the Apple CLLocationManager API which makes it seem unlikely that their is something wrong with the code in the geolocator it self. Please feel free to have a look yourself (or one of your developers).

Please also ask your developers to post some additional information which might enable us to help out. For example a small demonstration application which shows the same behaviour or a code snippet that shows how the geolocator is called in the application being affected.
