### ISSUE TITLE
App freeze when launch after killing it

### ISSUE THREAD

**Issue by MSyarifH** [Baseflow/flutter-geolocator#1220] opened 2023-02-15 09:03 UTC
## 🐛 Bug Report

during development process the app running normal, but when i build in release package whenever i close or kill the app and reopen it  the app freeze a few second sometime not responding pop up appear  

after investigate it, i try remove this plugin and the app running normal, relaunch the app duration not freeze again

### Expected behavior
the app launch duration no event 1 second when using this plugin

### Reproduction steps
when the app fisrt run from flutter run command

> [  +24 ms] D/FlutterGeolocator(12485): Creating service.
[        ] D/FlutterGeolocator(12485): Binding to location service.
[ +140 ms] D/FlutterGeolocator(12485): Flutter engine connected. Connected engine count 1
[+1914 ms] I/flutter (12485): tokenFCM

the next proses appear after around 1900ms 

after i close/ kill the app and open again
> [  +15 ms] D/FlutterGeolocator(13118): Creating service.
[        ] D/FlutterGeolocator(13118): Binding to location service.
[  +28 ms] D/FlutterGeolocator(13118): Flutter engine connected. Connected engine count 1
[+30050 ms] I/flutter (13118): firstRun false

the app freeze around 30000ms until next prosses appear

sometimes like this
> [  +14 ms] D/FlutterGeolocator(14467): Creating service.
[   +2 ms] D/FlutterGeolocator(14467): Binding to location service.
[  +28 ms] D/FlutterGeolocator(14467): Flutter engine connected. Connected engine count 1
[+29560 ms] F/crash_dump64(14560): crash_dump.cpp:509] failed to attach to thread 707: Permission denied
[ +507 ms] I/flutter (14467): firstRun false

### Configuration

**Version:** 

geolocator: 9.0.2
Flutter Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1105]

**Platform:** 
- [ ] :robot: Android

**Comment by MSyarifH** [comment] 2023-02-15 09:43
###update

after closing it and reopen the apps while gps service is on the app freeze
but 
after closing it and reopen the apps while gps service is off the app not freeze

**Comment by MSyarifH** [comment] 2023-02-15 15:59
### update

idk what wrong with my code, but after blindly observe the closed issue i found a solution using [this ](https://github.com/transistorsoft/flutter_background_geolocation/issues/933#issuecomment-1407797107) i have try using the newest but sadly still got the error

**Comment by MSyarifH** [comment] 2023-02-15 16:00
> ### update
> idk what wrong with my code, but after blindly observe the closed issue i found a solution using [this ](https://github.com/transistorsoft/flutter_background_geolocation/issues/933#issuecomment-1407797107) (not to far from latest plugin version ) i have try using the newest version of the plugin but sadly still got the error

**Comment by bnayagrawal** [comment] 2023-02-17 08:16
I am facing a similar issue. If I try to open the app when location service is enabled then the app is stuck in the splash screen and after a few second the app is force closed by the system. If I turn off location service and launch the app then the app launches fine and doesn't freeze. I am using Geolocator "9.0.2" on Flutter 3.7.3. Android 13 on Oneplus 9 pro.

Please help fix this issue.

**Comment by TusharFA** [comment] 2023-02-21 04:47
Facing same issue. Any viable solution for this ?

**Comment by MSyarifH** [comment] 2023-02-21 07:51
for @bnayagrawal and @TusharFA have you try using this

```
dependency_overrides: 
    geolocator: 9.0.1 
    geolocator_android: 4.1.4
```

mine fixed after add that to pubspec.yaml

**Comment by DmitriySimonov** [comment] 2023-02-28 13:00
I am use flutter  3.7.5
i need this version of flutter
When can we expect an update so that everything works stably for the new flutter?

**Comment by DmitriySimonov** [comment] 2023-02-28 13:07
> for @bnayagrawal and @TusharFA have you try using this
> 
> ```
> dependency_overrides: 
>     geolocator: 9.0.1 
>     geolocator_android: 4.1.4
> ```
> 
> mine fixed after add that to pubspec.yaml

Not work on flutter 3.7.x

**Comment by singhtaranjeet** [comment] 2023-03-10 07:44
Is there any progress on this?? not working on latest flutter version

**Comment by nirranthea** [comment] 2023-03-28 08:21
I have same issue on Flutter 3.7.7 and Geolocator 9.0.2.
For now, I downgrade the plugin to 7.4.0 and the freeze is gone.

**Comment by JeroenWeener** [comment] 2023-06-19 16:08
Hi @MSyarifH, thank you for taking the time to file this issue!

Can you confirm that this is a problem only on Android? Your issue report also states a Windows version. Is this the computer that is compiling the application? Or are you also experiencing this issue on the Windows platform?

I see many people are experiencing this problem as well. Thanks to everyone weighing in on the situation, providing useful information such as version numbers and workarounds.

Could someone provide a minimal code example that showcases the issue? This would make tracking down the root cause of the bug easier. You can quickly create a minimal code example by creating a new flutter project and tweaking `main.dart`. Sending the contents of `main.dart`, or linking a repo, would help tremendously.

**Comment by DmitriySimonov** [comment] 2023-06-29 11:20
It turned out that the problem was in the safe_device library: ^1.1.4

If you remove the safe_device: ^1.1.4 library, then everything works fine.

These libraries work well!
   geolocator: ^9.0.2
   background_locator_2: ^2.0.6

Flutter 3.10.5
Dart 3.0.5 • DevTools 2.23.1

You can close the issue.

**Comment by anthonyhunter** [comment] 2023-07-01 20:01
> It turned out that the problem was in the library safe_device: ^1.1.4
> 
> If you remove the safe_device: ^1.1.4 library, then everything works fine.
> 
> These libraries work well!
> 
> ```
>    geolocator: ^9.0.2
>    background_locator_2: ^2.0.6
> ```
> 
> _Flutter 3.10.5 Dart 3.0.5 • DevTools 2.23.1_

Good find.
Seems `safe_device` dependency `trust_location` may be the issue. It provides location mocking detection (Android only), and can easily be removed while leaving core functionality of package.

**Closed** 2023-07-03 16:11 UTC
Labels: status: needs more info, platform: android

**Comment by crataristo4** [comment] 2023-08-28 06:32
This issues occurs on both android and iOS ... It feels like a deadly threat . The app hungs and throws no error ... First black screen appears before the native splash . In other cases my UI freezes for other pages

**Comment by Anik-Chakraborty** [comment] 2024-02-26 18:47
Getting similar kind of problem that @crataristo4 mentioned...
I have raise a problem in stackoverflow : https://stackoverflow.com/questions/78059346/flutter-app-not-running-screens-with-third-party-dependencies-no-error-message?noredirect=1#comment137616429_78059346
None of my projects are running.

**Comment by DennisKragekjaer** [comment] 2024-04-18 17:57
Same issue here actually. 1-2 sec freeze on iOS

**Comment by miladjalalli** [comment] 2024-10-08 16:06
I was remove **safe-device** from my project and then everything works fine (because **safe-device** use **location service** for check mock location)!
