### ISSUE TITLE
Approximate location not working

### ISSUE THREAD

**Issue by vineetpandit90** [Baseflow/flutter-geolocator#965] opened 2022-01-31 12:48 UTC
Plugin return nothing when user allow only approximate location while request to location permission in android 12.
Pls provide solution on early basis.

**Comment by mvanbeusekom** [comment] 2022-01-31 14:39
In general when only allowing approximate location permissions the Android sub system switches to using the `ACCESS_COARSE_PERMISSION` which means that the usage of WiFi and/or Bluetooth service are not available to assist with determining you location. This usually results in slow response time and sometimes no results when a connection to GPS satellites cannot be established (this happens mostly indoors or on places without a clear visibility to the sky). 

So first thing you should try is:
1. When testing on a real device, make sure to go somewhere where the device has clear visibility to the sky;
2. Don't give up too quickly, connecting to the GPS satellites can take up to 60 seconds.

If after 60 seconds with clear visibility to the sky you still don't receive any location updates something else might be wrong. To help out in this case we need more information, please supply us with the following:

1. The output of the `flutter doctor -v` command?
2. The contents of the `android/app/src/main/AndroidManifest.xml` file (**IMPORTANT**: remove or replace sensitive information)?
3. The contents of the `android/app/build.gradle` file (**IMPORTANT**: remove or replace sensitive information)?
3. The version of the plugin you are using?
4. Clear steps we can use to reproduce the issue (preferably accompanied with sample code)?

**Comment by vineetpandit90** [comment] 2022-02-01 04:35
1. flutter doctor -v
  [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/vineetsharma/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/vineetsharma/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!


I have declared both file and course location.

   <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

In case of allow precise location , it is working fine but  in case of approximate location it is not going after that line code.
   Position position = await Geolocator.getCurrentPosition();

**Comment by vineetpandit90** [comment] 2022-02-03 10:37
I tried this code in android 12, in case of approximate location allow.
Position accuratePosition = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

But this return nothing, got stuck on this line,

**Comment by l-qd** [comment] 2022-02-06 15:15
Faced the same problem here. Tried to get the location on both virtual and physical devices with both CourseLocation and FineLocation but with no luck. The app gets stuck on the getCurrentPosition method and does not return anything.

**Comment by NaplesDave** [comment] 2022-02-06 22:01
I'm using Android Studio 2021.1.1.21 Patch 1 on A MACBOOK Pro Intel i9, Monterey 12.1, Flutter, Geolocator 8.1. I followed the instructions in the docs and modified both my Android and my iOS files. iOS in Simulator for iPhone 8 works and returns coord. But the ANDROID Simulator , Pixel 4 API 32, returns these weird console messages.
******
Performing hot restart...
Syncing files to device sdk gphone64 x86 64...
Restarted application in 1,215ms.
D/EGL_emulation( 9232): app_time_stats: avg=4254797.50ms min=4254797.50ms max=4254797.50ms count=1
D/EGL_emulation( 9232): app_time_stats: avg=4744.64ms min=268.24ms max=9221.04ms count=2
D/EGL_emulation( 9232): app_time_stats: avg=4299185.00ms min=4299185.00ms max=4299185.00ms count=1

And Never errors or returns any coords.?

Here is the Dart Code;

import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class LoadingScreen extends StatefulWidget {
  @override
  _LoadingScreenState createState() => _LoadingScreenState();
}

class _LoadingScreenState extends State<LoadingScreen> {
  Future getLocation() async {
    LocationPermission permission = await Geolocator.requestPermission();
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.low);
    print(position);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            //Get the current location
            getLocation();
          },
          child: Text('Get Location'),
        ),
      ),
    );
  }
}

**Comment by l-qd** [comment] 2022-02-06 22:06
I found a workaround for this problem. It seems like the Android emulator finds difficulty fetching the location specified in the settings. I was able to circumvent that by opening Google maps (which allowed AVD to collect the location) and going back to the application. This way, I was able to get the location. Nonetheless, this is a tedious way and a better solution or fix should be implemented.

**Comment by NaplesDave** [comment] 2022-02-06 22:20
Thank You for the tip. I just tried that. I opened MAPS on the Android Simulator device (Pixel 4 API 32) , set the location by searching for my address. No issues. I Re-Launched my app and got no coords back, only these messages;

Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:64085/lBfvlwoy868=/ws
Syncing files to device sdk gphone64 x86 64...
D/EGL_emulation(10593): app_time_stats: avg=7488.00ms min=8.04ms max=14967.96ms count=2
D/EGL_emulation(10593): app_time_stats: avg=332.65ms min=7.17ms max=2623.10ms count=9
D/EGL_emulation(10593): app_time_stats: avg=9198.46ms min=3193.83ms max=15203.09ms count=2

I agree that it seems to be a SIMULATOR issue to me. My iOS Simulator device (iPhone 8) works fine. So I believe the Flutter code is OK. I double checked my ANDROID Manifest file and gradleBuild file and all settings are there as instructed. This is frustrating. I was battling a CocoaPods error due to an Android Studio bug introduced in the BumbleBee original release. Now with 2021.1.1.21 Patch 1 that is fixed. Now I have Android Simulator issues in the new "fixed" version. The Device Manager doesn't open in the IDE any more either, only from the Welcome screen.  ?? more bugs in the new release it seems.
________________________________

**Comment by NaplesDave** [comment] 2022-02-06 22:41
Just tried another tip; I set the Manifest file to..

"uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"

And updated my dart file to;

Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);

Now I get coord info like this;

Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:65189/odn-WC1wQyU=/ws
Syncing files to device sdk gphone64 x86 64...
D/EGL_emulation(11120): app_time_stats: avg=8707.57ms min=6.33ms max=17408.81ms count=2
D/EGL_emulation(11120): app_time_stats: avg=549.93ms min=11.60ms max=4717.76ms count=9
D/EGL_emulation(11120): app_time_stats: avg=2301.94ms min=2301.94ms max=2301.94ms count=1
D/EGL_emulation(11120): app_time_stats: avg=12510.79ms min=2815.64ms max=22205.93ms count=2
I/flutter (11120): Latitude: 37.4219983, Longitude: -122.084
I/flutter (11120): Latitude: 37.4219983, Longitude: -122.084
D/EGL_emulation(11120): app_time_stats: avg=107.30ms min=5.01ms max=1897.83ms count=21
D/EGL_emulation(11120): app_time_stats: avg=2228.00ms min=2228.00ms max=2228.00ms count=1
I/flutter (11120): Latitude: 37.4219983, Longitude: -122.084
D/EGL_emulation(11120): app_time_stats: avg=555.70ms min=7.31ms max=12404.54ms count=23
D/EGL_emulation(11120): app_time_stats: avg=12809.78ms min=12809.78ms max=12809.78ms count=1
I/flutter (11120): Latitude: 37.4219983, Longitude: -122.084
Application finished.


*Dave
________________________________

**Comment by mvanbeusekom** [comment] 2022-02-07 11:40
@vineetpandit90, I have been testing a lot this morning using the [example App](https://github.com/Baseflow/flutter-geolocator/tree/master/geolocator_android/example) and cannot reproduce this issue. On my emulator (I don't have access to a real device running Android 12) I receive a location almost immediately. 

The simulator I used:
- Pixel XL API 31 (Android 12 Preview x86_64, API 31 revision 8)

The `AndroidManifest.xml` file contains both permissions (see also [GitHub](https://github.com/Baseflow/flutter-geolocator/tree/master/geolocator_android/example) repo):
```xml
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

I haven't modified any of the default settings regarding the emulator location settings.

Feel free to have a look at the Dart code on the earlier mentioned GitHub repo.

Besides the above I also did an extensive review of the [JAVA code](https://github.com/Baseflow/flutter-geolocator/blob/726f928ac7662f417c69bb1958e4456afd173929/geolocator_android/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java) and I cannot discover any strange code. Also here, please feel free to have a look if I missed something.

I will close this issue now as I am unable to locate any mistakes and unable to reproduce the issue. Please leave a comment if there are findings.

**Closed by mvanbeusekom** 2022-02-07 11:40 UTC
Labels: platform: android

**Comment by vineetpandit90** [comment] 2022-02-09 05:51
I don't know how but it's working with invalidate cache in android studio, but still failing in 10% cases so i add a timeout.
in timeout i use hardcoded lat long.
