### ISSUE TITLE
Activity has leaked ServiceConnection that was originally bound here

### ISSUE THREAD

**Issue by Tom3652** [Baseflow/flutter-geolocator#1000] opened 2022-03-04 16:14 UTC
## 🐛 Bug Report

I have the following log on Android (sometimes) when the app goes in background and is killed by the OS : 

```
E/ActivityThread(20534): Activity com.myappname.android.MainActivity has leaked ServiceConnection com.baseflow.geolocator.GeolocatorPlugin$1@c8ea86 that was originally bound here
E/ActivityThread(20534): android.app.ServiceConnectionLeaked: Activity com.myappname.android.MainActivity has leaked ServiceConnection com.baseflow.geolocator.GeolocatorPlugin$1@c8ea86 that was originally bound here
E/ActivityThread(20534): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1836)
E/ActivityThread(20534): 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1708)
E/ActivityThread(20534): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1687)
E/ActivityThread(20534): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1834)
E/ActivityThread(20534): 	at android.app.ContextImpl.bindService(ContextImpl.java:1764)
E/ActivityThread(20534): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
E/ActivityThread(20534): 	at com.baseflow.geolocator.GeolocatorPlugin.onAttachedToActivity(GeolocatorPlugin.java:126)
E/ActivityThread(20534): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:155)
E/ActivityThread(20534): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:144)
E/ActivityThread(20534): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(20534): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/ActivityThread(20534): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009)
E/ActivityThread(20534): 	at com.fakedreameen.android.MainActivity.configureFlutterEngine(MainActivity.kt:29)
E/ActivityThread(20534): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
E/ActivityThread(20534): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/ActivityThread(20534): 	at android.app.Activity.performCreate(Activity.java:8077)
E/ActivityThread(20534): 	at android.app.Activity.performCreate(Activity.java:8061)
E/ActivityThread(20534): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/ActivityThread(20534): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3464)
E/ActivityThread(20534): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3659)
E/ActivityThread(20534): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/ActivityThread(20534): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/ActivityThread(20534): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/ActivityThread(20534): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2115)
E/ActivityThread(20534): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/ActivityThread(20534): 	at android.os.Looper.loop(Looper.java:250)
E/ActivityThread(20534): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
E/ActivityThread(20534): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(20534): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/ActivityThread(20534): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Expected behavior

The main activity should not leak.

### Reproduction steps

Hard to tell unfortunately, but as i said, when the app went in background and was killed by the OS i got this log.

### Configuration

**Version:** : 8.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-03-04 16:36
Duplicate of #986, closing this issue and track progress in #986.

**Closed** 2022-03-04 16:36 UTC
