### ISSUE TITLE
[BUG] [EXCEPTION] timeLimit leads to the 'Time limit reached while waiting for position update' exception.

### ISSUE THREAD

**Issue by zs-dima** [Baseflow/flutter-geolocator#1177] opened 2022-11-30 08:30 UTC
timeLimit leads to the 'Time limit reached while waiting for position update' exception:

```
Top-level error: TimeoutException after 0:00:05.000000: Time limit reached while waiting for position update.
I/flutter ( 6353): Stack trace:
E/FlutterGeolocator( 6353): Geolocator position updates stopped
E/FlutterGeolocator( 6353): There is still another flutter engine connected, not stopping location service
```

```dart
final locationSettings = LocationSettings(timeLimit: Duration(seconds: 5));
Geolocator.getPositionStream(
              locationSettings: locationSettings,
            ).listen((position) {...});
```

In case when timeLimit is not set geolocator working well.

It is not difference if 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
or
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
set for the AndroidManifest.xml.

**Version:** 9.0.2, 8+, 7+

**Platform:** 
Android v12+
- [v] :robot: Android emulator
- [v] :robot: Android device

**Comment by BinniZenobioCordovaLeandro** [comment] 2022-12-04 06:22
Same here

```log
I/flutter ( 5653): value: -12.1006488
D/EGL_emulation( 5653): app_time_stats: avg=2997.71ms min=17.60ms max=5977.83ms count=2
I/flutter ( 5653): ERROR STREAM POSITION!
E/FlutterGeolocator( 5653): Geolocator position updates stopped
D/FlutterGeolocator( 5653): Stopping location service.
```

**Comment by mvanbeusekom** [comment] 2023-07-27 12:18
Hi @zs-dima, @BinniZenobioCordovaLeandro,

The `timeLimit` parameter can be used to cancel the location stream if no updates arrive within the time specified. This indeed results in the `TimeoutException` allowing developers a change to handle gracefully.

The parameter is working as intended, therefore I will close this issue.

**Closed by mvanbeusekom** 2023-07-27 12:18 UTC
