### ISSUE TITLE
Get location in background mode

### ISSUE THREAD

**Issue by somaria** [Baseflow/flutter-geolocator#389] opened 2020-02-09 21:09 UTC
## 💬 Questions and Help

Hi, 

I am looking for some sample code or guide on how to implement getting current location when App is running in the background mode.  

Any help or guide would be greatly appreciated.

**Comment by AbrahamCardenes** [comment] 2020-02-11 11:54
I would love to know also if this is possible or not, because currently i'm trying to get the Position of the user even if the app is en background mode or closed.

**Comment by AbrahamCardenes** [comment] 2020-02-12 11:19
Soo, im trying to do it wich the alarm manager plugin so every X time execute a method with  Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
And... it works partially like i feel like sometimes it's only returning the same value, but it is a starting point i guess.

void printHello() async {
  print("Hello - " + DateTime.now().toString());
  Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
  print("Altitude: ${position.altitude}, Longitude: ${position.longitude}, Latitude: ${position.latitude}"  );
}

void main() async {

  WidgetsFlutterBinding.ensureInitialized();

  await AndroidAlarmManager.initialize();

  runApp(MyApp());
  await AndroidAlarmManager.periodic(const Duration(seconds: 1), 0, printHello);
}

Hope it helps a little

**Comment by somaria** [comment] 2020-02-12 13:36
The other day I was looking at this package [background fetch](https://pub.dev/packages/background_fetch) and I believe this would allow us to get the current location.

I have not tried it yet.

https://pub.dev/packages/background_fetch

**Comment by aaulia** [comment] 2020-02-16 04:12
> The other day I was looking at this package [background fetch](https://pub.dev/packages/background_fetch) and I believe this would allow us to get the current location.
> 
> I have not tried it yet.
> 
> https://pub.dev/packages/background_fetch

I have, unfortunately I have some problem with querying current location from headless background task (periodic task that trigger itself when the application is already being terminated).

It works if the application is on foreground or background, but if the app is terminated (or not yet started, in case the task is started on boot for example), then `getCurrentLocation` would just freeze.

I suspect this is because the the plugin doesn't play well with background_fetch headless mode. I'm still looking at this right now.

**Comment by aaulia** [comment] 2020-02-17 01:15
Okay, so the problem is, I should've test on real device, and not on emulator. So yes it's doable to combine background_fetch with this plugin. Cheers

**Comment by estevez-dev** [comment] 2020-02-17 19:00
Take a look on [workmanager](https://pub.dev/packages/workmanager) if you want to get more control over you background tasks. Also it is very stable.

**Comment by AbrahamCardenes** [comment] 2020-02-18 10:55
So finally what i did for android was a service (native code) wich runs all the time once is activated, i started this service thanks to the MethodChannel in flutter.
No alarm manager needed or workmanager.

**Comment by estevez-dev** [comment] 2020-02-18 11:28
Your service will be finished by OS in terms of battery saving. This is how newer versions of Android works. It can run for an hour, or even a day, but it will be terminated anyway. Also it will not be started after phone reboot. That is why you need Workmanager.

**Comment by cormalenv** [comment] 2020-02-19 05:30
> Your service will be finished by OS in terms of battery saving. This is how newer versions of Android works. It can run for an hour, or even a day, but it will be terminated anyway. Also it will not be started after phone reboot. That is why you need Workmanager.

It shouldn't be terminated if you create a foreground service for API 26+ though right? (In background mode that is, not for headless).  We use this option in native, listening to location updates. We are not chasing headless per se but in line with @somaria we are asking how to listen in the **background** (across both iOS and Android)?

**Comment by osamabinishrat** [comment] 2020-02-22 06:53
Found a solution for flutter android:

https://github.com/sriharsha1507/flutter_pet_tracking_android

**Comment by mvanbeusekom** [comment] 2020-05-08 11:56
duplicate of #53

**Closed by mvanbeusekom** 2020-05-08 11:56 UTC
