### ISSUE TITLE
Geolocator gives different coordinates at the same location

### ISSUE THREAD

**Issue by bossou7** [Baseflow/flutter-geolocator#614] opened 2020-11-30 17:25 UTC
Geolocator gives different coordinates at the same location

_Originally posted by @bossou7 in https://github.com/Baseflow/flutter-geolocator/issues/613#issuecomment-735926890_

**Comment by mvanbeusekom** [comment] 2020-12-01 08:08
duplicate of #596

**Closed by mvanbeusekom** 2020-12-01 08:08 UTC
Labels: type: duplicate
