### ISSUE TITLE
i cant run Geolocator.getCurrentPosition() in background

### ISSUE THREAD

**Issue by rulefahd** [Baseflow/flutter-geolocator#1045] opened 2022-04-28 16:09 UTC
when i try to getCurrentPosition while application in background or terminated , it returns 

' MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)'

**Comment by ysur67** [comment] 2022-05-02 15:09
Facing the same issue. Have you found any solution for it?

**Comment by AvidanGC** [comment] 2022-05-12 01:45
Facing the same issue. Have you found any solution for it?

**Comment by mvanbeusekom** [comment] 2022-05-13 09:50
Duplicate of issue #1041, please have a look at this [comment](https://github.com/Baseflow/flutter-geolocator/issues/1041#issuecomment-1125862107) for the fix.

**Closed by mvanbeusekom** 2022-05-13 09:50 UTC

**Comment by ubitechparth** [comment] 2022-06-20 13:09
Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
I am using geolocator package but this type of error coming when app is installed in android device how to solve it
