### ISSUE TITLE
Update Permission Allow Once, While Using the Apps, and Deny

### ISSUE THREAD

**Issue by sed1ka** [Baseflow/flutter-geolocator#1032] opened 2022-04-12 08:05 UTC
## Bug Report

Currently, location permissions have three different options than before.

The Past: Allow, Deny, and Deny Forever
Now: Allow Once (Ask Next Time Or When I Share / Only This Time), While Using The App, and Deny

If the user selects "Allow Once", the `checkPermission()` function will return `permission == LocationPermission.denied`
and can be handled with `requestPermission()` . function
And if user select "Deny", function `checkPermission()` will also return`permission == LocationPermission.denied` but `requestPermission()` does not work and does not display permission dialog
So since checkPermission is only 'denied' not 'deniedForever'. I can't handle it by using `openAppSetings()` or `openLocationSetting()` options.

So I think "Deny" for now (this time) means "Deny Forever"

### Expected behavior
Able to call `requestPermission()`, `openAppSetings()` or `openLocationSetting()` if user choose Deny.

### Reproduction steps
1. Select Deny when the app asks for permission
2. requestPermission() will not run / or no permission dialog appears

**Version: when:**
iOS 15.4
Android 11

**Platforms:**
both iPhone and Android

**Comment by mvanbeusekom** [comment] 2022-04-12 08:48
Hi @sed1ka, 

When you deny permissions on iOS they immediately result in the `PermissionStatus.deniedForever` status, the `checkPermission()` method will also return this value in subsequent checks.

However Android unfortunately doesn't support this. The native Android API only returns a `DENIED` or `GRANTED` status when checking permissions and doesn't allow us to make a distinction between "denied but you can try again" and "denied and don't ask again". Using a workaround it is possible to return this state directly after requesting permissions and therefore we recommend to handle permissions in the following manor:

```dart
bool serviceEnabled;
LocationPermission permission;

// Test if location services are enabled.
serviceEnabled = await Geolocator.isLocationServiceEnabled();
if (!serviceEnabled) {
  // Location services are not enabled don't continue
  // accessing the position and request users of the 
  // App to enable the location services.
  return;
}

permission = await Geolocator.checkPermission();
if (permission == LocationPermission.denied) {
  permission = await Geolocator.requestPermission();
  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately. 
    return;
  } 

  if (permission == LocationPermission.denied) {
    // Permissions are denied, next time you could try
    // requesting permissions again (this is also where
    // Android's shouldShowRequestPermissionRationale 
    // returned true. According to Android guidelines
    // your App should show an explanatory UI now.
    return;
  }
} else if (permission == LocationPermission.deniedForever) {
  // Permissions are denied forever, handle appropriately. 
  return;
}

// When we reach here, permissions are granted and we can
// continue accessing the position of the device.
_position = await Geolocator.getCurrentPosition();
```
More background information can be found in the [Breaking changes in 7.0.0](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0) article on our Wiki page.

I will go ahead and close this issue as the permissions are working as intended. If you have further questions however don't hesitate to leave a comment.

**Closed as completed by mvanbeusekom** 2022-04-12 08:48 UTC
