### ISSUE TITLE
[Bug] Geolocator.getCurrentPosition() not returning location sometimes

### ISSUE THREAD

**Issue by chirag-chopra** [Baseflow/flutter-geolocator#1193] opened 2023-01-10 13:41 UTC
## 🐛 Bug Report
Sometimes, `Geolocator.getCurrentPosition()` returns location and sometimes not. Even though I tried to add null check but I am getting warning. 

### Expected behavior
Either it should not be null at any cost or there must be a way to check if function returned null or not.  How to handle if locations are not fetched. How to perform null check?

### Reproduction steps
 ```dart
final curLoc = await Geolocator.getCurrentPosition();
      if (curLoc != null ) {
        // perform further stuff
      }else{
    print("Unable to fetch location");
     }
```

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by yeminsoe** [comment] 2023-01-13 08:16
I also faced this issues. Do i need to setup Geocoding API KEY ?

**Comment by rs-linhlc** [comment] 2023-01-18 02:05
I just commented on a similar issue. Maybe you can check it out if it work for you?
https://github.com/Baseflow/flutter-geolocator/issues/1191#issuecomment-1386359620

**Comment by ManInTheWind** [comment] 2023-02-08 14:45
I face it too, even though I have added timeLimit ,  it will just timeout but never return position from native

**Comment by rs-linhlc** [comment] 2023-02-09 02:20
> I face it too, even though I have added timeLimit , it will just timeout but never return position from native

You can use getLastKnownPosition if TimeOutException was thrown.

**Comment by SriRam-Macha** [comment] 2023-02-23 18:52
For me this is occurring only on the IOS build.
I don't how but calling the same function twice fixed the issue for me in the IOS build
For ex - 
`log(await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.best).toString());
    Position pos = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.best);`

**Comment by Prajwal238** [comment] 2023-02-23 18:58
Had the same issue. Works fine on android but while running on iOS getCurrentPosition() doesn't return anything.

**Comment by edwin-alvarez** [comment] 2023-03-11 17:29
get same problem, this occurred after migrating to latest

**Comment by 0wzZZzz6** [comment] 2023-03-28 04:25
I had this problem too. any fix?

**Comment by micaiah-effiong** [comment] 2023-05-08 11:14
In my case, I had to use `Geolocator.getLastKnownPosition()` instead

**Comment by JeroenWeener** [comment] 2023-06-19 09:39
Hi @chirag-chopra and other people that provided helpful comments, thank you for taking the time to open and discuss this issue!

Extra information helps to speed up investigation into issues. A minimal code example would be ideal. You can create one by creating a new flutter project, editing `main.dart` so it showcases your issue, and adding the contents of `main.dart` in a comment here. It is also interesting to find out under what circumstances you are experiencing this problem exactly. I see OP has not set up iOS development, so I am assuming that you are using Android. Other commenters have mentioned iOS having the problem, instead of Android. I would like to confirm whether this issue exists on both platforms, or whether there are two separate issues that occur on any one platform. Also, are you running your application on an emulator or on a physical device?

Looking forward to hearing from you!

**Comment by matheszabi** [comment] 2023-06-19 23:14
My project started 2-3 months ago or so.
Justr came back to develop and update something. 
One of the libraries asked for Android 19 min version. I gave it.
After that I see I don't get the location.
Now I am testing with Android 13 phone, with permissions given ( and no code change)
Here is where the code is waiting:
<img width="1637" alt="Screenshot 2023-06-20 at 02 10 20" src="https://github.com/Baseflow/flutter-geolocator/assets/506560/d555b1d1-fe1d-4a2d-997b-118afea2948c">

For me this is not really acceptable: one of the basic functionality of the app is broken by a library.
So better get out from Flutyter and go native, because the development price it is less than debugging libraries!!!

**Comment by JeroenWeener** [comment] 2023-06-20 08:41
Possible duplicate of #731, #949, #1114

**Closed** 2023-07-03 10:11 UTC
Labels: status: needs more info

**Comment by ErickLlerenas** [comment] 2024-03-17 20:25
> getLastKnownPosition

Yes, this is the answer since apple doesn't want us to getCurrentPosition twice
