### ISSUE TITLE
getCurrentPosition never returns a value

### ISSUE THREAD

**Issue by ryanlangton** [Baseflow/flutter-geolocator#642] opened 2021-01-14 14:20 UTC
## 🐛 Bug Report

Calling the method getCurrentPosition never returns data, it goes past this line of code and never hits the next line. This is wrapped in a try/catch and an exception is never thrown either. Running on Android emulator. Pixel API 28

I've tried this on emulators targeting v28 and v29 android. The behavior is the same. I do get a popup asking if I want to allow the application to access the devices location which I confirm. I have also "set location" in the extended controls for the emulator.

### Expected behavior

Return a location (lat/long)

### Reproduction steps

Add this line of code, use an android emulator.
final position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best, forceAndroidLocationManager: true);

### Configuration

geolocator: ^6.1.13

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-01-14 16:37
Duplicate of #641

**Closed by mvanbeusekom** 2021-01-14 16:37 UTC
