### ISSUE TITLE
Dart sdk error in html_permissions_manager

### ISSUE THREAD

**Issue by Bylinkk** [Baseflow/flutter-geolocator#1263] opened 2023-06-01 07:04 UTC
## 🐛 Bug Report

Dart error occurs while checking html permission.

I use the location_picker_flutter_map dependencies which uses flutter-geolocator. I use dependencies with Flutter web. When the location permission is activated it works correctly however when I deactivate the browser permission, the FlutterLocationPicker class gives me the error "Location Permission is denied forever" but the script stops in the HtmlPermissionsManager class

When I continue to run the code I get the following errors:

ChromeProxyService: Failed to evaluate expression 'permissionsSupported': InternalError: Expression evaluation in async frames is not supported. No frame with index 17..
ChromeProxyService: Failed to evaluate expression ''permissions_manager': InternalError: Expression evaluation in async frames is not supported. No frame with index 17..
Error: Location Permission is denied forever
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 321:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>

Use Flutter web with location_picker_flutter_map dependencies and location Permission deactivated on the browser

[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64)
    • Flutter version 3.10.1 on channel stable 
    • Framework revision d3d8effc68 (il y a 2 semaines), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

Can you help me to solve this problem please? thanks in advance.

**Comment by JeroenWeener** [comment] 2023-06-19 15:42
Hi @Bylinkk, thank you for taking the time to file this issue and include the error trace and versions of relevant tools!

To effectively dive into this issue, a minimal code example works wonders. Especially in this case, as the error can originate from `flutter-geolocator`, but also from `location_picker_flutter_map`. You can create a minimal setup easily by creating a new flutter project and tweaking `main.dart` to achieve the behavior you require. Then, you can send the contents of `main.dart` here so others can reproduce and look into the issue.

**Comment by Bylinkk** [comment] 2023-06-27 08:51
Hi @JeroenWeener, 
thanks for taking the time to respond. Here is a sample code with only the location_picker_flutter_map dependency. trackMyPosition is enabled and the error appears immediately when location access has been denied in chrome.

```
import 'package:flutter/material.dart';
import 'package:location_picker_flutter_map/location_picker_flutter_map.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Location Picker',
      home: OpenStreetMapView(),
    );
  }
}

class OpenStreetMapView extends StatelessWidget {
  const OpenStreetMapView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    String errorMessage = "";
    return MaterialApp(
      title: 'Choose adress',
      debugShowCheckedModeBanner: true,
      home: Scaffold(
        body: FlutterLocationPicker(
            initZoom: 15,
            minZoomLevel: 5,
            maxZoomLevel: 16,
            trackMyPosition: true,
            searchBarBackgroundColor: Colors.white,
            selectLocationButtonText: "Confirm",
            searchBarHintText: "Search",
            mapLanguage: 'en',
            onError: (e) {
              switch (e.toString()) {
                case "Location Permission is denied":
                  errorMessage = "Location Permission is denied";
                  break;
                case "Location Permission is denied forever":
                  errorMessage =
                      "Location Permission is denied forever";
                  break;
                default:
                  errorMessage = e.toString();
              }
              errorMessage.isNotEmpty
                  ? ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      behavior: SnackBarBehavior.floating,
                      content: Text(errorMessage)))
                  : null;
            },
            onPicked: (pickedData) async {
              print(pickedData.address);
            }),
      ),
    );
  }
}
```

Can someone help me ? Thanks in advance

**Comment by JeroenWeener** [comment] 2023-06-27 09:41
Hi @Bylinkk, reading your comments, it appears that your issues are not caused by `geolocator`. I am therefore going to close this issue.

Nevertheless, I could offer you some help with your issue regarding `ScaffoldMessenger`. Could you provide me with the error you are getting? `ScaffoldMessenger` seems like a good fit for your use case. Also, is there a reason for declaring `errorMessage` at the start of the build function, instead of in `onError`?

**Closed by JeroenWeener** 2023-06-27 09:41 UTC
Labels: platform: web

**Comment by Bylinkk** [comment] 2023-06-27 10:04
Thanks you for you quick come back ! 
The script stops in the following function: final html.PermissionStatus status = await _permissions!.query(
      _permissionQuery,
    ); of the HtmlPermissionsManager class

yes, I could declare the variable errorMessage in the onError!

**Comment by JeroenWeener** [comment] 2023-06-27 15:07
Hi @Bylinkk,

Unfortunately, without more code, I cannot offer much assistance. It seems that `query()` does not return, but that is all I can tell from the code snippet you provided.

**Comment by Bylinkk** [comment] 2023-07-04 23:28
Hi @JeroenWeener, thanks for your help, 

To avoid spending too much time on it, I worked around the problem by adding the message under the card and not in a ScaffoldMessenger like this

```
if (errorMessage != '')
              Container(
                color: Colors.red,
                padding: const EdgeInsets.all(8),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Icon(Icons.warning, color: Colors.white, size: 16),
                    const SizedBox(width: 8),
                    Text(
                      errorMessage,
                      style: const TextStyle(color: Colors.white),
                    ),
                  ],
                ),
              ),
```

I'll leave it like that for now. Thanks again for your help and support.
