### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by Saikiran24** [Baseflow/flutter-geolocator#1043] opened 2022-04-26 08:51 UTC
Getting this issue when running on Android

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

**Comment by mvanbeusekom** [comment] 2022-04-26 09:05
Duplicate of issues #745 and #930, please have a look there. This error is usually an issue with the development environment or pub.dev cache.

**Closed by mvanbeusekom** 2022-04-26 09:05 UTC
