### ISSUE TITLE
[!] No podspec found for `geolocator_web` in `.symlinks/plugins/geolocator_web/ios`

### ISSUE THREAD

**Issue by ObasiGodstime** [Baseflow/flutter-geolocator#696] opened 2021-03-29 05:17 UTC
### -> Fetching podspec for `firebase_auth_web` from `.symlinks/plugins/firebase_auth_web/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
    -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
    -> Fetching podspec for `flutter_geofire` from `.symlinks/plugins/flutter_geofire/ios`
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_native_image` from `.symlinks/plugins/flutter_native_image/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_share` from `.symlinks/plugins/flutter_share/ios`
    -> Fetching podspec for `flutter_statusbarcolor` from `.symlinks/plugins/flutter_statusbarcolor/ios`
    -> Fetching podspec for `flutter_vibrate` from `.symlinks/plugins/flutter_vibrate/ios`
    -> Fetching podspec for `geolocator` from `.symlinks/plugins/geolocator/ios`
    -> Fetching podspec for `geolocator_web` from `.symlinks/plugins/geolocator_web/ios`
    [!] No podspec found for `geolocator_web` in `.symlinks/plugins/geolocator_web/ios`

### [✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-NG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter-specific functionality.
    ✗ Dart plugin not installed; this adds Dart-specific functionality.
[✓] VS Code (version 1.54.3)
[✓] Connected device (1 available)

**Version:** 6.2.0

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment] 2021-03-29 06:41
Hi @ObasiGodstime, this seems to be a duplicate of issue #659. 

Please try the following steps to fix the issue:

1. Delete `Podfile` and `Podfile.lock` from `ios` folder;
2. Run `flutter clean` in the root folder of your project;
3. Change back into the `ios` folder and run `pod install`;
4. All should be good and you should be able to run you App.

**Closed by mvanbeusekom** 2021-03-29 06:41 UTC
