### ISSUE TITLE
[Regression]: There is crash when running building command. 

### ISSUE THREAD

**Issue by Talk8** [Baseflow/flutter-geolocator#1407] opened 2024-01-13 02:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [X] Windows

### Old behavior

there is a crash,we can not build apk normally.

### Current behavior

there is not any crash,we can build apk normally.

### Steps to reproduce

1. add the geolocator package into pubspec.yaml file.   geolocator: ^9.0.2
2. runnig 'pub get' get package.and it is running ok.
3. runing build command at AndroudStudio IDE, it is in menu of IDE,'Build -> flutter ->  build apk'.
4. IED report a crash. it is as following:

 flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.dev\geolocator_android-4.4.0\android\src\main\java\com\baseflow\geolocator\GeolocatorPlugin.java'".

5. we try the the version : geolocator: ^8.1.0, it runnig ok in the same PC,  So we thinks that ,this carsh is caused at 9.0.2 version. because we using the same PC, and don't change any config of PC. we try the latest version: '  geolocator: ^10.1.0', thre is the same crash too.
7. we developped Android App at Windows PC, it is a building issuer.

 we add the crash log,it is named 'flutter_08.log' it is usfull for you.

Thans a lot.
[flutter_08.log](https://github.com/Baseflow/flutter-geolocator/files/13926039/flutter_08.log)

### Code sample

<details><summary>Code sample</summary>

```dart
it is build error, so there is not any code.
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Current version

9.0.2

### Last version without regression

10.1.0

**Comment by mvanbeusekom** [comment] 2024-01-30 09:56
Hi @Talk8,

I have tried to reproduce this issue by creating a new Flutter application on my Windows laptop and adding the geolocator dependency. After running `futter pub get` I ran `flutter build apk` which worked without any problems.

I did a little bit of research on the error mentioned and found the following:

- Some users where able to resolve the problem by running `flutter clean`.
- People also report deleting the `.flutter-plugins` folder from the project.
- People also report this exact issue is related to encryption software that is encrypting the file system. The workaround mentioned was to remove or disable the encryption software.

Since I cannot reproduce the issue on my environment I will go ahead and close this issue for now. Below is some more details on my system setup:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22000.2538], locale en-NL)
    • Flutter version 3.16.9 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 41456452f2 (5 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mvanb\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34309.116
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\mvanb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Closed by mvanbeusekom** 2024-01-30 09:56 UTC

**Comment by Talk8** [comment] 2024-03-16 05:44
@mvanbeusekom 
Hello

we solve this issue by` "flutter clean"`, we think that ,this issue was caused by cache of ` .flutter-plugins`

thanks for your reply.
