### ISSUE TITLE
Android X LocationAccuracy works only if set to HIGH or BEST

### ISSUE THREAD

**Issue by JoKeRxbLaCk** [Baseflow/flutter-geolocator#445] opened 2020-05-24 08:10 UTC
## 🐛 Bug Report

This line of code:

Position position = await Geolocator()
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

works only if the location accuracy is set to high or best in android X.

### Expected behavior
Should work with every LocationAccuracy setting.

### Reproduction steps
Try to execute that line of code with Android X project.

### Configuration

**Version:** 5.3.1

**Platform:** 
- [x] :robot: Android

**Comment by lim-enhui** [comment] 2020-05-24 12:45
yup. there is an issue with this

**Comment by mvanbeusekom** [comment] 2020-05-28 11:10
duplicate of #430

**Comment by mvanbeusekom** [comment] 2020-08-31 09:43
fixed in 6.0.0

**Closed by mvanbeusekom** 2020-08-31 09:43 UTC
Labels: type: duplicate
