### ISSUE TITLE
[Bug]: kCLErrorDomain error 1. on Background (BYPASS_PERMISSION_LOCATION_ALWAYS=1 not working) 

### ISSUE THREAD

**Issue by lexermekongnet** [Baseflow/flutter-geolocator#1468] opened 2024-03-20 02:10 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. Bypass on Podfile BYPASS_PERMISSION_LOCATION_ALWAYS=1' (I don't want to receive update on background)

### Expected results

No results on background

### Actual results

The operation couldn’t be completed. (kCLErrorDomain error 1.)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  void initState() {
    super.initState();
  }

  @override
  void didChangeDependencies() async {
    super.didChangeDependencies();

    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      return Future.error(
        'Location permissions are permanently denied, we cannot request permissions.',
      );
    }
    Geolocator.getPositionStream().listen((event) {
      debugPrint('$event');
    });
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold();
  }
}

```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]
![Screenshot 2024-03-20 at 9 07 48 in the morning](https://github.com/Baseflow/flutter-geolocator/assets/150870949/25c83ece-ca25-4bb5-a935-1e74ae54dd7e)

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en-KH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by mvanbeusekom** [comment] 2024-03-20 07:53
Hi @lexermekongnet,

It is really difficult for us to implement all the different use cases on how to handle the stream when the application moves into te background. 

Therefore we leave this up to the application developers. In this case it is your responsibility to unsubscribe from the stream when the application goes into the background and don't leave the stream dangling.

I will go ahead and close this issue as this is working as intended.

**Closed by mvanbeusekom** 2024-03-20 07:53 UTC
