### ISSUE TITLE
Location is more accurate when other apps are open

### ISSUE THREAD

**Issue by orriesquabbit** [Baseflow/flutter-geolocator#1274] opened 2023-06-11 21:54 UTC
## 🐛 Bug Report

For my app (a golf app that measures shot distances) I'm using `LocationAccuracy.best` however the accuracy seems to be around 20m accuracy and doesn't update that frequently (~every 5 seconds). 

However, when I open another golf app that also requests location permissions (e.g. The Grint), all of a sudden the location updates in my app are super accurate (within 1m) and update every second. 

As soon as I close the other app, the updates in my app go back to being ~20m accuracy and ~5s updates. 

How is it that other apps are able to request such high precision updates? 

Note that this is only on Android, on iOS it's very accurate even without other apps open. 

### Reproduction steps
1. Open an app on Android and request an location stream with LocationAccuracy.best.
2. Notice that updates are ~20m accuracy and jump around.
3. Open an app like The Grint and start GPS tracking. 
4. Go back to the original app while The Grint is still requesting updates in the background and notice that the location updates in the app are super accurate ~1m accuracy. 
5. Close The Grint app. 
6. Go back to the original app and notice that location updates are back to ~20m. 

### Configuration

This is the configuration for the Android location settings: 
```
locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.best,
          distanceFilter: 1,
          forceLocationManager: true,
          intervalDuration: const Duration(seconds: 1),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText: "Your location will continue to update.",
            notificationTitle: "Location updating in background",
            enableWakeLock: true,
          )
      );
```

Setting up the stream:
```
_positionStream = Geolocator.getPositionStream(locationSettings: locationSettings)
        .listen((Position? position) {
          print("Position updated: ${position?.latitude}, ${position?.longitude}");
          if (position != null) _myPosition = LatLng(position.latitude, position.longitude);
          else position = null;
          setState(() {});
        });
```

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by odiggity25** [comment] 2023-06-13 22:45
I tried another package and it is much more accurate https://pub.dev/packages/location

**Comment by TimHoogstrate** [comment] 2023-06-27 07:27
Dear @odiggity25,

If you set forceLocationManager to true you basically force the app to use the Legacy LocationManager for position updates.  This is based either on GSM network for coarse positioning) and GPS based (fine) location. However, if you are for example testing inside, it might be hard to find an accurate position. If you set forceLocationManager to false, the app basically uses network and GPS and it combines them. In addition it uses internet (based on ISP data) and WiFi (if supported by the router) positioning as well. Therefore, inside you might expect a more accurate position. Why TheGrind influences your app is that it basically works together, if one app has a "better" location, other apps might profit from it.

I'll close this issue since I suspect that this is expected behaviour. Feel free to reopen when needed.

**Closed by TimHoogstrate** 2023-06-27 07:27 UTC

**Comment by orriesquabbit** [comment] 2023-07-30 19:58
@TimHoogstrate ohhh, gotcha. Sorry, I misread the documentation when I investigated this parameter. I only added this parameter because it is in the setup guide here https://pub.dev/packages/geolocator. I would suggest maybe removing it from the guide if it's not something most people should be using (I'm guessing most people want to use as many options as possible).

**Comment by Hariiikrishnan** [comment] 2023-12-09 03:59
@orriesquabbit bruh did you fixed it, if yes can you please tell me the settings config that you finalized?

**Comment by orriesquabbit** [comment] 2023-12-09 12:49
just remove `forceLocationManager: true,` from the settings. So: 

locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.best,
          distanceFilter: 1,
          intervalDuration: const Duration(seconds: 1),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText: "Your location will continue to update.",
            notificationTitle: "Location updating in background",
            enableWakeLock: true,
          )
      );

**Comment by Hariiikrishnan** [comment] 2023-12-09 14:15
Okay sure.. I'll try
