### ISSUE TITLE
getCurrentPosition takes too long on 7.6.2

### ISSUE THREAD

**Issue by digocse** [Baseflow/flutter-geolocator#839] opened 2021-09-18 22:36 UTC
## 🐛 Bug Report

Hi everyone!

I've been using `geolocator` for a while and I was about to upgrade the current version `^4.0.3` to `^7.6.2`.

Turns out that the method `getCurrentPosition` takes about 10 seconds to locate the user, while the old version returns almost immediately. I tried to upgrade to `^5.3.1` in the past but got the same behavior.

Does anyone knows a newer version that doesn't takes too long to locate the user?

### Expected behavior
Return user location faster. Just as it is in the older version.

### Reproduction steps
Call `getCurrentPosition` to take user location.

### Configuration

**Version:** ^7.6.2

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-09-20 06:52
Hi @digocse,

The issue is that we had a bug which resulted in the `getCurrentPosition` method to return the last known location. The benefit was that it made it return very fast, but of course the disadvantage is that is often returned a wrong location.

We have resolved the issue but unfortunately that means you will have to wait for iOS to make the necessary connections. This can take up to several seconds (especially the first time you call `getCurrentPosition`). There is unfortunately no way around this. 

I'd suggest you first call the `getCurrentPosition` method and while waiting for the satellite fix call the `getLastKnownPosition` method to get a fast location update.

More information can also be found in the [release notes](https://pub.dev/packages/geolocator/changelog#760). I will be closing this issue now as this isn't a bug we can resolve. If you have any follow up questions or feedback feel free to leave a comment.

**Closed by mvanbeusekom** 2021-09-20 06:52 UTC

**Comment by mvanbeusekom** [comment] 2021-10-04 15:49
Hello @SergiDevel, 
 
 As mentioned in the previous comment, this is unfortunately how Apple has implemented the solution. It takes up to 10 seconds because Apple's `requestLocation` method will fetch multiple location updates from the device, compare them to each other and returns the most accurate result (this procedure is very well explained in [this](https://fluffy.es/current-location/#retrieving) article).
 
 If you don't want to wait and don't need a high accuracy result, you could start listening to the `getPositionStream`, grep the first result and stop listening directly after. You can do this very easily using the `.first` property:
 
 ```dart
 // Fetch the first result from the position stream and cancel the stream directly after.
final Position position = await Geolocator.getPositionStream().first;
 ```
 
 Of course you can do more advanced logic if necessary.

**Comment by SergiDevel** [comment] 2021-10-04 19:10
Hello @mvanbeusekom, thanks for the fast answer. I tested the proposed solution requesting the first element but I got a few hundred meters difference for each request.
