### ISSUE TITLE
Flutter 2.0.0 Task geolocator:compileReleaseJavaWithJavac FAILED 

### ISSUE THREAD

**Issue by khandilist** [Baseflow/flutter-geolocator#682] opened 2021-03-06 12:20 UTC
## 🐛 Bug Report
Version 7.0.1 with flutter 2.0.0 can't compile android in **release mode**
Error message:
```
warning: [deprecation] onStatusChanged(String,int,Bundle) in LocationListener has been deprecated
  public void onStatusChanged(String provider, int status, Bundle extras) {
              ^
error: warnings found and -Werror specified
1 error
1 warning

warnings found and -Werror specified

```

### Configuration

**Version:** 7.0.1

**Platform:** 
- [v] Android

**Comment by mvanbeusekom** [comment] 2021-03-29 08:09
Hi @khandilist,

Apologies for the late reply. I have been looking into this issue but cannot really find the problem. We do indeed implement the `onStatusChanged(String,int,Bundle)` method for reasons of backwards compatibility. This method however is correctly decorated with the `@SuppressWarnings("deprecation")` attribute which should (and does in my test setup) prevent the build system from throwing the warning (see implementation [here](https://github.com/Baseflow/flutter-geolocator/blob/328fe15da0533f7b3c90caf22039731831997c5a/geolocator/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java#L135))

We also have configured the `-Werror` argument in our build strategy and the CI/CD system and locally the plugin compiles just fine. Just to make sure the build system is working correctly I removed the `@SuppressWarnings("deprecation")` attribute locally and build again which indeed resulted in the above compile error. 

Unfortunately this is all I can do, it seems you might have something locally that is conflicting. Some things you could check:

1. Do you use a forked implementation of the `geolocator`? 
2. Try cleaning your cache: `flutter clean`;
3. Make sure your dependencies are all up to date: `flutter pub upgrade`.

I will close this issue for now. If you have more information or you feel the issue is really on our side feel free to leave a message and I would be happy to re-open the issue.

**Closed by mvanbeusekom** 2021-03-29 08:09 UTC

**Comment by markizdeviler** [comment] 2021-09-29 12:50
I am also facing the same issue. When I upgraded `targetSdkVersion` to 31, error occured. But It's working fine in `targetSdkVersion` 30. 
Any solutions?

### Configuration

_Version_: 7.6.2

_Platform_: [v] Android

**Comment by mvanbeusekom** [comment] 2021-09-29 13:01
Hi @khandilist, @markizdeviler, 

We have a [pull request](https://github.com/Baseflow/flutter-geolocator/pull/830) ready which should resolve these issues. We are however a bit reluctant to merge it, since it would mean that everybody using the geolocator plugin should now also update the `compileSdkVersion` to `31` or they will receive a compile error.
