### ISSUE TITLE
getPositionStream not being updated while application is in background

### ISSUE THREAD

**Issue by devalp-pro** [Baseflow/flutter-geolocator#444] opened 2020-05-22 17:50 UTC
## 🐛 Bug Report

I had called the getPositionStream method to get continue location update in the foreground and background, but it's work in the foreground not in the background. While the application is in the background and we changed location update then it will not update but when we go to map app and update location then getPositionStream updates new location till then it will not be reflected in the application.

```
class SearchPage extends StatefulWidget {
  const SearchPage({Key key, this.authenticationBloc}) : super(key: key);
  @override
  _SearchPageState createState() => _SearchPageState();
}
```

```
class _SearchPageState extends State<SearchPage> {

GeolocationStatus _geolocationStatus = GeolocationStatus.unknown;

Geolocator _geoLocator = Geolocator();

bool _isGeoInitializeCompleted = false;

@override
  void initState() {
    super.initState();
    debugPrint("[${LabelConst.appName}] Widget State => Init");
  }

	@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    debugPrint("[${LabelConst.appName}] Widget Did Change Dependencies");
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      _checkForLocationPermission();
    });
	checkForGeoFenceInitialize();
  }
  
  _checkForLocationPermission() {
    _geoLocator.checkGeolocationPermissionStatus().then((geoStatus) {
      setState(() {
        _geolocationStatus = geoStatus;
      });
      Geofence.requestPermissions();
    });

    _getSavedGeoLocation();

    if (_isGeoInitializeCompleted) _getCurrentLocation();
  }

	checkForGeoFenceInitialize() async {
    debugPrint("[${LabelConst.appName}] checkForGeoFenceInitialize ==> $mounted");
    if (!mounted) {
      _isGeoInitializeCompleted = false;
      return;
    }
    Geofence.initialize();

    Geofence.startListening(GeolocationEvent.entry, (entry) {
      debugPrint("[${LabelConst.appName}] Geo Lististening Mounted ==> $mounted");
      debugPrint("[${LabelConst.appName}] Geo Lististening  Point ==> $entry Event => Enter");
      if (mounted && _appLifecycleState == AppLifecycleState.paused || _appLifecycleState == AppLifecycleState.inactive) {
        scheduleNotification(LabelConst.appName, LabelConst.labelNotification, entry);
      } else if (!mounted) {
        scheduleNotification(LabelConst.appName, LabelConst.labelNotification, entry);
      } else {
        _showDialog(entry);
      }
    });

    setState(() {
      _isGeoInitializeCompleted = true;
    });
  }
  
  void _getCurrentLocation() async {
    var locationOptions = LocationOptions(
        accuracy: LocationAccuracy.bestForNavigation,
        distanceFilter: 1,
        forceAndroidLocationManager: false,
        timeInterval: Duration(seconds: 1).inMilliseconds);
    _geoLocator.getPositionStream(locationOptions).listen((Position position) async {
      debugPrint("[${LabelConst.appName}] Current Location => " +
          (position == null ? "Unknown" : "Lat : ${position.latitude} and Long : ${position.longitude}"));

      if (position != null && _currentPosition != null) {
        double distance =
            await Geolocator().distanceBetween(_currentPosition.latitude, _currentPosition.longitude, position.latitude, position.longitude);
        debugPrint("[${LabelConst.appName}] Distance Between Points => $distance");
        if (distance > 50) {
          if (mounted) {
            setState(() {
              _currentPosition = LatLng(position.latitude, position.longitude);
            });
            _mapController.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(target: _currentPosition, zoom: DEFAULT_ZOOM_LEVEL)));
          }
        }
      } else if (position != null) {
        if (mounted) {
          setState(() {
            _currentPosition = LatLng(position.latitude, position.longitude);
          });
          _mapController.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(target: _currentPosition, zoom: DEFAULT_ZOOM_LEVEL)));
        }
      }
    });
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        flexibleSpace: SafeArea(
          child: Hero(
            child: Image.asset(
              ImageConst.imageAppbarLogo,
            ),
            tag: TagConst.tagLogo,
          ),
        ),
      ),
      body: Padding(
        padding: fit.only(top: 20),
        child: Column(
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Flexible(
              flex: 1,
              fit: FlexFit.tight,
              child: _mapWidget(),
            ),
            Flexible(
              flex: 1,
              fit: FlexFit.tight,
              child: ListView(
                shrinkWrap: true,
                padding: fit.only(bottom: 10),
                children: <Widget>[
                  Text(
                    LabelConst.labelMapTitle,
                    textAlign: TextAlign.center,
                    style:
                        TextStyle(height: 2, fontFamily: FontConst.impact, color: AppColors.ThemeColor[AppColors.ColorAccent], fontSize: fit.t(32)),
                  ),
                  Text(
                    LabelConst.labelMapDescription,
                    textAlign: TextAlign.center,
                    style: TextStyle(fontFamily: FontConst.centuryGothic, color: AppColors.ThemeColor[AppColors.ColorAccent], fontSize: fit.t(26)),
                  ),
                  Padding(
                    padding: fit.only(top: 18),
                    child: GFButton(
                      size: GFSize.LARGE,
                      shape: GFButtonShape.pills,
                      onPressed: () {
                        _getGeoPoints();
                      },
                      fullWidthButton: true,
                      text: LabelConst.labelSearchFotItems,
                      textStyle: TextStyle(
                        fontFamily: FontConst.myriadPro,
                        fontSize: fit.t(36),
                      ),
                      color: AppColors.ThemeColor[AppColors.ColorCommon],
                    ),
                  ),
                  TextDivider(
                    color: AppColors.ThemeColor[AppColors.ColorOffer],
                    text: LabelConst.labelClaimOffer,
                  ),
                  if (_userInformation != null)
                    GridCircleList(
                      dealType: LabelConst.labelAll,
                      leftArrowIcon: ImageConst.imageLeftArrowRed,
                      rightArrowIcon: ImageConst.imageRightArrowRed,
                      userInformation: _userInformation,
                      onListItemTap: (deal) {
                        if (deal.isClaimed) {
                          _redirectToPage(
                              context,
                              DashboardPage(
                                authenticationBloc: widget.authenticationBloc,
                              ),
                              true);
                        } else {
                          _redirectToPage(
                              context,
                              ClaimOfferPage(
                                userInformation: _userInformation,
                                deal: deal,
                                authenticationBloc: widget.authenticationBloc,
                              ),
                              false);
                        }
                      },
                    ),
                ],
              ),
            ),
            BottomButtons(
              tag: TagConst.tagSearchMapScreen,
              authenticationBloc: widget.authenticationBloc,
            ),
          ],
        ),
      ),
    );
  }
  
  _mapWidget() {
    return GoogleMap(
      circles: _circleList,
      mapType: MapType.hybrid,
      compassEnabled: false,
      indoorViewEnabled: false,
      buildingsEnabled: true,
      myLocationEnabled: _geolocationStatus == GeolocationStatus.granted,
      myLocationButtonEnabled: _geolocationStatus == GeolocationStatus.granted,
      tiltGesturesEnabled: true,
      rotateGesturesEnabled: true,
      scrollGesturesEnabled: true,
      zoomGesturesEnabled: true,
      zoomControlsEnabled: true,
      initialCameraPosition: CameraPosition(target: _currentPosition, zoom: DEFAULT_ZOOM_LEVEL),
      onMapCreated: (GoogleMapController controller) async {
        _mapCompleter.complete(controller);
        _mapController = await _mapCompleter.future;
      },
    );
  }
}
```
``` 
**Application Log**

2020-05-22 22:56:03.256 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.06159 and Long : 72.5144
2020-05-22 22:56:03.257 4385-4438/com.gramstands.io I/chatty: uid=10138(com.gramstands.io) Thread-2 identical 1 line
2020-05-22 22:56:03.257 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.06159 and Long : 72.5144
2020-05-22 22:56:03.259 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 1230.107421875
2020-05-22 22:56:03.259 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 8228532.5
2020-05-22 22:56:03.262 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 999.4940795898438
2020-05-22 22:56:03.320 4385-4385/com.gramstands.io D/DC: Called onreceive
2020-05-22 22:56:03.325 4385-4385/com.gramstands.io I/GeoBroadcastReceiver: GeoRegion(id=Deval Home, radius=50.0, latitude=23.06159, longitude=72.5144, events=[entry])
2020-05-22 22:56:03.341 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Geo Lististening Mounted ==> true
2020-05-22 22:56:03.341 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Geo Lististening  Point ==> Instance of 'Geolocation' Event => Enter
2020-05-22 22:56:03.573 4385-4438/com.gramstands.io I/flutter: ProgressDialog shown
2020-05-22 22:56:03.780 4385-4398/com.gramstands.io I/m.gramstands.i: Background young concurrent copying GC freed 81442(2976KB) AllocSpace objects, 4(208KB) LOS objects, 16% free, 15MB/18MB, paused 386us total 156.621ms
2020-05-22 22:56:04.544 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] User information ==> devalp.pro@gmail.com
2020-05-22 22:56:04.544 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Config Id => M7NJzKLzPrumpcgRVXi3
2020-05-22 22:56:05.283 4385-4438/com.gramstands.io I/flutter: ProgressDialog dismissed
2020-05-22 22:56:05.635 4385-4438/com.gramstands.io I/flutter: ProgressDialog dismissed by back button
2020-05-22 22:56:40.309 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] App Lifecycle State => AppLifecycleState.inactive
2020-05-22 22:56:40.309 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Widget Lifecycle State => AppLifecycleState.inactive
2020-05-22 22:56:42.938 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] App Lifecycle State => AppLifecycleState.paused
2020-05-22 22:56:42.939 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Widget Lifecycle State => AppLifecycleState.paused
2020-05-22 22:57:16.361 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.07647 and Long : 72.5076033
2020-05-22 22:57:16.361 4385-4438/com.gramstands.io I/chatty: uid=10138(com.gramstands.io) Thread-2 identical 1 line
2020-05-22 22:57:16.361 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.07647 and Long : 72.5076033
2020-05-22 22:57:16.365 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 990.374267578125
2020-05-22 22:57:16.365 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 8228039.5
2020-05-22 22:57:16.365 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 1789.01708984375
2020-05-22 22:57:18.442 4385-7256/com.gramstands.io W/m.gramstands.i: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2020-05-22 22:57:26.601 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.0701767 and Long : 72.5174033
2020-05-22 22:57:26.601 4385-4438/com.gramstands.io I/chatty: uid=10138(com.gramstands.io) Thread-2 identical 1 line
2020-05-22 22:57:26.602 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Current Location => Lat : 23.0701767 and Long : 72.5174033
2020-05-22 22:57:26.609 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 287.1610107421875
2020-05-22 22:57:26.609 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 8228952.5
2020-05-22 22:57:26.609 4385-4438/com.gramstands.io I/flutter: [GRAM STANDS IO] Distance Between Points => 1222.3394775390625

```

### Expected behavior
getPositionStream method get continues updated with lat long while the app is in background

### Reproduction steps
Testing all steps with Android Emulator (Pixel 3 XL API 29)
1.) Open App with registring getPositionStream method.
2.) you will get location update continuously while the application in the foreground.
3.) Press home button or navigate to other app and change your location. App getPositionStream 
 will not update with the latest position.

### Configuration
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.0)
[√] Connected device (1 available)

**Version:** 5.3.1

**Platform:** 
- [ ] :iphone: iOS (Not checking)
- [X ] :robot: Android

**Comment by mvanbeusekom** [comment] 2020-05-28 11:18
duplicate of #53

**Comment by mvanbeusekom** [comment] 2020-05-28 11:19
The geolocator indeed doesn't support running in the background. This involves more complex logic which I am not really sure as of jet how to implement.

**Comment by pY4x3g** [comment] 2020-05-28 11:44
I switched to the package [pub.dev/packages/background_location](https://pub.dev/packages/background_location) which is working fine on android.
The library is starting a foreground service to retrieve background location updates, which is indeed complex to implement.

**Comment by mvanbeusekom** [comment] 2020-08-27 13:34
closing this issue and track updates on background support on issue #53

**Closed by mvanbeusekom** 2020-08-27 13:34 UTC
Labels: type: duplicate

**Comment by temala** [comment] 2021-01-18 21:40
this works for me https://pub.dev/packages/background_location
