### ISSUE TITLE
getCurrentPosition returns same location in Android even location changes.

### ISSUE THREAD

**Issue by umamahacse** [Baseflow/flutter-geolocator#409] opened 2020-03-22 08:34 UTC
## 🐛 Bug Report

I am developing an taxi booking app,  for updating driver's location i am fetching location using getCurrentPosition.
Previously i am using 5.1.5 version with compileSdkVersion as 28. Recently i tested my app in Android 10, there was some permission based issue raised in Android 10 alone. So i changed the compileSdkVersion as 29 and upgraded the version as geolocator: ^5.3.0.
But after changing the geolocator: ^5.3.0 and  compileSdkVersion as 29 the getCurrentPosition only returns same location even at the time of moving also.
This issue only rises in Android.In iOS it works fine.
Can any one update me the solution?
Thanks you.

### Configuration
compileSdkVersion 29
**Version:** 1.x
geolocator: ^5.3.0
**Platform:** 
- [ ] :robot: Android

**Comment by estevez-dev** [comment] 2020-05-29 15:49
I think it is a duplicate of old but serious issue #313

**Comment by yacinegithub** [comment] 2020-06-15 13:04
Same isssue
Configuration
compileSdkVersion i tried both 28 and 29
Version: 1.0.0+1
geolocator: ^5.3.2+2
Platform:

 🤖 Android

**Comment by mvanbeusekom** [comment] 2020-08-31 13:55
We have just released version 6.0.0 of the geolocator which should have solved this issue.

**Closed by mvanbeusekom** 2020-08-31 13:55 UTC
Labels: status: triage
