### ISSUE TITLE
[Question]: Location stream not stopping after app being terminated

### ISSUE THREAD

**Issue by maazkhan1998** [Baseflow/flutter-geolocator#1280] opened 2023-06-24 16:01 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

I am using getlocation stream with notification config, everything is working fine, i am getting location even after app is terminated. But after terminating the app there is no way to close the stream.

### Version

9.0.2

**Comment by badrapp** [comment] 2023-09-13 12:43
Hi @maazkhan1998.
I've same issue and I'm badly stuck in it. Can you please let me know if you've figured it out.

**Comment by OsamaQureshi796** [comment] 2023-09-13 13:11
Hi @JeroenWeener I'm also badly stuck in this issue. It'll be very nice if you address this issue. Thanks

**Comment by JeroenWeener** [comment] 2023-09-14 14:48
Hi @maazkhan1998, @OsamaQureshi796, thank you for reaching out.

Could you provide me with a code sample and the contents of the `AndroidManifest.xml` your application is using?

@maazkhan1998 are you experiencing the bug on both Android and iOS?

**Comment by OsamaQureshi796** [comment] 2023-09-14 21:17
Hi @JeroenWeener, I've figured it out. The problem was caused by FirebaseMessaging.onBackgroundMessage because it was preventing the Flutter engine from closing, which resulted in the background service for the position stream not being disposed of.

**Closed** 2023-09-29 08:11 UTC
Labels: status: needs more info, type: question, status: closed (missing info), P3, background-foreground-location
