### ISSUE TITLE
Add support for Android API 32

### ISSUE THREAD

**Issue by leocape** [Baseflow/flutter-geolocator#1072] opened 2022-06-04 10:32 UTC
### Expected behavior
Setting `compileSdkVersion` and `targetSdkVersion` to 32 will fetch the location successfully on Android. 

(If `compileSdkVersion` and `targetSdkVersion` is set to 31, the location is fetched successfully - ie. the plugin appears to not yet support API 32)

### Reproduction steps
In `build.gradle`, set the `compileSdkVersion` and `targetSdkVersion` to 32:

```
android {
    lintOptions {
        checkReleaseBuilds false
    }
    compileSdkVersion 32

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 24
        targetSdkVersion 32
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
```

### Configuration

Then try get the location using the default:

```
 var _currentPosition = await Geolocator.getCurrentPosition(
        timeLimit: Duration(seconds: 600),
        desiredAccuracy: LocationAccuracy.lowest,
      );
```

**Version:** 8.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android (emulator and physical)

**Comment by mvanbeusekom** [comment] 2022-06-10 12:31
Hi @leocape,

The problem here is most likely the fact that you are requesting the current position using the `LocationAccuracy.lowest` setting. On Android this translates to the [PRIORITY_PASSIVE](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_PASSIVE) priority.

This means the application only receives location updates if other clients (applications) trigger a location update. Meaning the application doesn't consume any additional power. The Android documentation describes this as follows:

> Ensure that no extra power will be used to derive locations. This enforces that the request will act as a passive listener that will only receive "free" locations calculated on behalf of other clients.

My feeling is that in Android API 32 they have made and bug fix more strongly enforcing this principle which is why there is a difference with Android API 31. 

Using the example application on the emulator (Pixel XL API 32) I can get a location using the `LocationAccuracy.lowest` accuracy if I for example have Google Maps running in the background doing a navigation from point A to B.

If you don't want to rely on other applications to trigger the location services please make sure you set the `desiredAccuracy` to a minimum of `LocationAccuracy.low`. Here is an overview of how we map the different accuracy settings:

| Geolocator | Android |
|---|---|
| lowest | [PRIORITY_PASSIVE](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_PASSIVE) |
| low | [PRIORITY_LOW_POWER](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_LOW_POWER) |
| medium | [PRIORITY_BALANCED_POWER_ACCURACY](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_BALANCED_POWER_ACCURACY) |
| high | [PRIORITY_HIGH_ACCURACY](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_HIGH_ACCURACY) |
| best | [PRIORITY_HIGH_ACCURACY](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_HIGH_ACCURACY) |
| bestForNavigation | [PRIORITY_HIGH_ACCURACY](https://developers.google.com/android/reference/com/google/android/gms/location/Priority#PRIORITY_HIGH_ACCURACY) |

I will close this issue now as my tests indicate that the plugin is working as intended. Please feel free to leave a comment if you have other behavior.

**Closed by mvanbeusekom** 2022-06-10 12:31 UTC
