### ISSUE TITLE
For Chinese devices, Google Play Store is missing

### ISSUE THREAD

**Issue by jahnli** [Baseflow/flutter-geolocator#794] opened 2021-07-26 02:08 UTC
### Reproduction steps

![image](https://user-images.githubusercontent.com/20943608/126923654-a7496957-090e-41db-a2d8-f5fc7905d5c3.png)
When I set forceAndroidLocationManager, I still can't get  

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by jahnli** [comment] 2021-07-29 09:07
@sestegra @willbryant @AlexandreRoba

**Comment by willbryant** [comment] 2021-07-29 09:14
I have literally no idea why you tagged me. Unsubscribing.

**Comment by mvanbeusekom** [comment] 2021-08-02 06:01
@jahnli, as I am not in China I cannot reproduce this issue on a real device. The only thing I can do is use an emulator without Google Play Store installed. Which for me works fine, have a look at this issue with complete reproduction steps and source code: https://github.com/Baseflow/flutter-geolocator/issues/773#issuecomment-883311979

Feel free to debug further using the plugin source code and if you notice a mistake I would be happy to help and fix it. In that case don't hesitate to leave another comment. For now I will be closing this issue as there isn't much other details and as shown in the linked issue the above code simply work on the emulator and real devices.

**Closed by mvanbeusekom** 2021-08-02 06:01 UTC
