### ISSUE TITLE
Please add feature to show android deafault pop to enable notification using play services.

### ISSUE THREAD

**Issue by parmeetmaster** [Baseflow/flutter-geolocator#1106] opened 2022-07-16 12:34 UTC
### Describe the feature

The location plugin allows me to show pop to enable GPS location via google play services. Can you please add this feature to your plugin so I can remove that location plugin?

I am just frustrated to manage both plugins for this small feature.It is also good for your plugin as well.Please consider to add for next update

![image](https://user-images.githubusercontent.com/42370506/179354994-43f6bd41-97bb-4144-84c8-ac3dc45e9421.png)

### Platforms affected (mark all that apply)
- [ ] :robot: Android

**Comment by Robbendebiene** [comment] 2022-07-26 07:57
As far as I know geolocator always displays this kind of popup on location request when google play/location services are installed but  "Google Location Accuracy" setting is disabled.

**Comment by florissmit1** [comment] 2022-08-05 09:29
Hey @parmeetmaster, thanks for your request. I did some research and I guess it's possible, but we will need to make some major changes to the Android implementation. I'm not sure if we will make the changes, will keep you up to date in this thread!

**Comment by parmeetmaster** [comment] 2022-08-05 19:37
@florissmit1 if you feel okay, You can make me a contributor.I can add solution and create pull request,If you feel okay you can merge into main branch or do required updates.

**Comment by JeroenWeener** [comment] 2023-07-11 13:57
Hi @parmeetmaster!

First of all, my apologies for the radio silence. Due to shifting priorities we were unable to keep up with the maintenance of the geolocator plugin. This has recently changed, giving us time to catch up and work on the geolocator once again.

To come back to your last comment:
Everyone can contribute to the geolocator plugin. You can fork the repository, create a new branch, submit a PR and wait for review. So feel free to contribute to the plugin and implement this feature! If you need help setting up a fork or getting familiar with this plugin's structure, do not hesitate to ping me or @mvanbeusekom. We would be happy to help.

**Comment by mvanbeusekom** [comment] 2023-07-21 15:27
Closing as duplicate of #543, we'll keep progress of this issue there.

**Closed by mvanbeusekom** 2023-07-21 15:27 UTC
Labels: type: duplicate, type: enhancement, platform: android, P3
