### ISSUE TITLE
[Feature Request]: A method for requesting user to enable location service without redirecting them to location settings

### ISSUE THREAD

**Issue by Prince2347X** [Baseflow/flutter-geolocator#1289] opened 2023-07-21 14:45 UTC
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Use case

Currently, we can only check if location services are enabled or not by `Geolocator.isLocationServiceEnabled()` method and to tell the users to enable location service, we are required to redirect users to location settings to enable location service. This flow works fine but imagine a case where we don't want to redirect users from our app to settings just for turning on location service when a popup can be shown just like asking for permission. (An attachment is attached below for demonstrating how it looks on android)

![IMG_20230721_200250](https://github.com/Baseflow/flutter-geolocator/assets/68418241/54d852a0-d9c1-4922-b5b9-5f3dd3f654f9)

### Proposal

Add a method named `requestLocationService()` which will open a popup (as shown above) in android which will allow the users directly to turn on their location without redirecting them to location page. This feature is available in the location package but it doesn't have all the features provided in this package.

**Comment by mvanbeusekom** [comment] 2023-07-21 15:28
Closing as duplicate of #543, we'll keep track of progress regarding this feature there.

**Closed by mvanbeusekom** 2023-07-21 15:28 UTC
