### ISSUE TITLE
Geolocator gives different coordinates at the same location

### ISSUE THREAD

**Issue by bhanuka96** [Baseflow/flutter-geolocator#596] opened 2020-11-17 11:25 UTC
`  geolocator: ^6.1.6`

It's return so many lat and lng when I using `forceAndroidLocationManager: true`. And also return many lat and lng when I using `forceAndroidLocationManager: false`.

**Example: I didn't move the phone. Phone on my desk**

Using `forceAndroidLocationManager: true` return more than 100 list of latLng within 1 minutes.

Using `forceAndroidLocationManager: false` return more than 20 list of latLng within 1 minutes.

Why return list of latLng without moving device? And also I remove duplicate latLng too.

```
  list.removeWhere((element) => element?.latitude == userLocation?.latitude || element?.longitude == userLocation?.longitude);
    list.add(userLocation);
```

Stream Data 

```
    Geolocator.requestPermission().then((value) {
      if (value == LocationPermission.whileInUse || value == LocationPermission.always) {
        Geolocator.getPositionStream(desiredAccuracy: LocationAccuracy.bestForNavigation, distanceFilter: 0, timeInterval: 1000,
            forceAndroidLocationManager: false
        ).listen((event) {
          if (event != null) {
            _locationController.add(LocationModel.fromGeoLocatorData(event));
          }
        });
      }
    });
```

**I am calculating totalKM based on the list of LatLng.**

**I am getting more than 10km result within 10 minutes without moving the device. Why is that?**

```
  double getDistanceKM() {
    list.removeWhere((element) => element?.latitude == userLocation?.latitude || element?.longitude == userLocation?.longitude);
    list.add(userLocation);

    double calculate = 0;
     if (list.length > 1) {
        LocationModel firstLoc = list.elementAt(list.length - 2);
        LocationModel lastLoc = list.last;
        calculate = calculateDistance(firstLoc.latitude, firstLoc.longitude, lastLoc.latitude, lastLoc.longitude);
      }

//THIS WAY IS NOT WORKING TOO. BECAUSE SPEED IS ALWAYS RUNNING
//  if (userLocation.speed != null) {
//      if (userLocation.speed > .2 && list.length > 1) {
//        LocationModel firstLoc = list.elementAt(list.length - 2);
//        LocationModel lastLoc = list.last;
//        calculate = _cp.calculateDistance(firstLoc.latitude, firstLoc.longitude, lastLoc.latitude, lastLoc.longitude);
//      }
//    }

    totalKm += calculate;
    return totalKm;
  }
```

```
  double calculateDistance(lat1, lon1, lat2, lon2) {
    var p = 0.017453292519943295;
    var c = cos;
    var a = 0.5 - c((lat2 - lat1) * p) / 2 + c(lat1 * p) * c(lat2 * p) * (1 - c((lon2 - lon1) * p)) / 2;
    return 12742 * asin(sqrt(a));
  }
```

**Comment by Sempakonka** [comment] 2020-12-09 09:02
Hi @bhanuka96 
I think what the problem is is that in your case Geolocator can't get a precise location enough to make this code work. In fact, the technology is [simply not there yet.](https://stackoverflow.com/questions/55721048/is-there-a-way-to-get-a-constant-accuracy-of-5-10-mts)

Everytime a new location comes in, a small displacement gets added to your `totalKM`, eventually leading up to great distances.

Could you try to set the `distanceFilter` to let's say, 25 meters and see if there is any improvement?

Links for futher explanation:
[FusedLocationProviderClient issue (default Api in android Geolocator uses) ](https://stackoverflow.com/questions/54274184/fused-location-provider-setsmallestdisplacement-not-working-in-specific-movement)
[More FusedLocationProviderclient](https://stackoverflow.com/questions/53666679/fusedlocationproviderclient-gives-different-location-sometimes)
[Stackoverflow issue where someone is explaining it far better than me](https://stackoverflow.com/questions/14183849/android-location-is-inaccurate)

**Comment by bhanuka96** [comment] 2020-12-09 11:44
@Sempakonka Thanks for your reply. I will try and let you know

**Comment by mvanbeusekom** [comment] 2020-12-23 10:12
Closing this issue as per explanation of @Sempakonka.

**Closed by mvanbeusekom** 2020-12-23 10:12 UTC
Labels: status: waiting for customer response
