### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by kadnan0900** [Baseflow/flutter-geolocator#600] opened 2020-11-21 13:21 UTC

**Comment by mvanbeusekom** [comment] 2020-11-23 09:26
Duplicate of #551. Try running `flutter clean` and `flutter pub get` and make sure you are on the gradle version. 

Closing by lack of information. If you wish us to spend our valuable time to help you, make sure you take some time yourself and make a proper bug report.

**Closed by mvanbeusekom** 2020-11-23 09:26 UTC
