### ISSUE TITLE
throw error when checkPermission

### ISSUE THREAD

**Issue by wolru** [Baseflow/flutter-geolocator#1162] opened 2022-11-01 07:12 UTC
Hi, Geolocator.checkPermission() throw error when permission is denied in Android

Library version is
geolocator: ^9.0.1

**Comment by mvanbeusekom** [comment] 2022-11-01 10:11
Please help us help you and provide more details:

1. Please provide the full stack trace of the error you received.
2. Provide clear reproduction steps, give a description of the steps you took resulting in the error (walk us through the state of your application).
3. Provide a list of permissions you added to the `AndroidManifest.xml` file (this should match the permissions documented in the `android` section of the README.md.
4. Include the output of the `flutter doctor -v` command.

Without this information we are unable to help you.

**Comment by Retr0sec7** [comment] 2022-11-03 16:13
Hi @wolru. Recently I created a flow that checks for permission status on Android devices (not sure if it works on iOS). Turns out that `Geolocator.checkPermission()` is no longer a thing (docs seems to be outdated). The method working to check permissions is called `Geolocator.checkGeolocationPermissionStatus()`. This is will return a GeolocationPermissionStatus object with value (int) which is one of the five (I believe) statuses defined on `GeolocationPermissionStatus` class.

Check out the code I provided on this Issue thread [on this Issue thread](https://github.com/Baseflow/flutter-geolocator/issues/1164). Hopefully that helps.

**Comment by mvanbeusekom** [comment] 2022-11-03 16:55
@Retr0sec7, can you please remove the above comment. The `checkPermission()` is most certainly still "a thing". The method `checkGeolocationPermissionStatus()` is not part of the Geolocator package and not supported by us.

**Comment by mvanbeusekom** [comment] 2022-11-03 17:31
Hi @wolru,

This error is guaranteed only thrown when calling the `getCurrentPosition`, `getPositionStream` or `getLastKnowLocation` method while the user has denied permission. 

This means the application makes a call to one of the above methods without first checking if permissions are granted. This error cannot be thrown from calling the `checkPermission` method as mentioned in your original question. Please have a look through the code base and ensure the above methods are only called when the user explicitly granted permission.

P.S. make sure you await any call to the `checkPermission` call before calling one of the above methods.

I am going to close this issue for now as this seems to be a user error. Feel free however to leave a comment with argumentation when you feel this is incorrect.

**Closed by mvanbeusekom** 2022-11-03 17:31 UTC
Labels: platform: android

**Comment by theashggl** [comment] 2026-09-02 15:09
Facign issue with the method right now. 
Geolocator-13.0.2
Android 16
Call to the method in initstate of a widget results in a repeated rebuild of that widget.
My functionality code to manage permission.(Convert the file to dart on your side)

[geolocator.checkpermission issue.txt](https://github.com/user-attachments/files/31743866/geolocator.checkpermission.issue.txt)

[logs for checkpermission issue.txt](https://github.com/user-attachments/files/31743881/logs.for.checkpermission.issue.txt)
