### ISSUE TITLE
ACCESS_BACKGROUND_LOCATION problem

### ISSUE THREAD

**Issue by imeDevelopers** [Baseflow/flutter-geolocator#886] opened 2021-11-02 12:45 UTC
if we add permission ACCESS_BACKGROUND_LOCATION to our AndroidManifest.xml

in the past the plugin was asking the user to "Always" use the location, even if the app are closed

now it just show Use While using app only, and "always" OPTION not shown to the user .if the permission is added

it's old problem 6 months or something like that, i was think you will note it and simply fix it, but you didn't, i don't know the reason ..

thank you.

**Comment by mvanbeusekom** [comment] 2021-11-02 13:39
This is intended behavior. As of Android 10, Google changed their policy on requesting location permissions. 

From Android 10 and higher you first need to request "while in use" access. Once you have that you can request background access. You can read more about this in the [official Android](https://developer.android.com/training/location/permissions) documentation.

The geolocator will handle this for you (as long as you specify the permissions in your AndroidManifest.xml file). You do however have to call the `requestPermission` twice (once to get "while in use" access and if granted a second time to get "always" permission). 

You will notice the options in the dialog change the second time you request permission.

I am going to close this issue as this is intended behavior on Android by Google.

**Closed** 2021-11-02 13:39 UTC
