### ISSUE TITLE
Position and LocationAccuracy aren't defined for GeoLocator Package

### ISSUE THREAD

**Issue by VM-Vishnu** [Baseflow/flutter-geolocator#768] opened 2021-07-02 05:22 UTC
Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);

When i use this line of code in my flutter package i get :
* Undefined class Position.
* Undefined name LocationAccuracy .
  ### This error occurs in the version ^7.2.0+1. It worked fine in the previous version ^7.1.0

This is my pubspec code:
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.2.0+1
```

 **flutter doctor -v:**
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.3 at C:\Src\Flutter\flutter
    • Framework revision f4abaa0735 (10 hours ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!
```

**Comment by mvanbeusekom** [comment] 2021-07-02 07:23
@VM-Vishnu I have tried to reproduce the issue but failed. I took the following steps:

1. Created a new Flutter application to test: `flutter create geo_issue_768`;
2. Added the dependency to the `pubspec.yaml` (see below);
3. Updated code to fetch position to the `_incrementCounter()` method to the `main.dart` (see below).

> note: I debugged the application in de browser and therefore didn't add any permissions. If you are running on iOS or Android (which I don't think you will according to your `flutter doctor` log) you'll have to add the required permissions aswell.

<details>
<summary>pubspec.yaml</summary>

```yaml
name: geo_issue_768
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.2.0+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best)
        .then((Position position) => print('Position: $position'));

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

So this looks something related to your local environment. Things you can check are:

1. Double check if you imported the geolocator in de file you are using it: `import 'package:geolocator/geolocator.dart';`;
2. Make sure you are not overriding the `geolocator` or `geolocator_platform_interface` packages in your `pubspec.yaml` file;
3. Run `flutter clean` and `flutter pub upgrade` and try again;
4. If all that fails try removing the geolocator packages from the .pub-cache folder. Since I am using macOS I am not sure where this folder is located on Windows. According to the [Dart documentation](https://dart.dev/tools/pub/environment-variables) it should be located at the following location `%LOCALAPPDATA%\Pub\Cache`, however it might also be part of your Flutter installation folder, which is `C:\Src\Flutter\flutter` according to your `flutter doctor -v` output. Alternatively you can try to run the `dart pub cache repair` command which does a clean reinstall of all cached packages.

I am going to close this issue as it doesn't seem to be an issue related to the geolocator package it self (works locally and also the automated build on the CI compiles correctly). However if you have any questions or comments feel free to add them here.

**Closed by mvanbeusekom** 2021-07-02 07:23 UTC
