### ISSUE TITLE
LatLong not updating, when application is paused state.

### ISSUE THREAD

**Issue by saravananmnm** [Baseflow/flutter-geolocator#527] opened 2020-09-21 07:40 UTC
I have created as a custom method for getting current location here it's working fine application running state. But when application is minimized/paused, it's not getting latest current location, instead of getting old one latlong.

How we resolve this?

` static Future<Position> getCurrentLocation() async {
    var geoLocator = new Geolocator();
    var result = await geoLocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best);
    return Future.value(result);
  }`

**Comment by mvanbeusekom** [comment] 2020-09-21 07:43
Duplicate of #53 

The geolocator doesn't support location updates while running in the background.

**Closed by mvanbeusekom** 2020-09-21 07:43 UTC
Labels: type: duplicate
