### ISSUE TITLE
No popup dialog when request a location permission on iOS 14.4.1

### ISSUE THREAD

**Issue by aoboinfo** [Baseflow/flutter-geolocator#762] opened 2021-06-24 08:47 UTC
The same source.
It worked on iOS under 14.
but when update to iOS 14.4.1, there is no Popup dialog show to let user select option of Location service.

**Comment by mvanbeusekom** [comment] 2021-06-28 15:30
@aoboinfo thank you for posting this issue. It is however a bit unclear. What do you mean with "there is no Popup dialog show to let user select option of Location service."?

The only dialog that should be shown on iOS is the dialog requesting location permissions. This doesn't show up when permissions are already granted.

Could you specify some more details? Information that would be helpful would be:

1. Which version of the geolocator plugin are you using?
2. Provide the full output of the `flutter doctor -v` command.
3. The code snippet you are using where you are expecting the "Popup dialog" (even better would be a reproducible example);

**Comment by aoboinfo** [comment] 2021-06-30 03:44
Thank you for your reply.
The version I used is 7.1.1.
I used geolocator and app_tracking_transparency which is a must plugin for Google Ads ads.

When launch app, app_tracking_transparency permission is pop up at first, when close this permission dialog, there is not any more permission dialog.

But when I use geolocator only in another app, the Location service permission dialog shows normally.

I think that in app_tracking_transparency permission include to access user location, maybe this is the reason.
At present, I not clear that should show location service again after closing app_tracking_transparency permission dialog,
because my app has passed review of Apple.

Best regards.

**Comment by mvanbeusekom** [comment] 2021-07-02 08:16
@aoboinfo I have been trying to reproduce the problem but on my side everything seems to work fine. Here is what I did maybe you can reproduce it:

1. Create a new Flutter App: `flutter create geo_issue_762`;
2. Add the necessary dependencies to the `pubspec.yaml` (see `pubspec.yaml` code below);
3. Add the necessary permissions to the `ios/Runner/Info.plist` file for both ATT and Location (see `Info.plist` below);
4. Update the `main.dart` file to request permissions for ATT and Location services (see `main.dart` below);
5. Run the App on the simulator or real device with iOS 14 or higher. Press button to request permissions, in my case each time the requests are showing a dialog correctly.

<details>
<summary>pubspec.yaml</summary>

```yaml
name: geo_issue_768
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.2.0+1
  app_tracking_transparency: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>Info.plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>geo_issue_768</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSUserTrackingUsageDescription</key>
	<string>This identifier will be used to deliver personalized ads to you.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location when open.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app needs access to location when in the background.</string>
</dict>
</plist>

```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:app_tracking_transparency/app_tracking_transparency.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _requestLocationPermissions() {
    Geolocator.requestPermission()
        .then((status) => print('Location permissions: $status'));
  }

  void _requestAttPermissions() {
    AppTrackingTransparency.requestTrackingAuthorization()
        .then((status) => print('ATT permissions: $status'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          FloatingActionButton(
            onPressed: _requestAttPermissions,
            tooltip: 'ATT Permissions',
            child: const Icon(Icons.track_changes),
          ),
          const SizedBox(
            height: 10,
          ),
          FloatingActionButton(
            onPressed: _requestLocationPermissions,
            tooltip: 'Locaton Permisssions',
            child: const Icon(Icons.location_city),
          ),
        ],
      ),
    );
  }
}

```
</details>

Since I am not able to reproduce the issue I am not sure what the problem is. Can you supply an example reproducing the problem?

**Comment by aoboinfo** [comment] 2021-07-02 09:36
Thank you very much for your kind reply.
I do not use this two plugin separately in my app.
At first, with initialization of Google Ads plugin app_tracking was called.
then visit user location service, and call location request.
I will check again when I update my app next time.

Best regards.

**Comment by vixez** [comment] 2021-08-09 09:39
I had the same issue. Apparently if your locations are toggled off, the permission popup does not show.
Once I turned location services on and tried my app again, it worked.

**Comment by PiotrMitkowski** [comment] 2021-08-10 09:59
Hey! I'm currently experiencing the same issue when running the app on my iPhone device with iOS 14.6. At the same time it works well in simulators. I'm running a demo with `geolocator`, I don't use any other dependencies (like ATT in example above). I did the following:
1. Create a new Flutter App: `flutter create geo_issue_762`;
2. Add the `geolocator` dependency to `pubspec.yaml`
3. Add the necessary permissions to the `ios/Runner/Info.plist` file for Location (Always, When in use, Always & when in use permissions)
4. Update the `main.dart` file to request permissions for Location services (see main.dart below);
5. Update the bundle ID and dev team to be able to run on a real device 
5. Run the App on real device with iOS 14.6. Press button to request permissions.

**Expected result**
App displays a popup asking for permission

**Actual result**
Nothing happens after a while (e.g. 5 minutes). When clicking second time on the button, it writes an error to console about already running location permission request 

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _requestPermissions() async {
    print('checking permissions');
    final status = await Geolocator.requestPermission();
    print (status);
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Location permissions demo',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _requestPermissions,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at /Users/piotrmitkowski/flutter/flutter
    • Framework revision f4abaa0735 (6 tygodni temu), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

```
</details>

**Comment by mvanbeusekom** [comment] 2021-08-10 10:07
Hi @PiotrMitkowski, thank you for the extensive reproduction steps. At the moment I am on a holiday and don't have access to my laptop.

One question, can you confirm that you have the location services enabled? Maybe you can also add an additional call to the `isLocationServiceEnabled` method and print the result?

**Comment by PiotrMitkowski** [comment] 2021-08-10 10:27
Sure! I forgot to mention it in my original comment, but I've checked the status of location services on my device and they were enabled. Right now I've added a check for `isLocationServiceEnabled` and it was `true`. I've added my updated `main.dart` code below. 


<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _requestPermissions() async {
    print('1. checking location services');
    final locationServicesStatus = await Geolocator.isLocationServiceEnabled();
    print(locationServicesStatus);
    print('2. checking permissions');
    final status = await Geolocator.requestPermission();
    print (status);
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Location permissions demo',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _requestPermissions,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>

**Comment by mvanbeusekom** [comment] 2021-08-23 16:15
@PiotrMitkowski thank you for reporting back. Since this seems to have been a one off issue with your device I will close this issue for now.

If the same problem occurs again, please don't hesitate to leave a comment and I would be happy to re-open the issue.

**Closed by mvanbeusekom** 2021-08-23 16:15 UTC
Labels: status: needs more info, platform: ios
