### ISSUE TITLE
[Bug]: GeoLocator does not work on MacOs

### ISSUE THREAD

**Issue by flaviolacer** [Baseflow/flutter-geolocator#1537] opened 2024-06-25 19:48 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Make all configurations and after you have permission, call getCurrentPosition(desiredAccuracy: LocationAccuracy.high). 

### Expected results

Get the position

### Actual results

Stuck and show this message error:  LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 0.).

Android mobile works fine.

### Code sample

<details><summary>Code sample</summary>

```dart
 var   serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
          var  permission = await Geolocator.requestPermission();
           Position _position =   await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

12.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by TimHoogstrate** [comment] 2024-06-28 07:57
Looks like a duplicate of (https://github.com/Baseflow/flutter-geolocator/issues/1534)

**Closed** 2024-06-28 15:36 UTC
