### ISSUE TITLE
Location stream continue in background

### ISSUE THREAD

**Issue by neighborfit** [Baseflow/flutter-geolocator#612] opened 2020-11-29 13:32 UTC
Hi guys. Great package. Thanks.

Just one question from me: the stream stops when the app is in the background.

Is there currently a way to allow it to continue fetching location in the background? (For example, if a person is tracking their jogging but they want to open their music app while they jog).

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment] 2020-12-01 08:15
Hi @neighborfit, the geolocator doesn't support running in the background. There is an feature request for this (see #53)  but I haven't found the time to make a good implementation for this. 

I will close this issue as being duplicate of #53 and keep track of progress in that issue.

**Closed** 2020-12-01 08:15 UTC
Labels: type: duplicate
