### ISSUE TITLE
[BUG] White Screen First Open App

### ISSUE THREAD

**Issue by fajaregafirmansyah** [Baseflow/flutter-geolocator#1296] opened 2023-08-01 16:43 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

I'am using Flutter 3.10.6

### Expected results

I'am using Flutter 3.10.6

### Actual results

when you open the application, the licensing conditions have been allowed for a very long time, more than 5 seconds. but when the cellphone GPS is turned off, opening the application is very fast.

### Code sample

<details><summary>Code sample</summary>

```dart
I'am using Flutter 3.10.6
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

I'am using Flutter 3.10.6

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
I'am using Flutter 3.10.6
```

</details>

**Comment by JeroenWeener** [comment] 2023-08-10 14:30
Hi @fajaregafirmansyah, thank you for reaching out!

You did not include much information for us to help you out. Could you provide us with a code example and a video demonstration?

My initial idea from reading your question is that your code depends on the first coordinate to load the UI, causing the delay. Do you perhaps call `await geolocator.getCurrentPosition()` in the `build` method?

**Comment by martin-braun** [comment] 2023-08-11 00:54
I can confirm this issue and it took me hours to find its cause. Our app seem to run fine in iOS and also fine in debug mode on Android, but our published Android app has a huge problem:

Whenever it's started, we had a white screen for 5 to 40 seconds, depending on the device. I spent hours stripping down our code to a minimal example and still being able to reproduce it on the release build.

Then I started removing dependency by dependency and as soon as I removed `geolocator` my app started in an instant. But after putting `geolocator` back and seeing the problem coming back, I noticed that it would also get fixed by removing `safe_device`. So it's not just `geolocator`, it's both dependencies colliding in some way. 

@JeroenWeener I stripped down my app and removed almost anything and everything, this is the main.dart:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(const AppFoodDelivery());
}

class AppFoodDelivery extends StatefulWidget {
  const AppFoodDelivery({super.key});

  @override
  State<AppFoodDelivery> createState() => _AppFoodDelivery();
}

class _AppFoodDelivery extends State<AppFoodDelivery> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Text("/HOME"),
      title: "Food Delivery",
      debugShowCheckedModeBanner: false,
    );
  }
}
```

And this is the pubspec.yaml:

```yaml
name: fooddelivery
description: Food Delivery Flutter App

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  geolocator: ^9.0.2
  safe_device: ^1.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

As soon as you either remove `geolocator` or `safe_device`, the problem is fixed.

```
> fvm flutter doctor -v                                                                           [android-crash-test]
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/marty/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/marty/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/marty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Arc.app/Contents/MacOS/Arc

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • Lenovo TB X606F (mobile) • HVA0BTSS                             • android-arm64  • Android 10 (API 29)
    • iPhone Xs Max (mobile)   • 2BBDAB13-5584-4DA1-8FDC-C40A742B7E93 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)          • macos                                • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)             • chrome                               • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by JeroenWeener** [comment] 2023-08-14 12:10
Thank you @martin-braun, for the elaborate information. This is really valuable in tracking down the cause of the issue.

I have tried to reproduce the behavior you are describing. These are the steps I followed:
1. Create a new Flutter project by running `flutter create temp`
2. Copy the contents of the `main.dart` file you provided
3. Copy the contents of the `pubspec.yaml` file you provided
4. Fetch the dependencies by running `flutter pub get`
5. Update `temp/android/app/build.gradle` by setting the `defaultConfig:minSdkVersion` to 21
6. Run `main.dart` on an Android emulator by clicking `Run 'app'` (not `Debug 'app'`) from Android Studio

Unfortunately, I do not encounter the behavior. Instead, my app launches instantly.

If you don't mind, could you try the steps I posted and see which result you get? My guess is that there is still a part of your project files that are different.

**Comment by Soli1065** [comment] 2023-08-16 07:54
> Thank you @martin-braun, for the elaborate information. This is really valuable in tracking down the cause of the issue.
> 
> I have tried to reproduce the behavior you are describing. These are the steps I followed:
> 
> 1. Create a new Flutter project by running `flutter create temp`
> 2. Copy the contents of the `main.dart` file you provided
> 3. Copy the contents of the `pubspec.yaml` file you provided
> 4. Fetch the dependencies by running `flutter pub get`
> 5. Update `temp/android/app/build.gradle` by setting the `defaultConfig:minSdkVersion` to 21
> 6. Run `main.dart` on an Android emulator by clicking `Run 'app'` (not `Debug 'app'`) from Android Studio
> 
> Unfortunately, I do not encounter the behavior. Instead, my app launches instantly.
> 
> If you don't mind, could you try the steps I posted and see which result you get? My guess is that there is still a part of your project files that are different.

Hi, I have the same issue and figured out that the initial white screen wont happen on first build and run. On first run or install app on either emulator or real device having geolocator package will cause the loading issue for almost 30 seconds till the device GPS service enables. I don't have this issue with Location package(Alternative for getting user locations), but since I'm using other plugins depending on geolocator,  looking for fixing.

**Comment by martin-braun** [comment] 2023-08-16 11:09
@Soli1065 Thanks for confirmation. Are you using `safe_device` package? If so, get rid of it and things will work again.

**Comment by Soli1065** [comment] 2023-08-16 11:37
> @Soli1065 Thanks for confirmation. Are you using `safe_device` package? If so, get rid of it and things will work again.
> 
> I can't confirm for now, but your issue looks like it has nothing to do with debug or release build, but rather if the debugger is attached, which is probably a quirk for `safe_device` to run differently and not cause any collisions with `geolocator`.

Thank you @martin-braun , yeah as you said removing safe_device fixed the problem.

**Comment by JeroenWeener** [comment] 2023-08-16 12:48
Hi @martin-braun and @Soli1065, thank you for the replies.

I have run the application in release mode now, both from Android Studio and from the command line (`flutter run --release`). However, I have not been able to reproduce the behavior you are describing. Could you confirm that you are seeing the same behavior by creating a Flutter application from scratch? Preferably, you can follow the steps I outlined earlier. There might still be a hidden configuration in your application that is influencing the behavior.

@martin-braun can you confirm whether this is specific to your Lenovo device? I have run the app on an emulator running Android API versions 29 and 33, and a Nexus 5X device running API version 26.
@Soli1065 could you tell me which hardware and OS version you are using?

**Comment by izzabellerina** [comment] 2023-08-17 11:04
I have faced this problem without using safe_device do you guys have any suggestions for me, Thank you

**Comment by JeroenWeener** [comment] 2023-08-17 11:06
Hi @izzabellerina, can you provide us with a minimal reproducible code sample that showcases your issue? We are also interested in the output of `flutter doctor -v`, and which Android version you are running. Are you experiencing this on multiple devices?

**Comment by izzabellerina** [comment] 2023-08-17 11:31
@JeroenWeener  this is my flutter doctor
```
/Users/pnall02/flutter/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/pnall02/flutter
    ! The flutter binary is not on your path. Consider adding /Users/pnall02/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/pnall02/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/pnall02/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM T295 (mobile) • R9WM80K2QKJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by JeroenWeener** [comment] 2023-08-17 12:02
@izzabellerina thank you for supplying the information. Can you include a video of what you are experiencing? It is not clear to me yet how your issue compares to the one reported by the OP.

**Comment by martin-braun** [comment] 2023-08-17 18:37
> @martin-braun can you confirm whether this is specific to your Lenovo device? I have run the app on an emulator running Android API versions 29 and 33, and a Nexus 5X device running API version 26. @Soli1065 could you tell me which hardware and OS version you are using?

@JeroenWeener Multiple devices are affected.

> However, I have not been able to reproduce the behavior you are describing. Could you confirm that you are seeing the same behavior by creating a Flutter application from scratch?

My time is very limited right now, I will try to look into that later, but in the meantime, here is the project (stripped down and hopefully still working): https://psitransfer.biz.martin-braun.net/046cba7cd536 (Password is your organization name)

While archiving, I noticed there are still left overs from the past packages, so it still could be a false positive. I still want to blame `safe_device` for it, but if you feel motivated, please check it out.

**Comment by JeroenWeener** [comment] 2023-08-29 09:41
I am going to close this issue as the problem seems to be caused by `safe_device` and not by `geolocator`. We have been unable to reproduce the mentioned issues from a fresh project. You can report and read about the issue at the [`safe_device` repository](https://github.com/ufukhawk/safe_device/issues/33).

**Closed by JeroenWeener** 2023-08-29 09:41 UTC
Labels: platform: android, type: question, P2

**Comment by martin-braun** [comment] 2023-08-29 17:56
@JeroenWeener That might be reasonable. Sorry I'm too busy to investigate further, but my research has shown that `safe_device` didn't just collide with `geolocator`, but also with `cached_network_image` as stated earlier. I think it is safe to assume that this package is at fault, and not `geolocator`.

**Comment by JeroenWeener** [comment] 2023-08-30 08:24
No worries @martin-braun. Thank you for contributing to the issue and helping us investigate ;)
