### ISSUE TITLE
[Bug]: the operation couldn’t be completed. (kCLErrorDomain error 1.)

### ISSUE THREAD

**Issue by andreastambazzi** [Baseflow/flutter-geolocator#1452] opened 2024-03-07 17:34 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

I having the same issue "the operation couldn’t be completed. (kCLErrorDomain error 1.)" 
on IOS 17.3.1 iphone 12

( Same app on android 11 is working fine .... )

i'm referring to the already sendend but closed bug :
https://github.com/Baseflow/flutter-geolocator/issues/1111

## pubspec.yaml :
  geolocator: ^11.0.0

## info.plist
```
<dict>
		<key>NSLocationWhenInUseUsageDescription</key>
		<string>This app needs access to location when open.</string>
		<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
		<string>This app needs access to location information while running in the background.</string>
		<key>NSLocationTemporaryUsageDescriptionDictionary</key>
		<dict>
```

## podfile

```
post_install do |installer|
  installer.pods_project.targets.each do |target|    
    
    if target.name == "geolocator_apple"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'BYPASS_PERMISSION_LOCATION_ALWAYS=1']
      end
    end

    flutter_additional_ios_build_settings(target)

  end
end

```

## src code:

 ```

locationAccurancy = LocationAccuracy.high;
distanceFilter    = 5;
intervalDuration  = Duration(seconds: 5);


locationSettings = AppleSettings(
    accuracy: locationAccurancy,        
    activityType: ActivityType.fitness,
    distanceFilter: distanceFilter,
    pauseLocationUpdatesAutomatically: true,
    // timeLimit: intervalDuration,
    // Only set to true if our app will be started up in the background.
    showBackgroundLocationIndicator: false,        
  );

positionStream = Geolocator
      .getPositionStream(locationSettings: locationSettings)
      .listen( (Position? position) {

        try {
          if ( position == null ) {
            logger.info("getPositionStream: null");     
          }
          else {
            logger.info("getPositionStream: ${position.latitude.toString()}, ${position.longitude.toString()} ${position.altitude.toStringAsFixed(2)}");
          }
          
          if ( onPositionChange != null ) {
            onPositionChange(position);
          }
        }
        catch(error) {
          logger.error("getPositionStream listen $error");
        }

      },
      onError: (error) {
        logger.error("LISTEN: $error");
      }
      );
```

### Expected results

getPositionStream:  [LAT], [LONG] [ALTITUDE]

### Actual results

the operation couldn’t be completed. (kCLErrorDomain error 1.)

### Code sample

<details><summary>Code sample</summary>

```dart
locationAccurancy = LocationAccuracy.high;
distanceFilter    = 5;
intervalDuration  = Duration(seconds: 5);


locationSettings = AppleSettings(
    accuracy: locationAccurancy,        
    activityType: ActivityType.fitness,
    distanceFilter: distanceFilter,
    pauseLocationUpdatesAutomatically: true,
    // timeLimit: intervalDuration,
    // Only set to true if our app will be started up in the background.
    showBackgroundLocationIndicator: false,        
  );

positionStream = Geolocator
      .getPositionStream(locationSettings: locationSettings)
      .listen( (Position? position) {

        try {
          if ( position == null ) {
            logger.info("getPositionStream: null");     
          }
          else {
            logger.info("getPositionStream: ${position.latitude.toString()}, ${position.longitude.toString()} ${position.altitude.toStringAsFixed(2)}");
          }
          
          if ( onPositionChange != null ) {
            onPositionChange(position);
          }
        }
        catch(error) {
          logger.error("getPositionStream listen $error");
        }

      },
      onError: (error) {
        logger.error("LISTEN: $error");
      }
      );
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
andreastambazzi@Logos ~/work/Projects/flutter/yourate $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 13.6.5 22G621 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment] 2024-03-11 09:22
Hi @andreastambazzi,

According to the iOS documentation, the `kCLErrorDomain error 1` occurs when the app is requesting position updates while the location services on the phone are disabled. 

Please verify if the location services are enabled by checking the iOS configuration: Settings > Privacy > Location Services > Your App.

The geolocator plugin also supports checking if the location services are enabled using the `isLocationServiceEnabled()` method:

```dart
  // Test if location services are enabled.
  bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
  if (!serviceEnabled) {
    // Location services are not enabled don't continue
    // accessing the position and request users of the 
    // App to enable the location services.
    return Future.error('Location services are disabled.');
  }
```

Please let us know it this helps to resolve the issue.

**Comment by andreastambazzi** [comment] 2024-03-11 10:29
Thank you i have solved te issue.

I had already activate the keys in **info.plist**

```
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>Always and when in use!</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>Can I have location always?</string>
<key>NSLocationUsageDescription</key>
<string>Older devices need location.</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Need location when in use</string>
```

But was not sufficent

i had also modified  Podfile as following

`installer.pods_project.targets.each do |target|            
    target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)',

        ## dart: [PermissionGroup.calendarWriteOnly, PermissionGroup.calendar (iOS 16 and below)]
        # 'PERMISSION_EVENTS=1',
   
        ## dart: [PermissionGroup.calendarFullAccess, PermissionGroup.calendar (iOS 17 and above)]
        # 'PERMISSION_EVENTS_FULL_ACCESS=1',
  
        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=1',

        ## dart: PermissionGroup.photosAddOnly
        # 'PERMISSION_PHOTOS_ADD_ONLY=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth
        'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        # 'PERMISSION_CRITICAL_ALERTS=1'
                    
      ]
    end
`


and in the flutter source code 

```
WidgetsFlutterBinding.ensureInitialized();
PermissionStatus requestPermission = await Permission.location.request(); 

```

To raise system request permission to use te location

**Comment by mvanbeusekom** [comment] 2024-03-11 12:59
Hi @andreastambazzi,

Thank you for getting back to us and good to hear you managed to resolve the issue. Note that if you only require location permissions there is no need to use the permission_handler plugin. 

The geolocation has build in support for checking and requesting permissions using the `checkPermission` and `requestPermission` methods. Of course you are free to use the permission_handler plugin as well.

I will close the issue now. Feel free to open another issue in case you run into another issue.

**Closed by mvanbeusekom** 2024-03-11 12:59 UTC
Labels: platform: ios

**Comment by andreastambazzi** [comment] 2024-03-11 13:47
Thank you a question then about , the build in support for checking and requesting permissions that you mentioning.
What happen if a user remove permission when the app is running? 
Geologator plugin is able to know it and pop up again to the user a requet of permission?

**Comment by mvanbeusekom** [comment] 2024-03-11 13:54
No the geolocator doesn't know, if you are listening to the position stream it will return an error. The idea is that when you handle the error, you'll check if:

- Location services are enabled using the `isLocationServiceEnabled()` method, if not prompt the user to enable the location services.
- Permissions are granted using the `checkPermission()` method, if not prompt the user to grant permission as retracted permissions are always permanent and can't be requested again. Meaning the user needs to explicitly provide permissions.

**Comment by andreastambazzi** [comment] 2024-03-11 13:56
Ok thank you.

**Comment by andreastambazzi** [comment] 2024-03-18 17:42
Now i receive the position only one time, but unfortunatly the stream function don't  refresh te position after that.
Same code on android platform is working fine.

**Comment by mvanbeusekom** [comment] 2024-03-19 08:54
Hi @andreastambazzi,

It is very well possible that this is caused by the `pauseLocationUpdatesAutomatically` setting that is set to `true`. According to [Apple's documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620553-pauseslocationupdatesautomatical?language=objc):

> Allowing the location manager to pause updates can improve battery life on the target device without sacrificing location data. Setting this property to YES causes the location manager to pause updates (and powers down the appropriate hardware) at times when the location data is unlikely to change. For example, if the user stops for food while using a navigation app, the location manager might pause updates for a period of time.

Try setting this to `false` or make sure to move (outside) while testing with the application.

**Comment by andreastambazzi** [comment] 2024-03-19 08:56
Unfortunatly no, this is Settings for ios:

locationSettings = AppleSettings(
        accuracy: locationAccurancy,        
        activityType: ActivityType.fitness,
        distanceFilter: distanceFilter,
        pauseLocationUpdatesAutomatically: false,
        timeLimit: intervalDuration,
        showBackgroundLocationIndicator: false,        
      );

**Comment by andreastambazzi** [comment] 2024-03-19 14:59
The issue appear to happen when listen.onError  event is raised.
If the listen method raise a error for a timeout, since that moment the streamer stop to stream and to raise updates.
I've tryed to check 

```
if ( positionStream.isPaused ) {
     positionStream.resume();
}
```

but  whithout results.

On android os it behave different, even if event onError is raised the streamer still working fine.

There's  a solution? Do i have to call a method to convince the streamer to continue it's work? 
Or a fix is needed?

I hope you have a solution.

Thanks.
