### ISSUE TITLE
Geolocator.getPositionStream listener gets updates even the device is not moved in iOS 

### ISSUE THREAD

**Issue by lahirunc** [Baseflow/flutter-geolocator#1167] opened 2022-11-07 23:10 UTC
Sorry if i'm spamming but I'm stuck at this point because of this issue (https://github.com/Baseflow/flutter-geolocator/issues/1166) which was closed prematurely.

**Version:** 9.0.2

**Platform:** 
- [x] :iphone: iOS (16.0.2)
- [ ] :robot: Android

This was working fine in `9.0.1` 

`Geolocator.getPositionStream` listener gets updates even the device is not moved.

` positionStream =
        Geolocator.getPositionStream(locationSettings: locationSettings)
            .listen((Position? position) async {
      print('loc updated - Listener ${position!.latitude},${position.longitude}');

    // db update
    locationUpdate();
    });

  // location settings
  locationSettings = LocationSettings(
      accuracy: LocationAccuracy.best,
      distanceFilter: 150,
    );`

`

`locationSettings = LocationSettings(
      accuracy: LocationAccuracy.medium,
      distanceFilter: 3000,
    );`

I have done testing using the above values but still keeps getting min. 2 events per second without moving the device and location coordinates are not changed at all. 

Log:
`
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:34.872962

flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:35.293022

flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:44.868808

flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:45.297299
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:56.882748
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:31:57.265405
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:08.868998
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:09.300702
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:20.873127
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:21.302089
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:32.870515
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:33.287268
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:44.873644
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:45.288866
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:56.877972
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:32:57.292501
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:08.868705
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:09.310313
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:20.872610
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:21.313127
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:32.884367
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:33.299903
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:44.866601
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:45.297741
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:56.866522
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:33:57.301312
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:08.868129
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:09.304218
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:21.105941
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:21.537021
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:33.105818
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:33.537314
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:45.104649
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:45.537610
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:57.105693
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:34:57.558832
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:09.106221
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:09.539196
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:21.107288
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:21.539784
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:33.108620
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:33.526489
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:45.108613
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:45.525653
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:57.104477
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:35:57.543816
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:05.552393
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:06.003233
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:17.101321
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:17.535359
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:29.104869
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:29.536550
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:41.104665
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:41.522224
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:53.105385
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:36:53.543174
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:05.107766
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:05.541774
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:17.342671
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:17.777869
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:29.345322
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:29.778564
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:41.346412
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:41.781581
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:53.348604
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:37:53.783083
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:05.350862
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:05.784218
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:17.345966
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:17.768222
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:29.340604
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:29.770324
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:41.341143
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:41.773274
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:53.341882
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:38:53.762601
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:05.344332
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:05.776251
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:17.346257
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:17.770250
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:29.348436
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:29.781205
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:41.338467
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:41.751623
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:53.353053
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:39:53.785306
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:05.338475
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:05.771446
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:17.574148
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:18.005554
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:29.578209
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:30.024683
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:41.577383
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:42.008821
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:53.578419
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:40:54.012759
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:41:05.566870
flutter: loc updated - Listner -37.88389210390433,145.05493616153728
flutter: loc updated @2022-11-04 17:41:05.996963

`

**Comment by mvanbeusekom** [comment] 2022-11-08 07:14
Duplicate of #1166, which I will re-open.

**Closed** 2022-11-08 07:15 UTC
