### ISSUE TITLE
Window demo crash in Win7

### ISSUE THREAD

**Issue by nikohpng** [Baseflow/flutter-geolocator#1168] opened 2022-11-08 05:35 UTC
### Expected behavior

Window demo crash in Win7

### Reproduction steps

I make a debug pacakge to run it

**Version:** 9.0.2

**Platform:** 
- [ ] 🪟 : Windows

**Comment by TimHoogstrate** [comment] 2023-06-12 11:15
Closing issue due to lack of reproducible steps. Feel free to reopen with additional information. Thank you for your understanding.

**Closed by TimHoogstrate** 2023-06-12 11:15 UTC
