### ISSUE TITLE
placemarkFromCoordinates takes forever (=1-2 minutes)

### ISSUE THREAD

**Issue by mikron123** [Baseflow/flutter-geolocator#391] opened 2020-02-13 10:54 UTC
I'm using the latest Flutter SDK 1.12.13+hotfix.8. Code is waiting more than 1 minute for 
placemarkFromCoordinates(n,z) to return a reuslt (!)

Any advice about why is it so slow?
It delays the whole app initializing..

**Comment by mvanbeusekom** [comment] 2020-02-14 14:31
Hi @mikron123, thank you for reporting this issue. Could you provide us with some additional information:

- Which platform (iOS, Android or both) are you experiencing this issue?
- Which version of the plugin are you using?
- Do you have some example code (or even better an example App) which we can use to  reproduce this issue?

**Comment by mikron123** [comment] 2020-02-17 12:21
Platform: Android
Plugin: Latest for now - ^5.2.1
I'm not sure it happens on all devices, for my Galaxy S7 it does.. maybe it's more of an OS thing? Android 8.0.

Here is the code, pretty straight forward.. the GPS point return pretty quickly, then it gets stuck on the 
placemarkFromCoordinates call. can be even 1 minute. resulting of course in user frustration.

`Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
List<Placemark> pMarks = await Geolocator().placemarkFromCoordinates(position.latitude, position.longitude);`

Thanks!!

**Comment by mikron123** [comment] 2020-03-01 09:34
Update: It looks like it only happen on the first activation of the app for some reason...

**Comment by habilgur** [comment] 2020-03-16 19:38
@mikron123
"Update: It looks like it only happen on the first activation of the app for some reason..."
I have same trouble like you when at my app first openning, fetching data (get current location,placemark and some data download from api..)  takes approx. 20-27 seconds however after that when i call it again it takes only 1 or 2 seconds.. When i use a fake location application for mocking location there is  no problem but when i turn off fake gps and  resume back to my app and call getcurrent location functions it takes again 20-27 seconds. I dont know what is the problem?

**Comment by mvanbeusekom** [comment] 2020-09-03 15:42
This issue should be resolved in version 6.0.0. Note that the geocoding functionality has been moved to its own plugin called [geocoding](https://pub.dev/packages/geocoding)

**Closed by mvanbeusekom** 2020-09-03 15:42 UTC
Labels: status: needs more info
