### ISSUE TITLE
geolocator.getCurrentPosition take a long time to return position on IOS

### ISSUE THREAD

**Issue by hungtran2492** [Baseflow/flutter-geolocator#320] opened 2019-08-30 02:56 UTC
getCurrentPosition is working really fine on Android, but on IOS it took so much time to execute. Can you check it? Thank you
**Platform:** 
- [ x] :iphone: iOS
- [ ] :robot: Android

**Comment by mrmko** [comment] 2019-09-01 21:28
Experiencing same issue. Not found what's causing the slowdown so far but using Last Known Position as temporary work around for my case...

**Comment by paulobreim** [comment] 2019-09-08 22:47
check if your Info.plist have 3 keys
<key>NSLocationAlwaysUsageDescription</key>
<string>your description</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>your description</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>your description</string>

**Comment by babaosoftware** [comment] 2019-09-21 00:06
Same problem here. Had to downgrade to 4.0.3 version. Every version after that is very slow to respond in iOS, on the initial install of the app. If shut down the app and restart, it's fine.
And yes, @paulobreim I have all the required strings in Info.plist, otherwise it would not respond at all.

**Comment by ollydixon** [comment] 2019-09-27 08:42
Using `desiredAccuracy: LocationAccuracy.high` is very slow, sometimes more than 9 seconds, desiredAccuracy: `LocationAccuracy.medium` seems fast. 

Is there an option to just use last location?

**Comment by hungtran2492** [comment] 2019-09-28 00:27
I use Location plugin for getting the current location. It works fine on both Android and IOS.

**Comment by ollydixon** [comment] 2019-10-01 14:44
@hungtran2492 I'm also using Location plugin, it's much faster than this.

@StijnWoerkom what's the reason for closing? This is a legitimate bug that is causing developers issues on the main locational library for Flutter.

**Comment by StijnWoerkom** [comment] 2019-10-01 14:54
@ollydixon I tested this issue on multiple IOS devices and concluded that the problem was more with the device than with the code. I can re-open the issue, but I don't see any trouble occurring with this issue.

**Comment by ollydixon** [comment] 2019-10-01 14:56
@StijnWoerkom if it helps I did a live app demo with 4 users and it was slow on all their mobiles. (All iOS). Was a little embarrising for me cause the simulator works fine it's only on the device it's extremely slow.

I used another library and it was fine (Location for Flutter).

**Comment by babaosoftware** [comment] 2019-10-01 14:57
Version 4.0.3 works just fine. I actually downgraded to that version on my app. So it's got to be something in the library itself. Did tests with different iPhones, it's consistent, so I doubt it's the device.

**Comment by StijnWoerkom** [comment] 2019-10-01 15:00
@ollydixon Thank you for your response. I'm sorry for your failure with the demo. I re-opened the issue and will look further into this. Can you tell me what version you were using?

**Comment by babaosoftware** [comment] 2019-10-01 15:06
Any version after 4.0.3 has the problem. So it must be something introduced in 5.0.0.

**Comment by StijnWoerkom** [comment] 2019-10-02 07:29
@babaosoftware In the 5.0.0 version, we converted the IOS version from Swift to Objective-C, reducing the size of the final binary considerably, as well as solve some compatibility issues with other objective-c based plugins.

**Comment by babaosoftware** [comment] 2019-10-02 11:00
@StijnWoerkom I am not questioning the necessity of the conversion, just saying that it created this problem, and giving a hint to where someone might start looking into it.

**Comment by StijnWoerkom** [comment] 2019-10-02 11:08
I noticed that you told me yesterday that the problems started with version 5.0.0. I am looking into all the features we added with the version to determine what the cause of the issue is.

**Comment by paulobreim** [comment] 2019-10-02 16:19
Let me suggest an alternative to isolating the problem, if it really exists.
We can make a small program with the geolocator.getCurrentPosition function only, and everyone can test this program and measure the time it executes.
what do you think?

**Comment by babaosoftware** [comment] 2019-10-02 17:55
@paulobreim I was going to do exactly that tonight (USA Eastern time). I will post my result as soon as I will have them.

**Comment by babaosoftware** [comment] 2019-10-03 02:21
I did the following test:
The app:
import 'package:flutter/foundation.dart';
import 'package:geolocator/geolocator.dart';
void main(){
  DateTime start = DateTime.now();
  getCurrentPosition().then((pos){
    DateTime end = DateTime.now();
    debugPrint("time span = ${end.difference(start).inMilliseconds} ms");
  });
}
Future<Position> getCurrentPosition() async {
    return await Geolocator().getCurrentPosition();
}

in pubspec.yaml I have 
geolocator: ^4.0.3 # Don't upgrade - it's very slow to respond on startup.
for the first test, and
  geolocator: ^5.1.4
for the second test.
I tested using an iPhone 6S, but before I used newer devices too, so I don't think the device makes a difference.
The first test, with version 4.0.3 showed a response time of about 100ms
The second test, with version 5.1.4. showed a response time of about 10 s - that is seconds, not ms
There you go.

**Comment by paulobreim** [comment] 2019-10-04 22:18
I am trying to test it in my Motorola Z2 Play and an iPhone, but I got the error below and don know what to do.

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution

I know there are no relations with geolocator, but i don know to fix it.

**Comment by babaosoftware** [comment] 2019-10-05 00:05
> 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.2) classpath

Check this:
https://github.com/flutter/flutter/issues/27254

**Comment by paulobreim** [comment] 2019-10-05 03:50
Here is my test for Android.
I put a floatingActionButton and pressed 10 times

FIRST TEST geolocator: ^4.0.3
Launching lib/main.dart on Moto Z2 Play in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Moto Z2 Play...
I/flutter (11197): time span = 1006 ms
I/flutter (11197): time span = 1626 ms
I/flutter (11197): time span = 965 ms
I/flutter (11197): time span = 6024 ms
I/flutter (11197): time span = 991 ms
I/flutter (11197): time span = 971 ms
I/flutter (11197): time span = 6022 ms
I/zygote  (11197): Do partial code cache collection, code=62KB, data=51KB
I/zygote  (11197): After code cache collection, code=62KB, data=51KB
I/zygote  (11197): Increasing code cache capacity to 256KB
I/flutter (11197): time span = 7866 ms
I/flutter (11197): time span = 940 ms
I/flutter (11197): time span = 6091 ms

SECOND TEST geolocator: ^5.1.4
Launching lib/main.dart on Moto Z2 Play in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Moto Z2 Play...
I/flutter (11471): time span = 1043 ms
I/flutter (11471): time span = 5927 ms
I/flutter (11471): time span = 8876 ms
I/flutter (11471): time span = 1052 ms
I/flutter (11471): time span = 5987 ms
I/flutter (11471): time span = 6316 ms
I/flutter (11471): time span = 5948 ms
I/zygote  (11471): Do partial code cache collection, code=62KB, data=50KB
I/zygote  (11471): After code cache collection, code=62KB, data=50KB
I/zygote  (11471): Increasing code cache capacity to 256KB
I/flutter (11471): time span = 934 ms
I/flutter (11471): time span = 6012 ms
I/flutter (11471): time span = 954 ms

THIRD TEST geolocator: ^5.1.4
(WHITOUT await in geolocator pressing button 10 times quick
Launching lib/main.dart on Moto Z2 Play in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Moto Z2 Play...
I/flutter (16122): time span = 1020 ms
I/flutter (16122): time span = 159 ms
I/flutter (16122): time span = 584 ms
I/flutter (16122): time span = 544 ms
I/flutter (16122): time span = 99 ms
I/flutter (16122): time span = 536 ms
I/flutter (16122): time span = 82 ms
I/zygote  (16122): Do partial code cache collection, code=62KB, data=50KB
I/zygote  (16122): After code cache collection, code=62KB, data=50KB
I/zygote  (16122): Increasing code cache capacity to 256KB
I/flutter (16122): time span = 504 ms
I/flutter (16122): time span = 1381 ms
I/flutter (16122): time span = 946 ms

**Comment by babaosoftware** [comment] 2019-10-05 12:56
While I didn't check the problem on Android myself, as the title states, this issue was opened for iOS. Nonetheless, your tests show pretty inconsistent results, and I'm not sure what the third test does without await on the geolocator call. Maybe  posting your app's code would clarify that.
In any case, I'm staying with the version 4.0.3 of the library for now. As a matter of fact I released my app on the apple store just recently. You might want to check it out at
http://apps.apple.com/us/app/apple-store/id1469322424

**Comment by paulobreim** [comment] 2019-10-05 23:49
Here is my test for IOS 12.4.4 iPhone 6 

FIRST TEST geolocator: ^4.0.3
Launching lib/main.dart on iPhone PCB in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Paulo Breim (Y34R2HBJ59)"
Running pod install...
Running Xcode build...
Xcode build done.                                           23,7s
Installing and launching...
Syncing files to device iPhone PCB...
flutter: time span = 230 ms
flutter: time span = 92 ms
flutter: time span = 74 ms
flutter: time span = 80 ms
flutter: time span = 95 ms
flutter: time span = 87 ms
flutter: time span = 199 ms
flutter: time span = 58 ms
flutter: time span = 73 ms
flutter: time span = 70 ms

SECOND TEST geolocator: ^5.1.4
Launching lib/main.dart on iPhone PCB in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Paulo Breim (Y34R2HBJ59)"
Running pod install...
Running Xcode build...
Xcode build done.                                           22,6s
Installing and launching...
Syncing files to device iPhone PCB...
flutter: time span = 12383 ms
flutter: time span = 10033 ms
flutter: time span = 10027 ms
flutter: time span = 10026 ms
flutter: time span = 10031 ms
flutter: time span = 10029 ms
flutter: time span = 10032 ms
flutter: time span = 10032 ms
flutter: time span = 10028 ms
flutter: time span = 10029 ms

babaosoftware, let me know if you need more tests

**Comment by babaosoftware** [comment] 2019-10-06 01:02
@paulobreim thanks for your effort. Apparently confirms what we've been saying all along, and the results are consistent. Versions of geolocator library, starting with 5.0.0 have an unacceptable response time of about 10 seconds for calls to getCurrentPosition on iOS platform.
The results on Android are inconsistent, but some show response times of over 8 seconds, which is also worrisome.
@StijnWoerkom I think there's enough evidence that something is very wrong with the library upgrade and requires some effort to isolate and fix.

**Comment by StijnWoerkom** [comment] 2019-10-07 07:52
@babaosoftware Thank you for your effort. I tested the same issue and got to the same conclusion as you did. We will work on this issue and keep you posted when there is a solution to this issue.

**Comment by jpv123** [comment] 2019-11-07 15:37
Same happening here on iOS 13.1.3 iPhone XR with latest version of GeoLocator. It takes between 8-10 seconds to get current position

**Comment by cielo** [comment] 2019-12-15 04:26
For those of you who have trouble with slow `getPosition` in iOS (e.g. takes 10+s to get position information), you can use this alternative package as it has been said before in the earlier thread. 

https://github.com/Lyokone/flutterlocation

It loads position information extremely fast both in Android as well as in iOS. (<1s).

**Comment by mike2096** [comment] 2019-12-18 12:53
I'm experiencing the same lag using the latest version. Are there any issues/down sides with sticking with version 4.0.3?

**Comment by OsaXma** [comment] 2020-01-15 01:36
I agree with @cielo, I tested this package and the location package [[link](https://pub.dev/packages/location)] and the difference in speed is apparent. Though, this package offers more features and I hope this bug in delay gets fixed (for me it's inconsistent).

**Comment by davidkohcw** [comment] 2020-01-27 16:04
I just want to add in that I'm still experiencing this slowness too. Works fine on the emulator, but takes more than 10 seconds on Physical Iphone 8 Plus device.

**Comment by valkot** [comment] 2020-01-27 17:09
effectively version 4.0.3 works great. My experience in physical ios devices, with version 5.2.0, was very delayed in locating the location of the device, by lowering it to 4.0.3 the problem of solving

**Comment by billymahmood** [comment] 2020-01-31 17:20
Hi, I am having this issue on Android 

my code is as simple as.  `position = await _geoLocator.getCurrentPosition();`

**Comment by taz1208** [comment] 2020-02-05 02:37
me too :( 
i'm using ^5.1.5
getCurrentPosition() so slow both Android, IOS

**Comment by rafaelcorbellini-egsys** [comment] 2020-03-04 20:51
some update?

**Comment by Gperez88** [comment] 2020-03-07 19:10
me too
iam using ^5.3.0
IOS 12.4 Iphone 5s.

**Comment by bagus-repository** [comment] 2020-03-18 09:24
I have same problem, on iOS 13.4 beta iPhone XR
Works fine on any android OS devices.

**Comment by hasanzia1993** [comment] 2020-03-19 20:56
same issue still, works fine on the virtual device but 10 sec delay on physical device

**Comment by flocbit** [comment] 2020-03-26 15:55
Experiencing the same issue on my iPhone 7, iOS 13.4

**Comment by racacere** [comment] 2020-03-27 15:03
Same issue in iPhone 7 and IPhone X, IOS 13

**Comment by demetrio812** [comment] 2020-03-31 13:23
Hello, same issue in a real iPhone X device, iOS 13

Our startup time was 10+ seconds because of this issue, going back to 4.0.3 works

**Comment by tomwyr** [comment] 2020-04-09 13:08
Same here, iPhone 5s iOS 12.4.

**Comment by RicardoRB** [comment] 2020-04-14 19:31
Also in iPhone 6s iOS 13.4

**Comment by sam-parks** [comment] 2020-04-15 22:38
I'm experiencing this issue as well. iPhone 6s iOS 13.4

**Comment by rodriigovieira** [comment] 2020-05-11 17:52
Same problem on a physical device, iPhone 8 iOS 13.4. `getLastKnownLocation` works fine.

**Comment by JayPerfetto** [comment] 2020-05-14 08:01
+1

**Comment by digocse** [comment] 2020-05-15 23:21
Same here using `^5.3.1` Geolocator's version on iPhone Xs and iOS 13.3. I've downgraded it to `4.0.3` and its very fast! 🚀

**Comment by edwin-alvarez** [comment] 2020-05-27 03:13
Having same slowly results, in the IOS simulator it works like a charm, then I tried on real phone an takes about 10 seconds on every different address, I walked around few houses and the first time is always slow, if you retry then it loads fast.

**Comment by edwin-alvarez** [comment] 2020-05-27 20:05
I also tried 4.0.3 and is working fine, but I see many fixes from 4.0.3 to ^5.3.1. any plan to fix this up in the main branch?

I noticed 4.0.3 is not as accurate as 5.3.1

**Comment by RafiqCR7** [comment] 2020-06-01 14:22
I also had this same issue. Downgrading to 4.0.3 resolved the issue for me. It worked fine on the ios simulator but was taking an age on my physical ios device (iPhone SE 2nd Gen).

How has this issue not gained more traction? Surely this is a production level plugin breaking issue. It simply can't be used in a live environment past v4.0.3.

**Comment by nincode** [comment] 2020-06-01 20:15
Reproes here as well, iPhone 8. 
First acquisition is 20+ seconds on actual hardware on 5.3.1.
Same hardware, same location, first acquisition is ~2 secs on 4.0.3.

**Comment by valkot** [comment] 2020-06-04 20:52
> Having same slowly results, in the IOS simulator it works like a charm, then I tried on real phone an takes about 10 seconds on every different address, I walked around few houses and the first time is always slow, if you retry then it loads fast.

Guy I have used 4.0.3 version for best result in simulator and device iOS (iPhone 6s - 8)

**Comment by ekuprel** [comment] 2020-06-08 19:48
I have same issue and moving to 4.0.3 was not simple because I would have to back-down versions and I have already upgraded to Androidx.  I used the flutter location plugin instead, much faster.

**Comment by Nathan-Heller** [comment] 2020-06-12 20:30
Similar to what other folks are saying, I'm seeing ~10 second (almost on the dot) delays on a physical iOS device, but none in the simulator. This slowdown was seen on multiple devices across my team.

Is there any intention to implement a fix for newer versions?

**Comment by carlosgibarra82** [comment] 2020-06-18 04:07
could you try to change the accuracy? this one worked for me:
await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.medium)

**Comment by bidy** [comment] 2020-06-21 12:46
await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.medium)
worked for me.

**Comment by cvovan** [comment] 2020-06-24 05:59
I was at 5.3.2+2 and noted that this plugin was much slower than the location plugin. Based on the recommendation here, I downgraded to 4.0.3 and the speed was much improved.

**Comment by darbyo** [comment] 2020-07-21 23:56
Also had the same problem as above, when running in Simulator v11.5 on mac.

The location of the Simulator IOS device is not set by default which causes the exception, this can be set by clicking in the top menu bar

Features -> Location -> *Select an option* 

I used custom location which gives San Francisco Long/Lat

**Comment by andrewescutia** [comment] 2020-07-27 17:22
also had to downgrade to 4.03 due to the performance on actual iOS devices.

**Comment by bartekpacia** [comment] 2020-07-28 09:25
Same here, extremely slow.

**Comment by elizv** [comment] 2020-07-31 16:54
I had the same problem using version 5.3.1.
It took about 10 seconds to get the location on almost any version of iPhone, iPad.
Changing the LocationAccuracy (from best to medium), seems to solve the problem.

**Comment by dqr79** [comment] 2020-08-07 00:11
same here, tested on multiple iPhones from 6S and upwards, version 5.3.2 - takes 5-10 secs to get the location

**Comment by abdullahmaswadeh** [comment] 2020-08-11 14:33
Same here iPhone 8 takes 5 seconds to determine location

**Comment by elizv** [comment] 2020-08-11 14:38
Maybe my solution was hidden in the text:
When I changed the LocationAccuracy (from best to medium), , shorten the delay for less than a second, and on sometimes the response was instantaneous (at least on all the machines that I tested it).
Please note, that LocationAccuracy  of "good" was not good enough.

**Comment by samyakkkk** [comment] 2020-08-13 17:20
It is taking upto 100sec (seconds) on my iPhoneSE to get current Position. Sometime it takes less than a second and the next time it takes upto 100. I also tried to use the Location package but the same issue persisted. I cannot downgrade to 4.0.4 as another package I am using depends on the higher versions. :(

**Comment by mvanbeusekom** [comment] 2020-08-15 08:28
We are working hard on a new release which should solve these issues. See also issue #430 with more details on it progress.

**Comment by ssiphiwo** [comment] 2020-08-16 19:26
recently had this issue using geolocator: ^5.3.1
to fix I upgraded to  geolocator: ^5.3.2+2
set :
compileSdkVersion 28

and eventually did 
flutter upgrade

that seems to have fixed the issue.

**Closed** 2020-08-31 09:30 UTC
Labels: platform: ios, type: bug, type: duplicate

**Comment by mannnish** [comment] 2020-09-08 03:31
> 
> 
> await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.medium)
> worked for me.
Geolocator() class is now deprecated in the latest release of ^6.0.0, how am i supposed to use PlaceMarker

**Comment by mvanbeusekom** [comment] 2020-09-08 05:08
@mannnish, the geocoding functionality has been moved to its own (dedicated) plugin called [geocoding](https://pub.dev/packages/geocoding).

**Comment by mannnish** [comment] 2020-09-08 05:09
> @mannnish, the geocoding functionality has been moved to its own (dedicated) plugin called [geocoding](https://pub.dev/packages/geocoding).


Thanks worked

**Comment by fluttercorner** [comment] 2020-10-08 18:09
[How to Get Device Lat Long in Flutter](https://fluttercorner.com/how-to-get-device-lat-long-in-flutter/)

**Comment by pumuckelo** [comment] 2021-01-18 21:01
I updated to the newest version, fixed the problem for me 👍👍👍

**Comment by TenPetr** [comment] 2021-01-19 07:59
> I updated to the newest version, fixed the problem for me 👍👍👍

Indeed, upgrading to the `^6.1.14` helped me too.

**Comment by thedrivingforc** [comment] 2021-01-23 13:45
> > I updated to the newest version, fixed the problem for me 👍👍👍
> 
> Indeed, upgrading to the `^6.1.14` helped me too.

its not working for me .................do tell steps i need to follow

**Comment by pumuckelo** [comment] 2021-01-24 14:01
> > > I updated to the newest version, fixed the problem for me 👍👍👍
> > 
> > 
> > Indeed, upgrading to the `^6.1.14` helped me too.
> 
> its not working for me .................do tell steps i need to follow

hm, I just updated my pubspec.yaml, maybe you also need to delete pubpec.lock?

**Comment by pumuckelo** [comment] 2021-04-08 19:02
Now its slow again lol (at least on web)

**Comment by AhmedKhattab95** [comment] 2021-05-18 13:05
should be re-opened using version 5.3.2+2

**Comment by thedang** [comment] 2021-06-24 16:39
Anyone have idea for issue ?

The first time around 7-10s,
the next time, about 3-5s.
But sometimes jump to 7-10s for the next time.

i used version 7.1.1 and LocationAccuracy = best.

**Comment by ekuprel** [comment] 2021-06-24 17:46
If you are not able to find a solution you may want to consider using the flutter location plugin.  I was able to refactor to the flutter location plugin in less than a day.  https://pub.dev/packages/location

**Comment by michaelsof47** [comment] 2021-08-30 12:16
anyone know it when i make by geolocator : ^7.4.0. it slown to get location after install an apps. it makes duration until 16 seconds to get location with setting .high. but in emulator, i got location only 3-5 second. anyone know else?

**Comment by mvanbeusekom** [comment] 2021-08-30 12:21
@michaelsof47, today we have updated the geolocator (to version 7.6.0) to include a bug fix with the `getCurrentPosition` method. 

In the past this method contained a bug which caused the method to return a cached location (which most of the times is not the real location). After the bug fix it will retrieve the real location however the first time this might take several seconds since the device needs to connect with the different available location services (network, GPS, WiFi, etc...).

This is also documented in the CHANGELOG.md. Suggested method of working is to first call the `getLastKnownPosition` and update the value later with the outcome of the `getCurrentPosition` method.

**Comment by michaelsof47** [comment] 2021-08-30 12:33
wow, it's works. after i tried install an apps. it makes only 3-4 seconds within LocationAccuracy.medium. but, it not works on LocationAccuracy.high when relogin and i try access it. it makes 28 seconds to get current location

**Comment by mvanbeusekom** [comment] 2021-08-30 12:54
@michaelsof47 which platform are you using (iOS or Android)?

**Comment by sandeepgurram** [comment] 2021-11-03 12:03
> wow, it's works. after i tried install an apps. it makes only 3-4 seconds within LocationAccuracy.medium. but, it not works on LocationAccuracy.high when relogin and i try access it. it makes 28 seconds to get current location.
> 
> i'm really thank you about new update version. you're saving my time sir

I am also facing same issue with 7.7.1 version with real device, but it works fine with simulator.

**Comment by MuraliThangavel** [comment] 2021-11-18 09:44
i am also facing delay in iphone . in android it is working perfectly

**Comment by mvanbeusekom** [comment] 2021-11-18 09:46
@sandeepgurram, @MuraliThangavel, this is expected behaviour and explained in more detail in issue #887. Older versions (pre-7.6.0) of the geolocator actually contained a bug when fetching the current position (see issue #629) which was fixed in [version 7.6.0](https://pub.dev/packages/geolocator/changelog#760).

**Comment by MuraliThangavel** [comment] 2021-11-18 09:53
@mvanbeusekom , i am using 7.7.1 . but still it takes 10 seconds to fetch the location. what is the exact solution for this ? please help me

**Comment by mvanbeusekom** [comment] 2021-11-18 09:57
@MuraliThangavel as mentioned this is expected behaviour. More information in issue #887 I suggest you read it carefully.

**Comment by obolorhuu** [comment] 2021-12-01 08:13
same for me, IOS 14, and location package last version. How can i fix this error.

**Comment by mvanbeusekom** [comment] 2021-12-01 08:15
@obolorhuu please read the comments above: 

- https://github.com/Baseflow/flutter-geolocator/issues/320#issuecomment-908296930
- https://github.com/Baseflow/flutter-geolocator/issues/320#issuecomment-972701940
- https://github.com/Baseflow/flutter-geolocator/issues/320#issuecomment-972710347
