### ISSUE TITLE
Changed AndroidManifest path for permissions

### ISSUE THREAD

**Issue by ykws** [Baseflow/flutter-geolocator#359] opened 2019-12-16 08:59 UTC
Flutter generated two AndroidManifest for permissions.

`android/app/src/main` -> `android/app/src/profile`

<img width="328" alt="Screen Shot 2019-12-16 at 17 43 11" src="https://user-images.githubusercontent.com/5770480/70892913-68144f00-202d-11ea-948d-d927b5af9df9.png">

**Comment by ykws** [comment] 2019-12-16 09:10
But without permissions, we can retrieve the location 🤔 
It's the example on this repository.

**Comment by mvanbeusekom** [comment] 2019-12-16 09:29
@ykws the idea is that the values in the `android/app/src/main/AndroidManifest.xml` are propagated to the `android/app/src/profile/AndroidManifest.xml` and `android/app/src/debug/AndroidManifest.xml` files. 

The `android/app/src/profile` (or `android/app/src/debug` for that matter) are only used when you execute the App in either Profile or Debug mode. These `AndroidManifest.xml` files allow you to set settings specific for running in Debug or Profiling mode but you don't want in Release mode (e.g. special logging configuration).

So we on purpose added the permissions to the `android/app/src/main` version of the AndroidManifest.xml file just to make sure they always end-up in each configuration (Debug, Profile and Release).

There is a known issue which causes settings not being propagated correctly when changes are made to the AndroidManifest.xml file after it has been run on the emulator or real phone. To solve this you should"

1. Remove the App from the target device (emulator or real phone);
2. Run `flutter clean`;
3. Rerun the app from the IDE.

This should solve all problems and propagate all settings from the `android/app/src/main/AndroidManifest.xml` file to the `profile` and `debug` versions of the same file.

I am closing this issue and the associated PR since this is working as intended. More information can be found here: https://developer.android.com/studio/build/index.html#sourcesets

**Closed by mvanbeusekom** 2019-12-16 09:29 UTC

**Comment by ykws** [comment] 2019-12-17 00:36
@mvanbeusekom I got it and appreciate the detail information.
