### ISSUE TITLE
The location service on the device is disabled.

### ISSUE THREAD

**Issue by lqminhlab** [Baseflow/flutter-geolocator#601] opened 2020-11-21 14:29 UTC
## 🐛 Bug Report

App still gets the location but throws an exception:

Unhandled Exception: The location service on the device is disabled.
E/flutter ( 6712): #0      MethodChannelGeolocator._handlePlatformException (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:192:9)
E/flutter ( 6712): #1      MethodChannelGeolocator.getPositionStream.<anonymous closure> (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:171:11)

**Version:**   geolocator: ^6.1.6

**Platform:** 
- [x] :robot: Android

**Comment by MercurialG** [comment] 2020-11-21 15:28
Same here
I/flutter (11976): The location service on the device is disabled.

**version:** geolocator: ^6.1.7

**Android API 30**

**Comment by nihara75** [comment] 2020-11-22 07:40
Yesterday it worked fine, today it shows like this

**Comment by samettonyali** [comment] 2020-11-22 21:32
I enabled/disabled the host machine's (Windows 10) location service and tried again and again on the Android Emulator, but didn't work :(

version: geolocator: ^6.1.7

Android API 30

**Comment by mvanbeusekom** [comment] 2020-11-23 09:19
Are the location services enabled on the device (or emulator)? Please check in "Settings" -> "Location" and make sure the "Use location" switch is set to "on".

**Comment by MercurialG** [comment] 2020-11-23 09:51
It is emulator, that was the first thing i checked, location is on, position is set, permission is given, problem is still here.

**Comment by mvanbeusekom** [comment] 2020-11-23 10:17
Going through the issues this seems to be a duplicate of issue #585. I will be closing this issue and track progress in issue #585.

**Closed by mvanbeusekom** 2020-11-23 10:17 UTC
Labels: type: duplicate

**Comment by sejr1996** [comment] 2020-12-29 01:56
I have the same error, I have reproduced it on the xiaomi Redmi Note 8, while on a huawei p20 lite it works fine.
I notice that the following method returns true when services are disabled on the xiaomi, it should return false, just as it happens on the huawei.
`await Geolocator.isLocationServiceEnabled ()`
