### ISSUE TITLE
Creating the object causes debug asserts on unsupported platforms

### ISSUE THREAD

**Issue by bksubhuti** [Baseflow/flutter-geolocator#818] opened 2021-08-22 12:16 UTC
## 🐛 Bug Report

I want to create the object and then use platform to exclude the init calls.
However, merely opening up a state widget where the object is made gives a platform plugin error in debug

platform_channel.dart
```
      throw MissingPluginException('No implementation found for method $method on channel $name');
    }

I'm not sure if merely including the file import file  is doing this or if it is the object creation.
I only get gps when a button is pressed.. 
Normally I like to have a class member gps object.
But if I move the code (including the object creation) into the onpressed method, there is still an assert as above.

// This gets called when button onpressed(){}
// pretty much all of the sample code.

  void initGps() async {
    if (Platform.isAndroid || Platform.isIOS) {
      Geolocator geoLocator = Geolocator();
      if (!_initPerformed) {
        bool serviceEnabled;
        LocationPermission permission;

        // Test if location services are enabled.
        serviceEnabled = await Geolocator.isLocationServiceEnabled();
        if (!serviceEnabled) {
          // Location services are not enabled don't continue
          // accessing the position and request users of the
          // App to enable the location services.
          return Future.error('Location services are disabled.');
        }



```
### Expected behavior
I want to be able to have the object or include files present and have one code base for desktop and mobile 
(this test and failure occurs on linux)

### Reproduction steps
You can try to build a file.. and if there is no mobile OS do not run anything.
Linux will assert and failure..will happen. (debug mode).
You can also clone my code https://github.com/bksubhuti/buddhist_sun
However, that code has the geolocator as a member of the gps screen.
You can move it to the gpsinit() but it won't make a difference.  it will still fail on linux 

### Configuration

So while the OS supported is ios or android.
It should be safe to use as a single code base without calling the gps functions

ubuntu 21.04
using latest stable dart flutter.

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by bksubhuti** [comment] 2021-08-22 12:19
I'm also getting trouble with the play store submission.  They say i'm not giving a popup to warn them, but I am and it is awaits the end of the alert popup.  However, I show the popup when they press the "get gps" button, before permission is requested.  I suspect an automation tool is pickup some functionality in a similar manner that the error is picking up  a problem.

**Comment by mvanbeusekom** [comment] 2021-08-23 06:07
@bksubhuti I am a bit confused. The Geolocator plugin uses a static class which cannot (and should not) be instantiated.

So when you do `Geolocator geolocator = Geolocator()` this must be some other class that is not part of the Geolocator plugin or you would get a compile error.

**Comment by bksubhuti** [comment] 2021-08-23 06:43
Well that is funny.. I do not see that object instantiation in the docs anymore..I'm not sure where i pulled that code from.. I'm not smart enough to figure it out.  Maybe it came from another place.. 
In any case.. I removed that declaration (it didn't do anything anyway)...
I succeeded on my phone for getting gps without it (as you expected)
I could reproduce the bug in linux (as you did not expect).

There were never compiler errors.. there was a runtime assert fail and it blocks the live debugger from running.  same issue without that instantiation as above.

Please see [](https://github.com/bksubhuti/buddhist_sun/blob/master/lib/views/gps_location.dart)

This is not a page, but just a statefulwidget for a sliding pageview;

or compile and run the whole project.
To repeat this.. run in linux desktop .. click on gps bottom nav icon.. 
it should succeed and load a dummy page.
go back home..
go back to gps nav bottom nav icon..
it will throw an error (debug only).
"missing  platform plugin"

Small note to take the time to show my appreciate for:
1.  Making this easy to use plugin
2. Documentation that worked for its intended platforms
3. Responding to this issue

**Comment by mvanbeusekom** [comment] 2021-08-23 07:52
@bksubhuti thank you for supplying the additional information. I will try to reproduce it, but first need to setup a linux machine. I will try to go through this today (my time is 10 am at the moment).

**Comment by bksubhuti** [comment] 2021-08-23 08:50
Fyi...I'm using Ubuntu 21.04 with added gnome desktop and xOrg boot.  Default is Wayland.
But I think standard ubuntu will give the same message.

I'm not the best coder.. but I believe the code is that has the instance never gets created (run time), but the compiler must be doing something.

My original code created the gps page, but I think this current code does not.

Just to be sure I ran this one more time.  I had to flip back and forth a few times instead of just once .  Try up to ten page switches 

I believe it has to do with the creation of the static object (no longer by my code as checked in)  The code assertion still happens.  The code never does anything with geoloader run time,

**Comment by mvanbeusekom** [comment] 2021-08-23 13:01
Hi @bksubhuti, 

I have just run your application (using the master branch) on my Linux installation (Ubuntu 21.04). I think I can reproduce the `MissingPluginException` error you are referring to, the problem however is that the error is not caused by the geolocator plugin but the wakelock plugin.

The error also occurs when switching between the "TMR" and "Cities" tabs (or the "TMR" and "GMT" tabs). You can see the error is caused by the wakelock plugin by analyzing the exeption below: 

```shell
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method stop on channel flutter_tts)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:57:7)
<asynchronous suspension>
#1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20:5)
<asynchronous suspension>
```

The error happens when the `WakeLockApi.toggle` method is being called. I am not familiar with this plugin and don't know how to help other then referring to [their GitHub repo](https://github.com/creativecreatorormaybenot/wakelock/issues) and suggest you create an issue there.

I will be closing this issue now because I couldn't find a relationship with the geolocator plugin. If I missed something please feel free to leave a comment and I will reopen the issue.

**Closed by mvanbeusekom** 2021-08-23 13:01 UTC

**Comment by bksubhuti** [comment] 2021-08-23 14:05
My sincere apologies with this...  sorry for the involved research.
Linux is easy, but setting up a flutter dev env is quite some doing.
Your Geolocator package is appreciated.
I don't see a solution to this and will look for a new plugin.

I have run into problems with the play store acceptance policy..
When it is resolved, I will hopefully try to submit some documentation for you :)
