### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by developerflutter** [Baseflow/flutter-geolocator#705] opened 2021-04-09 18:00 UTC
Unhandled Exception: MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator)

 Platform: 

- Android

**Comment by mvanbeusekom** [comment] 2021-04-13 08:48
Duplicate of #551. Try running `flutter clean` and `flutter pub get` and make sure you are on the correct gradle version. 

Closing by lack of information. If you wish us to spend our valuable time to help you, make sure you take some time yourself and make a proper bug report.

**Closed by mvanbeusekom** 2021-04-13 08:48 UTC
