### ISSUE TITLE
Hi @AhkamKhalaaf,

### ISSUE THREAD

**Issue by AhkamKhalaaf** [Baseflow/flutter-geolocator#1018] opened 2022-03-30 17:38 UTC
Hi @AhkamKhalaaf,

Based on the information provided I am assuming you are working on a Windows application. Windows support has only been officially endorsed since version 8.1.0 (see [CHANGELOG](https://pub.dev/packages/geolocator/changelog)). So please make sure you are using geolocator version 8.1.0. 

The most secure way to test this is by having a look at the `pubspec.lock` in the root of your Flutter project. Search for the "geolocator" package and it should show which version your project is currently using. Of course to be really sure you are on the correct version make sure you depend on version 8.1.0 in your `pubspec.yaml` file.

If for some reason you are stuck to version 8.0.4 you can add windows support by manually adding a dependency on the `geolocator_windows: ^0.1.0` package in you `pubspec.yaml` file (in addition to the `geolocator` dependency).

If this is all not working please provide more information:

- Contents of your `pubspec.lock` file;
- Output of the `flutter doctor -v` command;
- The platform you are targeting.

_Originally posted by @mvanbeusekom in https://github.com/Baseflow/flutter-geolocator/issues/1017#issuecomment-1083338782_

Hi @mvanbeusekom , thanks alot for your response , the error is still even if i used geolocator: ^8.2.0, i wanna to use it in mobile application not desktop , no thing found in pubspec.lock related geolocator

any suggestion to solve this problem ?
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  auto_size_text: ^3.0.0
  flutter_svg: ^0.22.0
  transparent_image: ^2.0.0
  easy_localization: ^3.0.0
  flutter_riverpod: ^1.0.3
  table_calendar: ^3.0.3
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  dio: ^4.0.4
  get_it: ^7.2.0
  shared_preferences: ^2.0.12
  dio_cookie_manager: ^2.0.0
  url_launcher: ^6.0.18
  google_maps_flutter: ^2.1.1
  flutter_html: ^2.2.1
  avoid_keyboard: ^0.3.0
problem is still even if i r un flutter clean and then flutter pub get

**Comment by mvanbeusekom** [comment] 2022-03-30 18:02
Closed as duplicate of #1017

**Closed** 2022-03-30 18:01 UTC
