### ISSUE TITLE
Location Services indicator never disappears

### ISSUE THREAD

**Issue by gridfriday** [Baseflow/flutter-geolocator#780] opened 2021-07-06 15:00 UTC
If I get the device's location using Geolocator.getPositionStream() and then later cancel the subscription, the location services indicator in the status bar never gets removed. Nothing short of force quitting the app will remove the indicator.

`late StreamSubscription<Position> positionStream;`

`void getPosition() {
   positionStream = Geolocator.getPositionStream().listen((Position pos) {
      ...
   });
}`

`void stopLocation() {
   positionStream.cancel();
}`

Is this expected behavior?

If I instead use Geolocator.getCurrentPosition(), the indicator will disappear after a few seconds. But I want continuous user location updates.

I'm using Geolocator 7.2.0+1, Flutter 2.2.0 and seeing the issue on the iOS 14.4 simulator and a real device running 10.2.

**Comment by MrBorsti** [comment] 2021-07-07 09:14
The cause seems to be the `controller.stream.asBroadcastStream()` in the `_wrapStream`. If the broadcast stream is canceled the underlying location subscription is not.
Changing it to `controller.stream.asBroadcastStream(onCancel: (sub) => sub.cancel());` or even change the whole stream to be a broadcast from `StreamController<dynamic>(...` to `StreamController<dynamic>.broadcast(...` will close everything and the indicator disappears.

What is the reason for this?

**Comment by incloudss** [comment] 2021-07-08 20:07
Do anyone know maybe if getting position stream with given configuration, then cancelling it, and then again getting position stream, but with different configuration(different time interval for example) will respect new configuration? Because from my quick investigaton, it will probably return old stream, and therefore the configuration will be not changed. It would also fits the theory with not disappearing indicator.

**Comment by huangkaichang** [comment] 2021-07-09 14:27
Remove stream while cancelling the subscription, fixed this problem for me.

**Comment by cto-leaps** [comment] 2021-07-15 15:08
Hi guys and thank you so much for this great library!
Any news on when this fix will be released?
many 🙏 in advance

**Comment by mvanbeusekom** [comment] 2021-07-16 08:47
@gridfriday, @MrBorsti, @incloudss, @cto-leaps, this issue is solved with version 2.3.1 of the geolocator_platform_interface package (which the geolocator package depends on).

The current version (7.2.0+1) of the geolocator plugin depends the geolocator_platform_interface using the following version `^2.2.0` constraint. So running `flutter pub upgrade` should resolve the issue. 

Today I will release a new version of the geolocator plugin package which will also update the constraint of the geolocator_platform_interface which should also remove the need of running `flutter pub upgrade`.

**Comment by mvanbeusekom** [comment] 2021-07-16 10:06
Version 7.3.0 has been published and should fix this issue.

**Closed by mvanbeusekom** 2021-07-16 10:06 UTC
