### ISSUE TITLE
geolocator getPositionStream stops listening to position updates after a while of mobile screen off and device idle

### ISSUE THREAD

**Issue by Yakoota** [Baseflow/flutter-geolocator#1023] opened 2022-04-07 15:30 UTC
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-04-07 20:25
Closing this issue due to lack of information.

I would gladly re-open the issue when required information is supplied (the platforms the issue occurs on, is background support enabled, reproduction steps, configuration send with the `getPositionStream` method, etc...).

**Closed** 2022-04-07 20:25 UTC

**Comment by MohammedHannoush** [comment] 2022-04-09 06:04
I've added all info

**Comment by johnray016** [comment] 2023-02-16 06:13
@MohammedHannoush  did you find any solution to this?

**Comment by JulianBissekkou** [comment] 2023-03-01 16:02
Please consider reopening this issue.
@mvanbeusekom

**Comment by FlawLessx** [comment] 2026-02-11 09:14
i still had this problem, after some times when the app paused by system, location update not sent anymore, i think getPositionStream not properly freground service
