### ISSUE TITLE
Can not build app in Android

### ISSUE THREAD

**Issue by AliAkberAakash** [Baseflow/flutter-geolocator#910] opened 2021-12-03 07:04 UTC
## 🐛 Bug Report

When I include the library and run pub get it runs fine. But when I try to build app it gives me the following errors
` e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (18, 8): Class 'GeolocationPlugin' is not abstract and does not implement abstract member public abstract fun onActivityPaused(@NonNull p0: Activity): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (106, 3): 'onActivityPaused' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (110, 3): 'onActivityResumed' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (114, 3): 'onActivityStarted' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (118, 3): 'onActivityDestroyed' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (122, 3): 'onActivitySaveInstanceState' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (126, 3): 'onActivityStopped' overrides nothing
e: /home/bs693/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (130, 3): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocation:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDevDebug failed with exit code 1 `

### Configuration
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)

**Version:** 8.0.0

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2021-12-03 07:54
Hi @AliAkberAakash, 

I see you are using the "[geolocation](https://pub.dev/packages/geolocation)" plugin which is a different plugin. We maintain the Flutter Favorite "[geolocator](https://pub.dev/packages/geolocator)" plugin. See the difference when I put them underneath each other:

```yaml
geolocation: ^1.1.2  # This is the plugin you are using now and giving you problems
geolocator: ^8.0.0   # This is the plugin we maintain
```
Of course you are welcome to switch to the [geolocator](https://pub.dev/packages/geolocator) plugin and if you have issues we would be happy to help out. 

As I am not familiar with the geolocation plugin I will be closing this issue.

**Closed by mvanbeusekom** 2021-12-03 07:54 UTC

**Comment by AliAkberAakash** [comment] 2021-12-03 08:02
> Hi @AliAkberAakash,
> 
> I see you are using the "[geolocation](https://pub.dev/packages/geolocation)" plugin which is a different plugin. We maintain the Flutter Favorite "[geolocator](https://pub.dev/packages/geolocator)" plugin. See the difference when I put them underneath each other:
> 
> ```yaml
> geolocation: ^1.1.2  # This is the plugin you are using now and giving you problems
> geolocator: ^8.0.0   # This is the plugin we maintain
> ```
> 
> Of course you are welcome to switch to the [geolocator](https://pub.dev/packages/geolocator) plugin and if you have issues we would be happy to help out.
> 
> As I am not familiar with the geolocation plugin I will be closing this issue.

Sorry I mistakenly pasted a different log. PLease see the updated one.

**Comment by mvanbeusekom** [comment] 2021-12-03 08:21
@AliAkberAakash sorry I still don't see any references to the geolocator plugin in the updated log. There is something related to the permission_handler which we also maintain. If you are still using version 8.0.0 I would strongly suggest you update to version 8.3.0 (we have solved several deprecation warning in versions [8.1.1](https://pub.dev/packages/permission_handler/changelog#811) and [8.1.5](https://pub.dev/packages/permission_handler/changelog#815). 

If you are not ready to migrate to Android `compileSdkVersion 31` you should stick to version 8.1.6 of the permission_handler plugin. 

If this doesn't solve your problem please be so kind to submit a [new issue](https://github.com/Baseflow/flutter-permission-handler/issues/new/choose) on the permission_handler plugin repo. In this issue please include the following information:

1. The exact version number of the plugin you are using;
2. The output of the `flutter doctor -v` command (note the `-v` flag);
3. The log of the error you are receiving.

**Comment by AliAkberAakash** [comment] 2021-12-03 08:59
Thanks! It was resolved after I updated the version. However I dIdn't understand the connection between these two.  Project runs fine when I have the permission_handler to an old version, but it causes issue when I add geolocator. Only when both libraries are latest versions, it builds the app.

**Comment by mvanbeusekom** [comment] 2021-12-03 09:08
There is no connection between the permission_handler and the geolocator plugin. The problem is most likely that you updated your App to target Android API 31 when you started using the geolocator plugin. Android API 30 and 31 were major releases both deprecating a lot of methods, this affects a lot of other plugins (like the permission_handler).

So the connection is the Android API version you configure in you App.

**Comment by AliAkberAakash** [comment] 2021-12-03 09:11
Yes! that was the reason. Sorry I missed this part in your previous comment. Thanks a lot for explaining it.
