### ISSUE TITLE
Geolocator.getCurrentPosition always returns same thing on ios or maybe returns last known location instead of current location

### ISSUE THREAD

**Issue by A-Azizi79** [Baseflow/flutter-geolocator#716] opened 2021-04-17 02:52 UTC
## Geolocator.getCurrentPosition always returns same thing on ios  
I'm using iOS simulator (iPhone 11) with custom location. I set it from simulator menu Features > Location > Custom Location.
and trying to get location with `await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high)` and if i change location and fetch it again the result is same, even on real device (iPhone 11)

**What do you think about this problem??**

### Expected behavior
when we try to fetch location it must be correct location not last known location so what i mean is like below:
```
device location is 52.514726, -0.1292423 now
result of Geolocator.getCurrentPosition() must be 52.514726, -0.1292423

device location is 37.514726, -1.1292423 now
result of Geolocator.getCurrentPosition() must be 37.514726, -1.1292423

device location is 24.514726, -6.1292423 now
result of Geolocator.getCurrentPosition() must be 24.514726, -6,1292423
```

**but geolocator behave like below !! even on real device (iPhone 11)**
```
device location is 52.514726, -0.1292423 now
result of Geolocator.getCurrentPosition() must be 52.514726, -0.1292423

device location is 37.514726, -1.1292423 now
result of Geolocator.getCurrentPosition() is 52.514726, -0.1292423

device location is 24.514726, -6.1292423 now
result of Geolocator.getCurrentPosition() is 52.514726, -0.1292423
```

Reproduction steps

    Run code in iOS Simulator
    Set custom location from simulator menu Features > Location > Custom Location
    Fetch current location by invoking Geolocator.getCurrentPosition()
    Set Another location from simulator menu Features > Location > Custom Location
    Fetch current location by invoking Geolocator.getCurrentPosition()

### Configuration
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
aliazizi@Alis-MacBook-Pro bin % ./flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 2.0.4 at /Users/aliazizi/Documents/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aliazizi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • 5B19BCC0-DA94-417C-A0C4-618EE0EBE62B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google

• No issues found!
```

**geolocator: ^7.0.3**

**Platform:** 
- [ ] :iphone: iOS

**Comment by callmediana** [comment] 2021-04-17 03:13
same here any solutions????

i really hate this bug

**Comment by A-Azizi79** [comment] 2021-04-17 04:56
Oh. i found something ! if we open another map application like google map or open map in our app (using map sdk like mapbox_gl, google map ,  etc...),  Geolocator will start working again !

**Comment by haashem** [comment] 2021-04-18 06:58
My issue is I had to open Gelocator sample app and start streaming, so geolocator in my app will start emitting location! I had this issue on android

**Comment by florissmit1** [comment] 2021-04-22 12:03
@haashem I can't reproduce it on Android, can you provide more information?

I can reproduce the issue on the iOS simulator. Later this week i will try to reproduce the issue on a local device. For now I will mark this issue as an iOS specific issue.

**Comment by haashem** [comment] 2021-05-06 09:13
@florissmit1 For me it's not reproducible on `geolocator: ^7.0.3`

**Comment by mvanbeusekom** [comment] 2021-07-21 07:27
closing this issue as duplicate of #629.

**Closed by mvanbeusekom** 2021-07-21 07:27 UTC
Labels: platform: ios
