### ISSUE TITLE
Cannot Find Symbol

### ISSUE THREAD

**Issue by Junama** [Baseflow/flutter-geolocator#557] opened 2020-10-21 19:23 UTC
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-6.1.1\android\src\main\java\com\baseflow\geolocator\permission\PermissionManager.java:53:
cannot find symbol
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                                                       ^
  symbol:   variable Q
  location: class VERSION_CODES

**Comment by mvanbeusekom** [comment] 2020-10-22 13:58
@Junama can you check which version you are using for the `compileSdkVersion` parameter in your  `android/app/build.gradle` file? This should be at least version 29.

Here is what the example build.gradle file looks like:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "io.flutter.plugins.cameraexample"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
        profile {
            matchingFallbacks = ['debug', 'release']
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by arikpre** [comment] 2020-10-22 20:55
I had the exact same issue, I can confirm that updating compileSdkVersion to 29 fixes the issue.

Thanks!

**Comment by mvanbeusekom** [comment] 2020-10-23 07:44
@arikpre thank you for confirming the solution. I will close this issue now.

**Closed by mvanbeusekom** 2020-10-23 07:44 UTC
Labels: platform: android, status: waiting for customer response
