### ISSUE TITLE
[Android]When set the location permission from phone, the App can not start

### ISSUE THREAD

**Issue by OliverKong** [Baseflow/flutter-geolocator#869] opened 2021-10-14 07:45 UTC
## 💬 Questions and [Help]

For questions or help we recommend checking:

Sample Code GitHub address：https://github.com/Baseflow/flutter-geolocator

When I run the example of the GitHub,I found the question below in Android.
First time start the sample APP, the location permission is granted. when I go to the phone's home page(**don't kill the process of sample APP**) and open the Setting of the phone, when I set the location permission to “denied”, and restart the App, I found the App in the background can't display. When I kill the process of the APP and reopen the App, the App is restarting, but it can not display the screen first time I was opened.
IOS is OK.

`[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1237], locale ja-JP)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (5 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: D:\OAS_DEV\java\jdk1.8.0_171\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_171-1-redhat-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 94.0.992.47

! Doctor found issues in 1 category.
Process finished with exit code 0`

**Comment by florissmit1** [comment] 2021-12-10 08:26
Thanks for reporting your issue. I looked into your issue, and I can reproduce it. Not only when using the `geolocator` plugin, but also when using other plugins that make use of permission handling, like the `camera`, `permission_handler` and `location` plugins. For now I will close this issue, since it's not `geolocator` related.

**Closed** 2021-12-10 08:27 UTC
