### ISSUE TITLE
IOS error:LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 1.)

### ISSUE THREAD

**Issue by dawiddszewczyk** [Baseflow/flutter-geolocator#1111] opened 2022-07-27 22:11 UTC
## 🐛 Bug Report
I use Stream.periodic(); method to get UserLocation after some time.But when I added app to background after I receive more than 3 parts of data (after 10 seconds one, and again until it do 3 loops) I get this error. Its weird cuz in first 3 loops everything works well and after 3 loops I get exemption like that.

### Expected behavior
After get more than 3 loops I want to don't have exertion there.
### Reproduction steps
```
1)
Stream.periodic(
        Duration(seconds:10),
        (_) async {
          controller.sink.add(await _baseSpotService.getUserLocation());
        },
      );
```
And subscribe to stream.
2) Put app to background and wait 20seconds.

**Version:**
 8.0.6

**Platform:** 
- [ 15.6] :iphone: iOS

**Comment by ggirotto** [comment] 2022-08-01 12:10
Not under the same circumstances, but we are also seeing occurrences of `kCLErrorDomain error 1` exception in production

**Comment by florissmit1** [comment] 2022-08-05 10:58
Hey @dawiddszewczyk and @ggirotto. The `kCLErrorDomain error 1` will only occur when the user denied access to location services. Just a few things to get things straight; Did you add the `NSLocationAlwaysUsageDescription` key to your Infop.list, added the Background mode Capability to your project and requested the user for the `always` permission?

**Comment by petro-i** [comment] 2023-01-20 12:43
Hi,

I observe this error too, but under specific conditions:
- run app as iPad app on Apple Silicon macOS machine (from App Store or in debug mode from Xcode)
- On first run of the app everything is OK, after user gives permission (I request the permissions with permission_handler plugin ahead of requesting location) - location determined without any error.
- on following app execution - the error described above observed. BUT permissions for location are definitely granted by user and checked in the code before location requested.

**Comment by ibraheemalayan** [comment] 2023-01-30 17:40
Same error here when

**Comment by TimHoogstrate** [comment] 2023-09-19 07:43
Dear @Dev-Paccore, @ibraheemalayan, @petro-i, @dawiddszewczyk,

I personally cannot reproduce this issue. In order to help us investigate the issue please read the following carefully:

Can anyone experiencing this error post the following: Version of geolocation; the output of 'flutter doctor -v' and test environment like iPhone (version)/iPad (version) and OS (version). 

Next to this also post detailed steps to reproduce and at least the minimal reproducible code including locationSettings. 

Furthermore, check your Privacy and Security -> location services settings on your test device. Verify if the switch for your app is switched on or off (it should be switched on). If it is switched off then you might have missed a step in the readme. If it is still switched off, let us know. 

Kind regards,

**Comment by ibraheemalayan** [comment] 2023-09-19 15:15
@TimHoogstrate 

I don't know how to reproduce the error, but our Sentry integration reported the following error, two days ago, on one of the testers phone.


![Screenshot 2023-09-19 at 18 13 25](https://github.com/Baseflow/flutter-geolocator/assets/35265448/74e45b23-236f-4d8f-a831-f4fcbe8a23c7)


iPhone 13 Pro (D63AP) ( IOS 16.1.2 )

**Comment by JulianBissekkou** [comment] 2023-09-19 15:19
This issue is very hard to reproduce. It happened a few times when the app was running in background for a long amount of time.
https://developer.apple.com/forums/thread/735929

**Comment by TimHoogstrate** [comment] 2023-09-20 07:48
Dear @ibraheemalayan,

Do you also use Stream.periodic? It looks like a different situation leading to the same error.

Kind regards,

**Closed** 2023-10-04 08:11 UTC
Labels: type: bug, status: needs more info, platform: ios, status: closed (missing info), P2

**Comment by S-Haq-ue** [comment] 2024-06-01 03:43
> Hi,
> 
> I observe this error too, but under specific conditions:
> 
> * run app as iPad app on Apple Silicon macOS machine (from App Store or in debug mode from Xcode)
> * On first run of the app everything is OK, after user gives permission (I request the permissions with permission_handler plugin ahead of requesting location) - location determined without any error.
> * after app restart - the error described above observed. BUT permissions for location are definitely granted by user and checked in the code before location requested.
> 
> No problem observed on iOS running iPhone.



> Hi,
> 
> I observe this error too, but under specific conditions:
> 
> * run app as iPad app on Apple Silicon macOS machine (from App Store or in debug mode from Xcode)
> * On first run of the app everything is OK, after user gives permission (I request the permissions with permission_handler plugin ahead of requesting location) - location determined without any error.
> * after app restart - the error described above observed. BUT permissions for location are definitely granted by user and checked in the code before location requested.
> 
> No problem observed on iOS running iPhone.

how did you solve this...??
