### ISSUE TITLE
geolocator.getCurrentPosition take a long time to return position on IOS

### ISSUE THREAD

**Issue by zSteppio** [Baseflow/flutter-geolocator#964] opened 2022-01-28 16:03 UTC
## 🐛 Bug Report

Whenever I call:

await Geolocator.getCurrentPosition (desiredAccuracy: LocationAccuracy.high); 

on ios it takes more than 10 seconds. 

**Version:** 8.0.5

**Platform:** 
- [ x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2022-01-28 16:23
Unfortunately this method can be slow iOS and is explained more detailed in this [comment](https://github.com/Baseflow/flutter-geolocator/issues/887#issuecomment-958123890) from issue #887. 

As explained in the comments this is intended behaviour from the iOS `requestLocation` method (see [official documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation)) and is to assure that the device indeed acquires the current location as precise as possible. The comment also explains to listen the `getPositionStream()` method as an alternative solution.

Since this is intended behaviour from Apple and out of our hands and there is an alternative provided I will now close this issue. Please feel free leave a comment if you have additional questions.

**Closed by mvanbeusekom** 2022-01-28 16:23 UTC
