### ISSUE TITLE
Geolocator's distance does not return value or return always the same one

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-geolocator#951] opened 2022-01-20 08:49 UTC
I use `geolocator` package for device coordinates tracking. I need to send current device coordinates to server each specified interval if distance is more than specified value. I noticed that if app is in background then `getDistanceBetween` returns almost the same value (I think this is because the current position is not changed), if device is off then it looks like even `geoPositionStream` stops generate events. So it looks like geo tracking is working only if app is in foreground but I need to track coordinates in both foreground and background modes.

Could you please to explain the current behaviour? What I had did wrong and how I can achieve what I need?

**Comment by mvanbeusekom** [comment] 2022-01-28 16:35
Hi @bambinoua,

At the moment the geolocator indeed only support fetching the location in the foreground. Issue #53 discusses background support but hasn't been implemented yet. 

Since this is a duplicate of issue #53 I will close this issue and keep tracking background support there.

**Closed by mvanbeusekom** 2022-01-28 16:35 UTC
