### ISSUE TITLE
Web Geolocation not possible with Mac Safari / iOS Browser

### ISSUE THREAD

**Issue by Beautylivery** [Baseflow/flutter-geolocator#707] opened 2021-04-11 04:02 UTC
## 🐛 Bug Report
The package works well with iOS, Chrome / Edge [On Mac] and the android simulator.
But if i try to request the Lon and Lat via _determinePosition() on Safari [MAC] or iOS then i just receive the message, that location services are not supported for the browser. 

Any idea whats missing or need to be done ?

### Configuration

**Version: geolocator: ^7.0.1 

**Platform:** 
- [ ] :iphone: iOS : Edge
- [ ] :iphone: iOS : Safari
- [ ] :Mac : Safari

**Comment by mvanbeusekom** [comment] 2021-04-12 16:03
@Beautylivery are you testing this with a server that is signed with a SSL certificate? Safari won't allow access to the geolocation API when the site is served from an insecure location (even if it is a local webserver).

**Comment by Beautylivery** [comment] 2021-04-17 08:59
Hey @mvanbeusekom sorry for the late reply...

i run the code on Firebase Hosting and it comes with HTTPS . therefore i assume this should not be the issue . 
I however have to use my VPN to access the Website, allthough i believe this wont make the difference ?

**Comment by wilyanto** [comment] 2021-04-26 06:31
Yes, I also faced this faced this issue. Everything works fine beside browser in macOS or iOS (not only Safari, but also other browsers)

Always getting `PlatformException(LOCATION_SERVICES_NOT_SUPPORTED, Location services are not supported on this browser., null, null)`

**Comment by Wiklem** [comment] 2021-05-03 14:34
LOCATION_SERVICES_NOT_SUPPORTED , same issue as mentioned above for 7.0.3

**Comment by florissmit1** [comment] 2021-05-04 08:09
There is a known bug in Dart, causing the Flutter web app to fail when using null safety in release mode. It's working fine on iOS/macOS when building your Flutter web app with the `--no-sound-null-safety` flag (`flutter build web --no-sound-null-safety`).

**Comment by florissmit1** [comment] 2021-05-04 09:07
@wilyanto @Wiklem I looked into the issue. There is a known issue in Dart which causes the Flutter web application to fail when using null safety, see [issue]](https://github.com/Baseflow/flutter-geolocator/issues/693) and [issue](https://github.com/dart-lang/sdk/issues/45562) for more info. You can solve this for now by using the `--no-sound-null-safety` flag when building/debugging your web application, f.e. `flutter build web --no-sound-null-safety`.

**Comment by florissmit1** [comment] 2021-05-04 09:34
@Beautylivery I tried to reproduce your issue, but for me it's working totally fine on macOS/iOS devices using the example application.

My flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale nl-NL)
    • Flutter version 2.0.6 at /usr/local/Caskroom/flutter/2.0.5/flutter
    • Framework revision 1d9032c7e1 (4 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/florissmit/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
Steps to reproduce:
Execute `firebase init` in the example app
Select `❯◯ Hosting: Configure and deploy Firebase Hosting sites`
Next select `Use an existing project` OR `Create a new project`
Use the build/web folder as the public Firebase directory: `What do you want to use as your public directory? build/web`
```
? Configure as a single-page app (rewrite all urls to /index.html)? No
? Set up automatic builds and deploys with GitHub? No
✔  Wrote build/web/404.html
? File build/web/index.html already exists. Overwrite? No
i  Skipping write of build/web/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```
Then, build your Flutter web application: `flutter build web --no-sound-null-safety` (don't forget to execute `flutter pub get` first). Check my previous comment about why u should use the `--no-sound-null-safety` flag when building a web release.

Finally, deploy your application to Firebase by executing `firebase deploy`. 
I deployed the example application to the following URL: https://fir-test-web-geolocator-2.web.app/#/

**Comment by Wiklem** [comment] 2021-05-04 10:42
> @wilyanto @Wiklem I looked into the issue. There is a known issue in Dart which causes the Flutter web application to fail when using null safety, see #693 and [issue](https://github.com/dart-lang/sdk/issues/45562) for more info. You can solve this for now by using the `--no-sound-null-safety` flag when building/debugging your web application, f.e. `flutter build web --no-sound-null-safety`.

This solves the problem for other browsers like chrome (building with flutter build web --no-sound-null-safety), but Safari still gives the error PlatformException(LOCATION_SERVICES_NOT_SUPPORTED, Location services are not supported on this browser., null, null). 

Same error for both iphone and mac on safari

**Comment by florissmit1** [comment] 2021-05-04 12:32
@Wiklem I think you should rewrite your code a bit. 
1. U should await `Geolocator.openLocationSettings();`
2. Geolocator.openLocationSettings is not supported on web, if u want to separate your web code and your native iOS/Android code u can use something like this:
```
import 'package:flutter/foundation.dart' show kIsWeb;

if (kIsWeb) {
  // Code executed when platform = web
} else {
  // NOT running on web, code is executed on all other platforms
}
```
3. Also, you are using the `Geolocator.getPositionStream();` wrong, take a look at the [docs](https://pub.dev/packages/geolocator). Here you can find the implementation of the example application and more useful information.

Since the example app is working fine, I guess you should take a look at it.

**Comment by Wiklem** [comment] 2021-05-04 14:48
Thank you, must have read somewhere else. 

Works with the new setup from docs and no sound null safety :)

New controller setup
`
class LocationController extends GetxController {
  static LocationController get to => Get.find();
  Stream<Position> getPositionStream() {
    return Geolocator.getPositionStream(
        desiredAccuracy: LocationAccuracy.high, distanceFilter: 5);
  }

  void requestPermission() {
    Geolocator.requestPermission().then((value) => getPosition());
  }

  Future<bool> locationSettings() async {
    bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if (!kIsWeb) Geolocator.openLocationSettings();
      return Future.error('Location services are disabled.');
    }
    return serviceEnabled;
  }

  Future<bool> permissionSettings() async {
    LocationPermission permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied ||
        permission == LocationPermission.deniedForever) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied ||
          permission == LocationPermission.deniedForever) {
        Get.dialog(LocationPermissionDialog());
        return false;
      }
    } else {
      return true;
    }
    return false;
  }

  Future<bool> checkPermission() async {
    return await locationSettings() && await permissionSettings();
  }

  Future<Position?> getPosition() async {
    // Test if location services are enabled.
    bool location = await locationSettings();
    bool permission = await permissionSettings();

    if (permission && location) {
      return await Geolocator.getCurrentPosition();
    }
  }
}
`

**Comment by florissmit1** [comment] 2021-05-05 06:16
Nice to hear that it worked out for you, I'm closing the issue for now.

**Closed** 2021-05-19 07:15 UTC
Labels: status: needs more info

**Comment by makthis** [comment] 2021-09-21 16:41
I am having the same issue with Safari on Mac Safari and iOS. 

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-arm, locale
    en-US)
    • Flutter version 2.5.1 at /Users/mudassirchapra/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
    • Android SDK at /Users/mudassirchapra/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Android Studio
    • Android Studio at /Users/mudassirchapra/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • BE4557CD-603A-4513-92B9-25CE2CA7C20B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.82
```

The code:

```
LocationPermission safariPermission;

        safariPermission = await Geolocator.checkPermission();

        if (safariPermission == LocationPermission.denied) {
          safariPermission = await Geolocator.requestPermission();
          if (safariPermission == LocationPermission.deniedForever) {
            await locationPermissionDialog();
            return Future.error(
              'Please eneable Location permissions in the settings',
            );
          }
        }
        var geoLocator = await Geolocator.getCurrentPosition();

        return LocationData.fromMap({
          'latitude': geoLocator.latitude,
          'longitude': geoLocator.longitude,
        });
```
