### ISSUE TITLE
[Bug]: NoSuchMethodError when opening dynamic links from Facebook

### ISSUE THREAD

**Issue by karthikk9828** [Baseflow/flutter-geolocator#1311] opened 2023-08-23 15:07 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. Install Facebook freshly, do not go to any screen that displays location permission dialog. This bug will not occur if location permission dialog has been displayed, does not matter if the permission was given or denied.
2. Post dynamic link of a webpage that uses location in Facebook.
3. Click on the link on Facebook

The issue seems to be with `watchPosition()` returning null. Since this happens in production, I can see the obfuscated logs only. 

I was able to fix it by by making the below changes in `main.dart.js`
**before**
```js
aBn(a,b,c,d){var s=a.watchPosition(b,A.km(c,1),d)
s.toString
return s}}
```

**after**
```js
aBn(a,b,c,d){var s=a.watchPosition(b,A.km(c,1),d)
if(s!=null)s.toString
return s}}
```

### Expected results

1. Webpage of the dynamic link should be displayed

### Actual results

Webpage is opened with error
```console
NoSuchMethodError: method not found: toString on null
```

It is not possible to test it in debug mode so the stack trace is obfuscated.

### Code sample

<details><summary>Code sample</summary>

```dart
Stream<LatLng?> latLngChanges() {
    final geolocatorPlatform = GeolocatorPlatform.instance;
    return geolocatorPlatform.getPositionStream().transform(
          StreamTransformer<Position, LatLng?>.fromHandlers(
            handleData: (position, sink) {
              sink.add(LatLng(position.latitude, position.longitude));
            },
            handleError: (e, s, sink) {
              if (!e.toString().contains('Only secure origins are allowed')) {
                Logger().e('Failed to get location.', e, s);
              }
              sink.add(null);
            },
          ),
        );
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by TimHoogstrate** [comment] 2023-08-29 09:32
Dear @karthikk9828,

Can you elaborate a bit on the issue? It is very hard to reproduce if we don't have any example project that we can run and perhaps some more detailed steps to reproduce. Is it possible to reproduce this in debug mode?

I also cannot find anything related to:

```
aBn(a,b,c,d){var s=a.watchPosition(b,A.km(c,1),d)
s.toString
return s}}
```
In the geolocator codebase...

Kind regards,

**Comment by karthikk9828** [comment] 2023-08-30 09:16
@TimHoogstrate 
Unfortunately I cannot share the entire code as this happened in an enterprise project. 
I thought maybe someone can help me identify the code that I mentioned and can fix it.

**Comment by TimHoogstrate** [comment] 2023-08-30 09:28
Sorry, it seems that I cannot help you for now. It is unclear to me what the issue is. It looks like your "s" is null. But i don't see how to reproduce this.

Kind regards,

**Comment by mvanbeusekom** [comment] 2023-09-05 09:36
@karthikk9828, 

Do I understand correctly that the webpage you link to from Facebook is a Flutter web application making use of the geolocator plugin?

If the webpage is opened, which browser is being used? Is the page opened internally in the Facebook app, Safari or a different browser?

If so can you confirm that you check / request permissions before accessing the `getPositionStream` method? This is not mentioned in your original post.

**Comment by karthikk9828** [comment] 2023-09-05 10:08
@mvanbeusekom 

> Do I understand correctly that the webpage you link to from Facebook is a Flutter web application making use of the geolocator plugin?
Yes

> If the webpage is opened, which browser is being used? Is the page opened internally in the Facebook app, Safari or a different browser?
It opens internally in the Facebook app

> Does this only happen in Facebook or can you also reproduce this in other applications (e.g. Twitter) or by directly opening the link to the webpage in the browser?
It happens only in Facebook app, I have tested in Twitter and other apps and it is working fine

> If so can you confirm that you check / request permissions before accessing the getPositionStream method? This is not mentioned in your original post.
The important pre-condition of this issue is as mention in the steps to reproduce section
Install Facebook freshly, do not go to any screen that displays location permission dialog. This bug will not occur if location permission dialog has been displayed, does not matter if the permission was given or denied.

**Comment by mvanbeusekom** [comment] 2023-09-12 13:26
Hi @karthikk9828,

Thank you for this response. The problem here is that Facebook loads the page inside an embedded [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) component. When embedding a [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) component the host app (in this case the Facebook app) will stay responsible to dealing with permissions. 

In this particular case the Facebook app has not requested permissions and therefore the web application (loaded within the embedded [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) component) is not allowed to access the location information.

I will go ahead and close this issue, as it is out of our control and can only be fixed by the developers of the Facebook App.

**Closed by mvanbeusekom** 2023-09-12 13:26 UTC
Labels: platform: web
