### ISSUE TITLE
Error on Android 9.0 (API 28) - Resources$NotFoundException: Resource ID #0x7f0808d3 

### ISSUE THREAD

**Issue by burhanaksendir** [Baseflow/flutter-geolocator#1369] opened 2023-11-07 14:52 UTC
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

When running it on Android 9.0 (API 28), I encounter the following error with Resource ID #0x7f0808d3:

```
FATAL EXCEPTION: main
Process: com.google.android.gms.ui, PID: 18190
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0808d3
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
  ...
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0808d3
  ...
```

This error is preventing my app from functioning, and I haven't been able to resolve it. I'm seeking assistance to address this issue related to Geolocator or Android 9.0. Any suggestions or guidance on resolving this error would be greatly appreciated.

Thank you!

### Version

10.1.0

**Comment by TimHoogstrate** [comment] 2023-11-08 10:19
Dear @burhanaksendir,

Can you elaborate a bit on the issue? What are you trying to run? The Geolocator example app? I also cannot find `LocationSettingsCheckerActivity` in the code base.

Kind regard,

**Comment by burhanaksendir** [comment] 2023-11-08 20:41
Dear @TimHoogstrate,
Thank you. I'm explaining step by step for you to reproduce the same issue:
1- Download the project from https://github.com/Baseflow/flutter-geolocator.
2- Connect a real device with Android 9 - API 28 to your computer or create an emulator.
3- Run the geolocator example app in VSCode or Android Studio.
4- Run the sample application. You will see the error you mentioned in Logcat and Debug Console.

I'm also sharing some screenshots. I appreciate your assistance.

Best regards,

<img width="1898" alt="Ekran Resmi 2023-11-08 23 35 03" src="https://github.com/Baseflow/flutter-geolocator/assets/8548639/54aa33a4-fab0-45d6-87f1-b9350e3c5715">

**Comment by AliJ91** [comment] 2023-11-10 09:13
Was this resolved?
im facing the same issue

**Comment by burhanaksendir** [comment] 2023-11-11 15:24
Hi @AliJ91 
The issue still persists; I haven't been able to find a solution.

**Comment by mvanbeusekom** [comment] 2023-11-14 10:16
Hi @burhanaksendir, @AliJ91,

A quick update from our side, we are now able to reproduce the issue. Note that if you do a fresh installation off the example application you have to start the location stream for the error to show up.

After that the error shows up immediately when you try to run it. Debugging the native JAVA code shows an error related to starting a foreground service. 

I will continue looking into the error and keep you updated on any progress here.

**Comment by AliJ91** [comment] 2023-11-17 12:43
@mvanbeusekom  Hello, yep only on emulator this error appeared

**Comment by mvanbeusekom** [comment] 2023-11-20 08:12
Hi @AliJ91, @burhanaksendir,

Thank you both for testing. Unfortunately we also don't have access to a Samsung S8+ which makes testing difficult. I have done more detailed debugging on the emulator and turns out that the error (when running on the emulator) is caused be the `startResolutionForResult` method which is part of Androids [SettingsApi](https://developers.google.com/android/reference/com/google/android/gms/location/SettingsApi). 

According to the documentation this should work on the API 28. A workaround for now would be utilising the [device_info_plus](https://pub.dev/packages/device_info_plus) plugin and force the use of the legacy `LocationManager` when running on Android 9 (API 28). This could look something like this:

```dart
final AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
LocationSettings? locationSettings;

if (Platform.isAndroid) {
  locationSettings = AndroidSettings(
    forceLocationManager: androidInfo.version.sdkInt == 28,
  );
}

final Position position = await Geolocator.getCurrentPosition(locationSettings: locationSettings);
```

The code snippet works around the problem at least on the emulator in my tests. For now I will close this issue as it seems this is out of our hands and seems a bug in Android or certain Android versions provided by telephone manufactures and a workaround is available.

**Closed by mvanbeusekom** 2023-11-20 08:12 UTC
Labels: type: bug, platform: android, P2

**Comment by EArminjon** [comment] 2024-05-14 07:54
Without the tricks above getCurrentPosition() dead lock on Android 9. This must be mentioned in documentation.
Major issue.
