### ISSUE TITLE
Not working on iOS 16

### ISSUE THREAD

**Issue by Morfeus73** [Baseflow/flutter-geolocator#1128] opened 2022-09-15 08:16 UTC
## 🔙 Regression

The plugin seems not work anymore on iOS 16, Xcode 14.

### Old (and correct) behavior
Geolocator.isLocationServiceEnabled() was correclty getting the system service information.

### Current behavior
Geolocator.isLocationServiceEnabled() throws 
> [CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

### Reproduction steps
Compile the example with Xcode 14 and launch the app on iOS16 device.

**Comment by blubearec** [comment] 2022-09-18 13:48
Same here!

**Comment by luttmfra** [comment] 2022-09-22 15:00
I get the same error message.

**Comment by Polibuzz** [comment] 2022-09-23 14:58
I'm using Flutter and have a button to bring me to current location which works my device but doesn't work when using the iPhone simulator. But I'm also getting this same error.

**Comment by tayyabmughal676** [comment] 2022-10-07 10:37
[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

Waiting for a possible solution. :)

**Comment by kekko7072** [comment] 2022-10-08 11:12
+ 1

**Comment by JulianBissekkou** [comment] 2022-10-18 08:51
Is this a duplicate of #1151?

**Comment by Tom3652** [comment] 2022-10-25 11:01
I do see the same logs but the plugin is still able to fetch the localization on iOS 16 on my devices

**Comment by dario-digregorio** [comment] 2022-11-14 09:49
I am unable to build my app. Is there a temporary solution?

**Comment by abdalmonem** [comment] 2022-12-26 05:35
is there any solution ?

**Comment by sparshba** [comment] 2023-01-05 20:49
anyone found the solution??

**Comment by diego-lipinski-de-castro** [comment] 2023-01-20 07:30
are we fucked?

**Comment by yzengin** [comment] 2023-02-02 19:04
This issue needs an urgent solution!

**Comment by abdalmonem** [comment] 2023-02-04 07:57
@yzengin we all agree , i have tried to found another packages , but the issue showed on all of them , we end up our app and prepare it for launch and waiting to solve this to upload it the the appstore :( , such a disappointment thing

**Comment by dungnguyenBKA** [comment] 2023-05-31 06:50
@abdalmonem did you found a solution for this problem? we also have an app which is ready submit to store.

**Comment by abdalmonem** [comment] 2023-06-01 06:33
@dungnguyenBKA 
yes , looks the issue is not in the plugin it self , we can say its just xcode warning,
a lot of time pass , but i remember , i delete the app , clean flutter project then clean x code (product>clean builder folder).

i used this dependencys :
`
  geolocator: ^9.0.2
  geolocator_apple: ^2.2.5
  permission_handler: ^10.2.0
`

i copy this part from my project , and its work:
`
PermissionStatus permission = await Permission.locationWhenInUse.status;
if (permission == PermissionStatus.denied) {
        await Future.delayed(Duration(microseconds: 200)); // i dont remember why there is delay here , if code works fine , try to remove it, maybe its reverent to 
        permission = await Permission.locationWhenInUse.request();
        Position position = await Geolocator.getLastKnownPosition();
        Position newPosition = await Geolocator.getCurrentPosition();
}
`

in my info.plist:
`
        <key>NSLocationAlwaysUsageDescription</key>
	<string>XXX app needs access to location when in the background.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>XXX app needs access to location when open.</string>
`

for the permission handler , read : 
https://pub.dev/packages/permission_handler

you need to un comment : `'PERMISSION_LOCATION=1'`

**Closed** 2023-06-05 15:24 UTC
Labels: platform: ios
