### ISSUE TITLE
iOS Location stream will timeout when manually getting current position

### ISSUE THREAD

**Issue by zbarbuto** [Baseflow/flutter-geolocator#999] opened 2022-03-04 05:32 UTC
## 🐛 Bug Report

On iOS simulator, setting the device to a mock location stream (such as City Run) will produce events in `Geolocator.getPositionStream()`.

However, if you call `Geolocator.getCurrentPosition()` while listening to this stream, the current position will return a result but the position stream effectively dies (will time out if one is set or never return updates if timeout is not set).

### Reproduction steps

Below is a minimal flutter app to reproduce the issue. 

1. Set iOS simulator to "City Run" under "Features" -> "Location"
2. Hit "Request Permission" and allow while using app
3. Hit "Restart Stream" if not already printing location updates
4. Hit "Get Position" and wait ~5 seconds for the stream to error

You can hit "restart stream" and reproduce the error again (stream will listen and print updates until "Get Position" is pressed).

<img width="614" alt="image" src="https://user-images.githubusercontent.com/9100419/156705435-9a37138a-b895-43a1-8e50-3ad7a40d9243.png">

The workaround I am using is to just re-create the stream on a `TimeoutException` occurs but ideally the stream would keep producing results even if a manual request for location check is made.

```dart
class StreamExample extends StatefulWidget {
  const StreamExample({Key? key}) : super(key: key);

  @override
  State<StreamExample> createState() => _StreamExampleState();
}

class _StreamExampleState extends State<StreamExample> {
  @override
  void initState() {
    _setupStream();
    super.initState();
  }

  _setupStream() {
    Geolocator.getPositionStream(
            locationSettings:
                const LocationSettings(timeLimit: Duration(seconds: 5)))
        .listen((event) {
      print(event);
    }).onError((e) {
      if (e is TimeoutException) {
        print('Stream timeout');
      } else {
        print(e);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(children: [
            TextButton(
                onPressed: () {
                  Geolocator.requestPermission();
                },
                child: Text('Request Permissions')),
            TextButton(
                onPressed: () async {
                  print('Getting position...');
                  final position = await Geolocator.getCurrentPosition();
                  print('Manual position was: ${position.toString()}');
                },
                child: Text('Get Position')),
            TextButton(
                onPressed: () {
                  _setupStream();
                },
                child: Text('Restart stream'))
          ]),
        ),
      ),
    );
  }
}
```

### Configuration

**Version:**  8.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by JustChris** [comment] 2022-03-24 09:51
I can confirm this. I believe that this problem has existed before and has already been fixed. 

Additionally, when you are listening to the location stream but there is no movement of the device i.e. the location stream is not emitting location updates, a manual `getCurrentPosition` will never return a value.

That's a major break for me.

**Comment by tsuncp** [comment] 2022-06-13 06:17
any update on it? Currently, I have to avoid to use `getCurrentPosition` on iOS.

**Comment by geisterfurz007** [comment] 2022-07-07 06:51
This *might* be a duplicate of #1040

**Comment by Wackymax** [comment] 2022-09-19 11:48
Anyone familiar with iOS that can maybe help with a PR to resolve this?

**Comment by anovis** [comment] 2022-10-11 17:21
any updates on this?

**Comment by zbarbuto** [comment] 2022-10-11 21:34
@anovis I think it probably won't be getting fixed as it's an issue with the SDK provided by Apple [per this comment](https://github.com/Baseflow/flutter-geolocator/issues/1040#issuecomment-1149660004).

**Comment by JeroenWeener** [comment] 2023-09-12 15:46
Closing this issue, as it appears to be an iOS problem (see https://github.com/Baseflow/flutter-geolocator/issues/999#issuecomment-1275298975)

**Closed by JeroenWeener** 2023-09-12 15:46 UTC
Labels: type: bug, platform: ios, P2
